// Code generated from classic socat tag-1.8.1.3. DO NOT EDIT.
// Source: git://repo.or.cz/socat.git tag-1.8.1.3 (xio*.c, xioopen.c).
//go:generate python3 ../../scripts/extract-classic-groups.py /tmp/socat-classic/src

package xio

// ClassicAddressGroups is the expanded GROUP_* set for each address keyword
// in classic socat 1.8.1.3. Aliases from addressnames[] are included.
var ClassicAddressGroups = map[string][]string{
	"-":                     []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"ABSTRACT":              []string{"fd", "socket", "sock-unix", "retry"},
	"ABSTRACT-CLIENT":       []string{"fd", "socket", "sock-unix", "retry"},
	"ABSTRACT-CONNECT":      []string{"fd", "socket", "sock-unix", "retry"},
	"ABSTRACT-LISTEN":       []string{"fd", "socket", "sock-unix", "listen", "child", "retry"},
	"ABSTRACT-RECV":         []string{"fd", "socket", "sock-unix", "retry"},
	"ABSTRACT-RECVFROM":     []string{"fd", "socket", "sock-unix", "retry", "child"},
	"ABSTRACT-SENDTO":       []string{"fd", "socket", "sock-unix", "retry"},
	"ACCEPT":                []string{"fd", "socket", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite", "child", "range", "retry"},
	"ACCEPT-FD":             []string{"fd", "socket", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite", "child", "range", "retry"},
	"CREAT":                 []string{"fd", "named", "reg"},
	"CREATE":                []string{"fd", "named", "reg"},
	"DATAGRAM":              []string{"fd", "socket", "range"},
	"DCCP":                  []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-dccp", "child", "retry"},
	"DCCP-CONNECT":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-dccp", "child", "retry"},
	"DCCP-L":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-dccp", "listen", "child", "range", "retry"},
	"DCCP-LISTEN":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-dccp", "listen", "child", "range", "retry"},
	"DCCP4":                 []string{"fd", "socket", "sock-ip4", "ip-dccp", "child", "retry"},
	"DCCP4-CONNECT":         []string{"fd", "socket", "sock-ip4", "ip-dccp", "child", "retry"},
	"DCCP4-L":               []string{"fd", "socket", "sock-ip4", "ip-dccp", "listen", "child", "range", "retry"},
	"DCCP4-LISTEN":          []string{"fd", "socket", "sock-ip4", "ip-dccp", "listen", "child", "range", "retry"},
	"DCCP6":                 []string{"fd", "socket", "sock-ip6", "ip-dccp", "child", "retry"},
	"DCCP6-CONNECT":         []string{"fd", "socket", "sock-ip6", "ip-dccp", "child", "retry"},
	"DCCP6-L":               []string{"fd", "socket", "sock-ip6", "ip-dccp", "listen", "child", "range", "retry"},
	"DCCP6-LISTEN":          []string{"fd", "socket", "sock-ip6", "ip-dccp", "listen", "child", "range", "retry"},
	"DGRAM":                 []string{"fd", "socket", "range"},
	"DTLS":                  []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"DTLS-C":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"DTLS-CLIENT":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"DTLS-CONNECT":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"DTLS-L":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range", "openssl", "retry"},
	"DTLS-LISTEN":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range", "openssl", "retry"},
	"DTLS-SERVER":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range", "openssl", "retry"},
	"ECHO":                  []string{"fd", "named", "open", "fifo"},
	"EXEC":                  []string{"fd", "fork", "exec", "socket", "sock-unix", "termios", "fifo", "pty", "parent"},
	"FD":                    []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"FIFO":                  []string{"fd", "named", "open", "fifo"},
	"FILE":                  []string{"fd", "fifo", "chr", "blk", "reg", "named", "open", "termios"},
	"GOPEN":                 []string{"fd", "fifo", "chr", "blk", "reg", "named", "open", "termios", "socket", "sock-unix"},
	"IF":                    []string{"fd", "socket", "interface"},
	"INET":                  []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "retry"},
	"INET-L":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"INET-LISTEN":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"INET4":                 []string{"fd", "socket", "sock-ip4", "ip-tcp", "child", "retry"},
	"INET4-L":               []string{"fd", "socket", "sock-ip4", "ip-tcp", "listen", "child", "range", "retry"},
	"INET4-LISTEN":          []string{"fd", "socket", "sock-ip4", "ip-tcp", "listen", "child", "range", "retry"},
	"INET6":                 []string{"fd", "socket", "sock-ip6", "ip-tcp", "child", "retry"},
	"INET6-L":               []string{"fd", "socket", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"INET6-LISTEN":          []string{"fd", "socket", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"INTERFACE":             []string{"fd", "socket", "interface"},
	"IP":                    []string{"fd", "socket", "sock-ip4", "sock-ip6"},
	"IP-DATAGRAM":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "range"},
	"IP-DGRAM":              []string{"fd", "socket", "sock-ip4", "sock-ip6", "range"},
	"IP-RECV":               []string{"fd", "socket", "sock-ip4", "sock-ip6", "range"},
	"IP-RECVFROM":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "child", "range"},
	"IP-SEND":               []string{"fd", "socket", "sock-ip4", "sock-ip6"},
	"IP-SENDTO":             []string{"fd", "socket", "sock-ip4", "sock-ip6"},
	"IP4":                   []string{"fd", "socket", "sock-ip4"},
	"IP4-DATAGRAM":          []string{"fd", "socket", "sock-ip4", "range"},
	"IP4-DGRAM":             []string{"fd", "socket", "sock-ip4", "range"},
	"IP4-RECV":              []string{"fd", "socket", "sock-ip4", "range"},
	"IP4-RECVFROM":          []string{"fd", "socket", "sock-ip4", "child", "range"},
	"IP4-SEND":              []string{"fd", "socket", "sock-ip4"},
	"IP4-SENDTO":            []string{"fd", "socket", "sock-ip4"},
	"IP6":                   []string{"fd", "socket", "sock-ip6"},
	"IP6-DATAGRAM":          []string{"fd", "socket", "sock-ip6", "range"},
	"IP6-DGRAM":             []string{"fd", "socket", "sock-ip6", "range"},
	"IP6-RECV":              []string{"fd", "socket", "sock-ip6", "range"},
	"IP6-RECVFROM":          []string{"fd", "socket", "sock-ip6", "child", "range"},
	"IP6-SEND":              []string{"fd", "socket", "sock-ip6"},
	"IP6-SENDTO":            []string{"fd", "socket", "sock-ip6"},
	"LOCAL":                 []string{"fd", "named", "socket", "sock-unix", "retry"},
	"OPEN":                  []string{"fd", "fifo", "chr", "blk", "reg", "named", "open", "termios"},
	"OPENSSL":               []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "openssl", "retry"},
	"OPENSSL-CONNECT":       []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "openssl", "retry"},
	"OPENSSL-DTLS-CLIENT":   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"OPENSSL-DTLS-CONNECT":  []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "openssl", "retry"},
	"OPENSSL-DTLS-LISTEN":   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range", "openssl", "retry"},
	"OPENSSL-DTLS-SERVER":   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range", "openssl", "retry"},
	"OPENSSL-LISTEN":        []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "openssl", "retry"},
	"PIPE":                  []string{"fd", "named", "open", "fifo"},
	"POSIXMQ":               []string{"fd", "open", "named", "posixmq", "retry"},
	"POSIXMQ-BIDIRECTIONAL": []string{"fd", "open", "named", "posixmq", "retry"},
	"POSIXMQ-READ":          []string{"fd", "open", "named", "posixmq", "retry"},
	"POSIXMQ-RECEIVE":       []string{"fd", "open", "named", "posixmq", "retry", "child"},
	"POSIXMQ-RECV":          []string{"fd", "open", "named", "posixmq", "retry", "child"},
	"POSIXMQ-SEND":          []string{"fd", "open", "named", "posixmq", "retry", "child"},
	"POSIXMQ-WRITE":         []string{"fd", "open", "named", "posixmq", "retry", "child"},
	"PROXY":                 []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "http", "child", "retry"},
	"PROXY-CONNECT":         []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "http", "child", "retry"},
	"PTY":                   []string{"named", "fd", "termios", "pty"},
	"READLINE":              []string{"fd", "termios", "readline"},
	"SCTP":                  []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-sctp", "child", "retry"},
	"SCTP-CONNECT":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-sctp", "child", "retry"},
	"SCTP-L":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-sctp", "listen", "child", "range", "retry"},
	"SCTP-LISTEN":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-sctp", "listen", "child", "range", "retry"},
	"SCTP4":                 []string{"fd", "socket", "sock-ip4", "ip-sctp", "child", "retry"},
	"SCTP4-CONNECT":         []string{"fd", "socket", "sock-ip4", "ip-sctp", "child", "retry"},
	"SCTP4-L":               []string{"fd", "socket", "sock-ip4", "ip-sctp", "listen", "child", "range", "retry"},
	"SCTP4-LISTEN":          []string{"fd", "socket", "sock-ip4", "ip-sctp", "listen", "child", "range", "retry"},
	"SCTP6":                 []string{"fd", "socket", "sock-ip6", "ip-sctp", "child", "retry"},
	"SCTP6-CONNECT":         []string{"fd", "socket", "sock-ip6", "ip-sctp", "child", "retry"},
	"SCTP6-L":               []string{"fd", "socket", "sock-ip6", "ip-sctp", "listen", "child", "range", "retry"},
	"SCTP6-LISTEN":          []string{"fd", "socket", "sock-ip6", "ip-sctp", "listen", "child", "range", "retry"},
	"SENDTO":                []string{"fd", "socket"},
	"SHELL":                 []string{"fd", "fork", "exec", "socket", "sock-unix", "termios", "fifo", "pty", "parent", "shell"},
	"SOCKET-CONNECT":        []string{"fd", "socket", "child", "retry"},
	"SOCKET-DATAGRAM":       []string{"fd", "socket", "range"},
	"SOCKET-LISTEN":         []string{"fd", "socket", "listen", "range", "child", "retry"},
	"SOCKET-RECV":           []string{"fd", "socket", "range"},
	"SOCKET-RECVFROM":       []string{"fd", "socket", "range", "child"},
	"SOCKET-SENDTO":         []string{"fd", "socket"},
	"SOCKETPAIR":            []string{"fd", "socket"},
	"SOCKS":                 []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS4":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS4A":               []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS5":                []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS5-BIND":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS5-CONNECT":        []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SOCKS5-LISTEN":         []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "socks", "child", "retry"},
	"SSL":                   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "openssl", "retry"},
	"SSL-L":                 []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "openssl", "retry"},
	"STALL":                 []string{"fd", "fifo"},
	"STDERR":                []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"STDIN":                 []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"STDIO":                 []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"STDOUT":                []string{"fd", "fifo", "chr", "blk", "reg", "socket", "termios", "sock-unix", "sock-ip4", "sock-ip6", "ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"SYSTEM":                []string{"fd", "fork", "exec", "socket", "sock-unix", "termios", "fifo", "pty", "parent"},
	"TCP":                   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "retry"},
	"TCP-CONNECT":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "child", "retry"},
	"TCP-L":                 []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"TCP-LISTEN":            []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"TCP4":                  []string{"fd", "socket", "sock-ip4", "ip-tcp", "child", "retry"},
	"TCP4-CONNECT":          []string{"fd", "socket", "sock-ip4", "ip-tcp", "child", "retry"},
	"TCP4-L":                []string{"fd", "socket", "sock-ip4", "ip-tcp", "listen", "child", "range", "retry"},
	"TCP4-LISTEN":           []string{"fd", "socket", "sock-ip4", "ip-tcp", "listen", "child", "range", "retry"},
	"TCP6":                  []string{"fd", "socket", "sock-ip6", "ip-tcp", "child", "retry"},
	"TCP6-CONNECT":          []string{"fd", "socket", "sock-ip6", "ip-tcp", "child", "retry"},
	"TCP6-L":                []string{"fd", "socket", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"TCP6-LISTEN":           []string{"fd", "socket", "sock-ip6", "ip-tcp", "listen", "child", "range", "retry"},
	"TEXT":                  []string{"fd", "fifo"},
	"TUN":                   []string{"fd", "chr", "open", "interface"},
	"UDP":                   []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp"},
	"UDP-CONNECT":           []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp"},
	"UDP-DATAGRAM":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "range"},
	"UDP-DGRAM":             []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "range"},
	"UDP-L":                 []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range"},
	"UDP-LISTEN":            []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "listen", "child", "range"},
	"UDP-RECV":              []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "range"},
	"UDP-RECVFROM":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "child", "range"},
	"UDP-SEND":              []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp"},
	"UDP-SENDTO":            []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp"},
	"UDP4":                  []string{"fd", "socket", "sock-ip4", "ip-udp"},
	"UDP4-CONNECT":          []string{"fd", "socket", "sock-ip4", "ip-udp"},
	"UDP4-DATAGRAM":         []string{"fd", "socket", "sock-ip4", "ip-udp", "range"},
	"UDP4-DGRAM":            []string{"fd", "socket", "sock-ip4", "ip-udp", "range"},
	"UDP4-L":                []string{"fd", "socket", "sock-ip4", "ip-udp", "listen", "child", "range"},
	"UDP4-LISTEN":           []string{"fd", "socket", "sock-ip4", "ip-udp", "listen", "child", "range"},
	"UDP4-RECV":             []string{"fd", "socket", "sock-ip4", "ip-udp", "range"},
	"UDP4-RECVFROM":         []string{"fd", "socket", "sock-ip4", "ip-udp", "child", "range"},
	"UDP4-SEND":             []string{"fd", "socket", "sock-ip4", "ip-udp"},
	"UDP4-SENDTO":           []string{"fd", "socket", "sock-ip4", "ip-udp"},
	"UDP6":                  []string{"fd", "socket", "sock-ip6", "ip-udp"},
	"UDP6-CONNECT":          []string{"fd", "socket", "sock-ip6", "ip-udp"},
	"UDP6-DATAGRAM":         []string{"fd", "socket", "sock-ip6", "ip-udp", "range"},
	"UDP6-DGRAM":            []string{"fd", "socket", "sock-ip6", "ip-udp", "range"},
	"UDP6-L":                []string{"fd", "socket", "sock-ip6", "ip-udp", "listen", "child", "range"},
	"UDP6-LISTEN":           []string{"fd", "socket", "sock-ip6", "ip-udp", "listen", "child", "range"},
	"UDP6-RECV":             []string{"fd", "socket", "sock-ip6", "ip-udp", "range"},
	"UDP6-RECVFROM":         []string{"fd", "socket", "sock-ip6", "ip-udp", "child", "range"},
	"UDP6-SEND":             []string{"fd", "socket", "sock-ip6", "ip-udp"},
	"UDP6-SENDTO":           []string{"fd", "socket", "sock-ip6", "ip-udp"},
	"UDPLITE":               []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE-CONNECT":       []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE-DATAGRAM":      []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE-DGRAM":         []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE-L":             []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE-LISTEN":        []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE-RECV":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE-RECVFROM":      []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite", "child", "range"},
	"UDPLITE-SEND":          []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE-SENDTO":        []string{"fd", "socket", "sock-ip4", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE4":              []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite"},
	"UDPLITE4-CONNECT":      []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite"},
	"UDPLITE4-DATAGRAM":     []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "range"},
	"UDPLITE4-DGRAM":        []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "range"},
	"UDPLITE4-L":            []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE4-LISTEN":       []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE4-RECV":         []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "range"},
	"UDPLITE4-RECVFROM":     []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite", "child", "range"},
	"UDPLITE4-SEND":         []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite"},
	"UDPLITE4-SENDTO":       []string{"fd", "socket", "sock-ip4", "ip-udp", "ip-udplite"},
	"UDPLITE6":              []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE6-CONNECT":      []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE6-DATAGRAM":     []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE6-DGRAM":        []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE6-L":            []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE6-LISTEN":       []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "listen", "child", "range"},
	"UDPLITE6-RECV":         []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "range"},
	"UDPLITE6-RECVFROM":     []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite", "child", "range"},
	"UDPLITE6-SEND":         []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite"},
	"UDPLITE6-SENDTO":       []string{"fd", "socket", "sock-ip6", "ip-udp", "ip-udplite"},
	"UNIX":                  []string{"fd", "named", "socket", "sock-unix", "retry"},
	"UNIX-CLIENT":           []string{"fd", "named", "socket", "sock-unix", "retry"},
	"UNIX-CONNECT":          []string{"fd", "named", "socket", "sock-unix", "retry"},
	"UNIX-L":                []string{"fd", "named", "socket", "sock-unix", "listen", "child", "retry"},
	"UNIX-LISTEN":           []string{"fd", "named", "socket", "sock-unix", "listen", "child", "retry"},
	"UNIX-RECV":             []string{"fd", "named", "socket", "sock-unix", "retry"},
	"UNIX-RECVFROM":         []string{"fd", "named", "socket", "sock-unix", "retry", "child"},
	"UNIX-SEND":             []string{"fd", "named", "socket", "sock-unix", "retry"},
	"UNIX-SENDTO":           []string{"fd", "named", "socket", "sock-unix", "retry"},
	"VSOCK":                 []string{"fd", "socket", "child", "retry"},
	"VSOCK-CONNECT":         []string{"fd", "socket", "child", "retry"},
	"VSOCK-L":               []string{"fd", "socket", "listen", "child", "retry"},
	"VSOCK-LISTEN":          []string{"fd", "socket", "listen", "child", "retry"},
}

// ClassicOptionGroups is the expanded GROUP_* set for each option keyword
// and nickname in classic socat 1.8.1.3. A defname wins over a later nickname.
var ClassicOptionGroups = map[string][]string{
	"aaonly":                           []string{"sock-ip4", "sock-ip6"},
	"abort-threshold":                  []string{"ip-tcp"},
	"accept-timeout":                   []string{"listen"},
	"acceptconn":                       []string{"socket"},
	"addrconfig":                       []string{"sock-ip4", "sock-ip6"},
	"ai-addrconfig":                    []string{"sock-ip4", "sock-ip6"},
	"ai-all":                           []string{"sock-ip4", "sock-ip6"},
	"ai-passive":                       []string{"sock-ip4", "sock-ip6"},
	"ai-v4mapped":                      []string{"sock-ip4", "sock-ip6"},
	"allmulti":                         []string{"interface"},
	"allow-table":                      []string{"range"},
	"append":                           []string{"open", "fd"},
	"async":                            []string{"open", "fd"},
	"attachfilter":                     []string{"socket"},
	"audit":                            []string{"socket"},
	"authhdr":                          []string{"sock-ip6"},
	"automedia":                        []string{"interface"},
	"b0":                               []string{"termios"},
	"b1000000":                         []string{"termios"},
	"b110":                             []string{"termios"},
	"b115200":                          []string{"termios"},
	"b1152000":                         []string{"termios"},
	"b1200":                            []string{"termios"},
	"b134":                             []string{"termios"},
	"b150":                             []string{"termios"},
	"b1500000":                         []string{"termios"},
	"b1800":                            []string{"termios"},
	"b19200":                           []string{"termios"},
	"b200":                             []string{"termios"},
	"b2000000":                         []string{"termios"},
	"b230400":                          []string{"termios"},
	"b2400":                            []string{"termios"},
	"b2500000":                         []string{"termios"},
	"b300":                             []string{"termios"},
	"b3000000":                         []string{"termios"},
	"b3500000":                         []string{"termios"},
	"b3600":                            []string{"termios"},
	"b38400":                           []string{"termios"},
	"b4000000":                         []string{"termios"},
	"b460800":                          []string{"termios"},
	"b4800":                            []string{"termios"},
	"b50":                              []string{"termios"},
	"b500000":                          []string{"termios"},
	"b57600":                           []string{"termios"},
	"b576000":                          []string{"termios"},
	"b600":                             []string{"termios"},
	"b7200":                            []string{"termios"},
	"b75":                              []string{"termios"},
	"b900":                             []string{"termios"},
	"b921600":                          []string{"termios"},
	"b9600":                            []string{"termios"},
	"backlog":                          []string{"listen"},
	"binary":                           []string{"open", "fd"},
	"bind":                             []string{"socket"},
	"bind-tempname":                    []string{"sock-unix"},
	"brkint":                           []string{"termios"},
	"broadcast":                        []string{"socket"},
	"bs0":                              []string{"termios"},
	"bs1":                              []string{"termios"},
	"bsdcompat":                        []string{"socket"},
	"bsdly":                            []string{"termios"},
	"bytes":                            []string{"appl"},
	"cafile":                           []string{"openssl"},
	"capath":                           []string{"openssl"},
	"ccid":                             []string{"ip-dccp"},
	"cd":                               nil,
	"cert":                             []string{"openssl"},
	"cfmakeraw":                        []string{"termios"},
	"chdir":                            nil,
	"child-shutup":                     []string{"child"},
	"children-shutup":                  []string{"child"},
	"chroot":                           []string{"process"},
	"chroot-early":                     []string{"process"},
	"ciphers":                          []string{"openssl"},
	"cksumrecv":                        []string{"socket"},
	"clocal":                           []string{"termios"},
	"cloexec":                          []string{"fd"},
	"close":                            []string{"fd"},
	"cn":                               []string{"openssl"},
	"compr":                            []string{"reg"},
	"compress":                         []string{"openssl"},
	"conn-abort-threshold":             []string{"ip-tcp"},
	"connect-timeout":                  []string{"socket"},
	"cool-write":                       []string{"fd"},
	"coolwrite":                        []string{"fd"},
	"cork":                             []string{"ip-tcp"},
	"cr":                               []string{"appl"},
	"cr0":                              []string{"termios"},
	"cr1":                              []string{"termios"},
	"cr2":                              []string{"termios"},
	"cr3":                              []string{"termios"},
	"crdly":                            []string{"termios"},
	"cread":                            []string{"termios"},
	"creat":                            []string{"open"},
	"crnl":                             []string{"appl"},
	"crtscts":                          []string{"termios"},
	"cs5":                              []string{"termios"},
	"cs6":                              []string{"termios"},
	"cs7":                              []string{"termios"},
	"cs8":                              []string{"termios"},
	"csize":                            []string{"termios"},
	"cstopb":                           []string{"termios"},
	"ctty":                             []string{"termios"},
	"dash":                             []string{"exec"},
	"dccp-set-ccid":                    []string{"ip-dccp"},
	"debug":                            []string{"socket"},
	"defer":                            []string{"open"},
	"defer-accept":                     []string{"ip-tcp"},
	"defnames":                         []string{"sock-ip4", "sock-ip6"},
	"delay":                            []string{"open"},
	"deny-table":                       []string{"range"},
	"detachfilter":                     []string{"socket"},
	"dgramerrind":                      []string{"socket"},
	"dh":                               []string{"openssl"},
	"direct":                           []string{"open"},
	"directory":                        []string{"open"},
	"dirsync":                          []string{"reg"},
	"discard":                          []string{"termios"},
	"dns":                              []string{"sock-ip4", "sock-ip6"},
	"dnsrch":                           []string{"sock-ip4", "sock-ip6"},
	"dontlinger":                       []string{"socket"},
	"dontroute":                        []string{"socket"},
	"dstopts":                          []string{"sock-ip6"},
	"dsusp":                            []string{"termios"},
	"dsync":                            []string{"open"},
	"echo":                             []string{"termios"},
	"echoctl":                          []string{"termios"},
	"echoe":                            []string{"termios"},
	"echok":                            []string{"termios"},
	"echoke":                           []string{"termios"},
	"echonl":                           []string{"termios"},
	"echoprt":                          []string{"termios"},
	"egd":                              []string{"openssl"},
	"end-close":                        []string{"fd"},
	"eof":                              []string{"termios"},
	"eol":                              []string{"termios"},
	"eol2":                             []string{"termios"},
	"erase":                            []string{"termios"},
	"error":                            []string{"socket"},
	"escape":                           []string{"appl"},
	"excl":                             []string{"open"},
	"f-setlk-rd":                       []string{"fd"},
	"f-setlk-wr":                       []string{"fd"},
	"f-setlkw-rd":                      []string{"fd"},
	"f-setlkw-wr":                      []string{"fd"},
	"f-setpipe-sz":                     []string{"fifo"},
	"fdin":                             []string{"fork"},
	"fdout":                            []string{"fork"},
	"ff0":                              []string{"termios"},
	"ff1":                              []string{"termios"},
	"ffdly":                            []string{"termios"},
	"fiosetown":                        []string{"socket"},
	"fips":                             []string{"openssl"},
	"flock":                            []string{"fd"},
	"flock-ex":                         []string{"fd"},
	"flock-ex-nb":                      []string{"fd"},
	"flock-nb":                         []string{"fd"},
	"flock-sh":                         []string{"fd"},
	"flock-sh-nb":                      []string{"fd"},
	"flowinfo":                         []string{"sock-ip6"},
	"flusho":                           []string{"termios"},
	"forever":                          []string{"retry"},
	"fork":                             []string{"child"},
	"freebind":                         []string{"sock-ip4", "sock-ip6"},
	"fs-append":                        []string{"reg"},
	"fs-compr":                         []string{"reg"},
	"fs-dirsync":                       []string{"reg"},
	"fs-immutable":                     []string{"reg"},
	"fs-journal-data":                  []string{"reg"},
	"fs-noatime":                       []string{"reg"},
	"fs-nodump":                        []string{"reg"},
	"fs-notail":                        []string{"reg"},
	"fs-secrm":                         []string{"reg"},
	"fs-sync":                          []string{"reg"},
	"fs-topdir":                        []string{"reg"},
	"fs-unrm":                          []string{"reg"},
	"ftruncate32":                      []string{"reg"},
	"ftruncate64":                      []string{"reg"},
	"gid":                              []string{"fd", "named"},
	"gid-l":                            nil,
	"group":                            []string{"fd", "named"},
	"group-early":                      nil,
	"group-late":                       nil,
	"hdrincl":                          []string{"sock-ip4", "sock-ip6"},
	"history":                          []string{"readline"},
	"history-file":                     []string{"readline"},
	"hoplimit":                         []string{"sock-ip6"},
	"hopopts":                          []string{"sock-ip6"},
	"http-version":                     []string{"http"},
	"hupcl":                            []string{"termios"},
	"icanon":                           []string{"termios"},
	"icrnl":                            []string{"termios"},
	"iexten":                           []string{"termios"},
	"if":                               []string{"socket"},
	"if-mtu":                           []string{"interface"},
	"iff-allmulti":                     []string{"interface"},
	"iff-automedia":                    []string{"interface"},
	"iff-broadcast":                    []string{"interface"},
	"iff-debug":                        []string{"interface"},
	"iff-loopback":                     []string{"interface"},
	"iff-master":                       []string{"interface"},
	"iff-multicast":                    []string{"interface"},
	"iff-no-pi":                        []string{"interface"},
	"iff-noarp":                        []string{"interface"},
	"iff-notrailers":                   []string{"interface"},
	"iff-pointopoint":                  []string{"interface"},
	"iff-portsel":                      []string{"interface"},
	"iff-promisc":                      []string{"interface"},
	"iff-running":                      []string{"interface"},
	"iff-slave":                        []string{"interface"},
	"iff-up":                           []string{"interface"},
	"ignbrk":                           []string{"termios"},
	"igncr":                            []string{"termios"},
	"ignorecr":                         []string{"http"},
	"ignoreeof":                        []string{"appl"},
	"ignpar":                           []string{"termios"},
	"igntc":                            []string{"sock-ip4", "sock-ip6"},
	"imaxbel":                          []string{"termios"},
	"immutable":                        []string{"reg"},
	"info":                             []string{"ip-tcp"},
	"inlcr":                            []string{"termios"},
	"inpck":                            []string{"termios"},
	"interface-mtu":                    []string{"interface"},
	"interval":                         []string{"retry"},
	"intr":                             []string{"termios"},
	"ioctl":                            []string{"fd"},
	"ioctl-bin":                        []string{"fd"},
	"ioctl-int":                        []string{"fd"},
	"ioctl-intp":                       []string{"fd"},
	"ioctl-string":                     []string{"fd"},
	"ioctl-void":                       []string{"fd"},
	"ip-add-membership":                []string{"sock-ip4", "sock-ip6"},
	"ip-add-source-membership":         []string{"sock-ip4", "sock-ip6"},
	"ip-freebind":                      []string{"sock-ip4", "sock-ip6"},
	"ip-hdrincl":                       []string{"sock-ip4", "sock-ip6"},
	"ip-mtu":                           []string{"sock-ip4", "sock-ip6"},
	"ip-mtu-discover":                  []string{"sock-ip4", "sock-ip6"},
	"ip-multicast-if":                  []string{"sock-ip4", "sock-ip6"},
	"ip-multicast-loop":                []string{"sock-ip4", "sock-ip6"},
	"ip-multicast-ttl":                 []string{"sock-ip4", "sock-ip6"},
	"ip-options":                       []string{"sock-ip4", "sock-ip6"},
	"ip-pktinfo":                       []string{"sock-ip4", "sock-ip6"},
	"ip-pktoptions":                    []string{"sock-ip4", "sock-ip6"},
	"ip-recvdstaddr":                   []string{"sock-ip4", "sock-ip6"},
	"ip-recverr":                       []string{"sock-ip4", "sock-ip6"},
	"ip-recvif":                        []string{"sock-ip4", "sock-ip6"},
	"ip-recvopts":                      []string{"sock-ip4", "sock-ip6"},
	"ip-recvtos":                       []string{"sock-ip4", "sock-ip6"},
	"ip-recvttl":                       []string{"sock-ip4", "sock-ip6"},
	"ip-retopts":                       []string{"sock-ip4", "sock-ip6"},
	"ip-router-alert":                  []string{"sock-ip4", "sock-ip6"},
	"ip-tos":                           []string{"sock-ip4", "sock-ip6"},
	"ip-transparent":                   []string{"sock-ip4", "sock-ip6"},
	"ip-ttl":                           []string{"sock-ip4", "sock-ip6"},
	"ipoptions":                        []string{"sock-ip4", "sock-ip6"},
	"ipv6-authhdr":                     []string{"sock-ip6"},
	"ipv6-dstopts":                     []string{"sock-ip6"},
	"ipv6-flowinfo":                    []string{"sock-ip6"},
	"ipv6-hoplimit":                    []string{"sock-ip6"},
	"ipv6-hopopts":                     []string{"sock-ip6"},
	"ipv6-join-group":                  []string{"sock-ip6"},
	"ipv6-join-source-group":           []string{"sock-ip6"},
	"ipv6-mtu-discover":                []string{"sock-ip4", "sock-ip6"},
	"ipv6-multicast-loop":              []string{"sock-ip6"},
	"ipv6-pktinfo":                     []string{"sock-ip6"},
	"ipv6-recvdstopts":                 []string{"sock-ip6"},
	"ipv6-recverr":                     []string{"sock-ip6"},
	"ipv6-recvhoplimit":                []string{"sock-ip6"},
	"ipv6-recvhopopts":                 []string{"sock-ip6"},
	"ipv6-recvpathmtu":                 []string{"sock-ip6"},
	"ipv6-recvpktinfo":                 []string{"sock-ip6"},
	"ipv6-recvrthdr":                   []string{"sock-ip6"},
	"ipv6-recvtclass":                  []string{"sock-ip6"},
	"ipv6-rthdr":                       []string{"sock-ip6"},
	"ipv6-tclass":                      []string{"sock-ip6"},
	"ipv6-unicast-hops":                []string{"sock-ip6"},
	"ipv6-v6only":                      []string{"sock-ip6"},
	"ipv6only":                         []string{"sock-ip6"},
	"isig":                             []string{"termios"},
	"ispeed":                           []string{"termios"},
	"istrip":                           []string{"termios"},
	"iuclc":                            []string{"termios"},
	"ixany":                            []string{"termios"},
	"ixoff":                            []string{"termios"},
	"ixon":                             []string{"termios"},
	"join-group":                       []string{"sock-ip6"},
	"join-source-group":                []string{"sock-ip6"},
	"journal-data":                     []string{"reg"},
	"keepalive":                        []string{"socket"},
	"keepcnt":                          []string{"ip-tcp"},
	"keepidle":                         []string{"ip-tcp"},
	"keepinit":                         []string{"ip-tcp"},
	"keepintvl":                        []string{"ip-tcp"},
	"kernaccept":                       []string{"socket"},
	"key":                              []string{"openssl"},
	"kill":                             []string{"termios"},
	"largefile":                        []string{"open"},
	"linger":                           []string{"socket"},
	"linger2":                          []string{"ip-tcp"},
	"link":                             []string{"pty"},
	"listen-timeout":                   []string{"listen"},
	"lnext":                            []string{"termios"},
	"lockfile":                         []string{"appl"},
	"login":                            []string{"exec"},
	"loopback":                         []string{"interface"},
	"lowport":                          []string{"ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"lseek32-cur":                      []string{"reg", "blk"},
	"lseek32-end":                      []string{"reg", "blk"},
	"lseek32-set":                      []string{"reg", "blk"},
	"lseek64-cur":                      []string{"reg", "blk"},
	"lseek64-end":                      []string{"reg", "blk"},
	"lseek64-set":                      []string{"reg", "blk"},
	"master":                           []string{"interface"},
	"max-children":                     []string{"child"},
	"max-version":                      []string{"openssl"},
	"maxfraglen":                       []string{"openssl"},
	"maxsendfrag":                      []string{"openssl"},
	"mcloop":                           []string{"sock-ip4", "sock-ip6"},
	"mcloop6":                          []string{"sock-ip6"},
	"md5sig":                           []string{"ip-tcp"},
	"membership":                       []string{"sock-ip4", "sock-ip6"},
	"method":                           []string{"openssl"},
	"min":                              []string{"termios"},
	"min-version":                      []string{"openssl"},
	"mode":                             []string{"fd", "named"},
	"mq-flush":                         []string{"posixmq"},
	"mq-maxmsg":                        []string{"posixmq"},
	"mq-msgsize":                       []string{"posixmq"},
	"mq-prio":                          []string{"posixmq"},
	"mss":                              []string{"ip-tcp"},
	"mss-late":                         []string{"ip-tcp"},
	"mtu":                              []string{"sock-ip4", "sock-ip6"},
	"mtudiscover":                      []string{"sock-ip4", "sock-ip6"},
	"mtudiscover6":                     []string{"sock-ip4", "sock-ip6"},
	"multicast-if":                     []string{"sock-ip4", "sock-ip6"},
	"multicastttl":                     []string{"sock-ip4", "sock-ip6"},
	"netns":                            []string{"process"},
	"nl0":                              []string{"termios"},
	"nl1":                              []string{"termios"},
	"nldly":                            []string{"termios"},
	"no-pi":                            []string{"interface"},
	"noarp":                            []string{"interface"},
	"noatime":                          []string{"reg"},
	"nocheck":                          []string{"socket"},
	"noctty":                           []string{"open"},
	"nodelay":                          []string{"ip-tcp"},
	"nodump":                           []string{"reg"},
	"noecho":                           []string{"readline"},
	"noflsh":                           []string{"termios"},
	"nofollow":                         []string{"open"},
	"nofork":                           []string{"fork"},
	"noinherit":                        []string{"open", "fd"},
	"nonblock":                         []string{"open", "fd"},
	"noopt":                            []string{"ip-tcp"},
	"noprompt":                         []string{"readline"},
	"nopush":                           []string{"ip-tcp"},
	"noreuseaddr":                      []string{"socket"},
	"nosni":                            []string{"openssl"},
	"notail":                           []string{"reg"},
	"notrailers":                       []string{"interface"},
	"nshare":                           []string{"open"},
	"null-eof":                         []string{"socket"},
	"o-binary":                         []string{"open", "fd"},
	"o-creat":                          []string{"open"},
	"o-defer":                          []string{"open"},
	"o-delay":                          []string{"open"},
	"o-direct":                         []string{"open"},
	"o-directory":                      []string{"open"},
	"o-dsync":                          []string{"open"},
	"o-excl":                           []string{"open"},
	"o-largefile":                      []string{"open"},
	"o-ndelay":                         []string{"open", "fd"},
	"o-noatime":                        []string{"open", "fd"},
	"o-noctty":                         []string{"open"},
	"o-nofollow":                       []string{"open"},
	"o-noinherit":                      []string{"open", "fd"},
	"o-nonblock":                       []string{"open", "fd"},
	"o-nshare":                         []string{"open"},
	"o-priv":                           []string{"open"},
	"o-rdonly":                         []string{"open"},
	"o-rdwr":                           []string{"open"},
	"o-rshare":                         []string{"open"},
	"o-rsync":                          []string{"open"},
	"o-sync":                           []string{"open"},
	"o-text":                           []string{"open", "fd"},
	"o-trunc":                          []string{"open"},
	"o-wronly":                         []string{"open"},
	"ocrnl":                            []string{"termios"},
	"ofdel":                            []string{"termios"},
	"ofill":                            []string{"termios"},
	"olcuc":                            []string{"termios"},
	"onlcr":                            []string{"termios"},
	"onlret":                           []string{"termios"},
	"onocr":                            []string{"termios"},
	"oobinline":                        []string{"socket"},
	"openpty":                          []string{"pty"},
	"openssl-cafile":                   []string{"openssl"},
	"openssl-capath":                   []string{"openssl"},
	"openssl-certificate":              []string{"openssl"},
	"openssl-cipherlist":               []string{"openssl"},
	"openssl-commonname":               []string{"openssl"},
	"openssl-compress":                 []string{"openssl"},
	"openssl-dhparam":                  []string{"openssl"},
	"openssl-egd":                      []string{"openssl"},
	"openssl-fips":                     []string{"openssl"},
	"openssl-key":                      []string{"openssl"},
	"openssl-max-proto-version":        []string{"openssl"},
	"openssl-maxfraglen":               []string{"openssl"},
	"openssl-maxsendfrag":              []string{"openssl"},
	"openssl-method":                   []string{"openssl"},
	"openssl-min-proto-version":        []string{"openssl"},
	"openssl-no-sni":                   []string{"openssl"},
	"openssl-pseudo":                   []string{"openssl"},
	"openssl-snihost":                  []string{"openssl"},
	"openssl-verify":                   []string{"openssl"},
	"opost":                            []string{"termios"},
	"ospeed":                           []string{"termios"},
	"parenb":                           []string{"termios"},
	"parmrk":                           []string{"termios"},
	"parodd":                           []string{"termios"},
	"passcred":                         []string{"socket"},
	"passive":                          []string{"sock-ip4", "sock-ip6"},
	"path":                             []string{"exec"},
	"paws":                             []string{"ip-tcp"},
	"peercred":                         []string{"socket"},
	"pendin":                           []string{"termios"},
	"perm":                             []string{"fd", "named"},
	"perm-early":                       []string{"named"},
	"perm-late":                        []string{"fd"},
	"pf":                               []string{"socket"},
	"pgid":                             []string{"fork"},
	"pipes":                            []string{"fork"},
	"pipesz":                           []string{"fifo"},
	"pktinfo":                          []string{"sock-ip6"},
	"pktopts":                          []string{"sock-ip4", "sock-ip6"},
	"pointopoint":                      []string{"interface"},
	"pop-all":                          []string{"fd"},
	"portsel":                          []string{"interface"},
	"posixmq-flush":                    []string{"posixmq"},
	"posixmq-maxmsg":                   []string{"posixmq"},
	"posixmq-msgsize":                  []string{"posixmq"},
	"posixmq-priority":                 []string{"posixmq"},
	"primary":                          []string{"sock-ip4", "sock-ip6"},
	"priority":                         []string{"socket"},
	"priv":                             []string{"open"},
	"promisc":                          []string{"interface"},
	"prompt":                           []string{"readline"},
	"protocol":                         []string{"socket"},
	"protocol-family":                  []string{"socket"},
	"proxy-authorization":              []string{"http"},
	"proxy-authorization-file":         []string{"http"},
	"proxy-resolve":                    []string{"http"},
	"proxyauth":                        []string{"http"},
	"proxyauthfile":                    []string{"http"},
	"proxyport":                        []string{"http"},
	"pseudo":                           []string{"openssl"},
	"ptmx":                             []string{"pty"},
	"pty":                              []string{"fork"},
	"pty-interval":                     []string{"pty"},
	"pty-wait-slave":                   []string{"pty"},
	"push":                             []string{"fd"},
	"quickack":                         []string{"ip-tcp"},
	"quit":                             []string{"termios"},
	"range":                            []string{"range"},
	"raw":                              []string{"termios"},
	"rawer":                            []string{"termios"},
	"rcvbuf":                           []string{"socket"},
	"rcvbuf-late":                      []string{"socket"},
	"rcvlowat":                         []string{"socket"},
	"rcvtimeo":                         []string{"socket"},
	"rdonly":                           []string{"open"},
	"rdwr":                             []string{"open"},
	"readbytes":                        []string{"appl"},
	"recurse":                          []string{"sock-ip4", "sock-ip6"},
	"recvdstaddr":                      []string{"sock-ip4", "sock-ip6"},
	"recvdstaddrif":                    []string{"sock-ip4", "sock-ip6"},
	"recvdstopts":                      []string{"sock-ip6"},
	"recverr":                          []string{"sock-ip6"},
	"recvhoplimit":                     []string{"sock-ip6"},
	"recvhopopts":                      []string{"sock-ip6"},
	"recvopts":                         []string{"sock-ip4", "sock-ip6"},
	"recvpathmtu":                      []string{"sock-ip6"},
	"recvpktinfo":                      []string{"sock-ip6"},
	"recvrthdr":                        []string{"sock-ip6"},
	"recvtclass":                       []string{"sock-ip6"},
	"recvtos":                          []string{"sock-ip4", "sock-ip6"},
	"recvttl":                          []string{"sock-ip4", "sock-ip6"},
	"reprint":                          []string{"termios"},
	"res-aaonly":                       []string{"sock-ip4", "sock-ip6"},
	"res-debug":                        []string{"sock-ip4", "sock-ip6"},
	"res-defnames":                     []string{"sock-ip4", "sock-ip6"},
	"res-dnsrch":                       []string{"sock-ip4", "sock-ip6"},
	"res-igntc":                        []string{"sock-ip4", "sock-ip6"},
	"res-nsaddr":                       []string{"sock-ip4", "sock-ip6"},
	"res-primary":                      []string{"sock-ip4", "sock-ip6"},
	"res-recurse":                      []string{"sock-ip4", "sock-ip6"},
	"res-retrans":                      []string{"sock-ip4", "sock-ip6"},
	"res-retry":                        []string{"sock-ip4", "sock-ip6"},
	"res-stayopen":                     []string{"sock-ip4", "sock-ip6"},
	"res-usevc":                        []string{"sock-ip4", "sock-ip6"},
	"resolve":                          []string{"http"},
	"retopts":                          []string{"sock-ip4", "sock-ip6"},
	"retrans":                          []string{"sock-ip4", "sock-ip6"},
	"retrieve-vlan":                    []string{"interface"},
	"retry":                            []string{"retry"},
	"reuseaddr":                        []string{"socket"},
	"reuseport":                        []string{"socket"},
	"rfc1323":                          []string{"ip-tcp"},
	"route":                            []string{"interface"},
	"routeralert":                      []string{"sock-ip4", "sock-ip6"},
	"rshare":                           []string{"open"},
	"rsync":                            []string{"open"},
	"rthdr":                            []string{"sock-ip6"},
	"running":                          []string{"interface"},
	"sack-disable":                     []string{"ip-tcp"},
	"sackena":                          []string{"ip-tcp"},
	"sane":                             []string{"termios"},
	"sctp-maxseg":                      []string{"ip-sctp"},
	"sctp-maxseg-late":                 []string{"ip-sctp"},
	"sctp-nodelay":                     []string{"ip-sctp"},
	"secrm":                            []string{"reg"},
	"securityauthentication":           []string{"socket"},
	"securityencryptionnetwork":        []string{"socket"},
	"securityencryptiontransport":      []string{"socket"},
	"seek":                             []string{"reg", "blk"},
	"seek-cur":                         []string{"reg", "blk"},
	"seek-end":                         []string{"reg", "blk"},
	"setflags":                         []string{"termios"},
	"setgid":                           []string{"process"},
	"setgid-early":                     []string{"process"},
	"setlk":                            []string{"fd"},
	"setlk-rd":                         []string{"fd"},
	"setlkw":                           []string{"fd"},
	"setlkw-rd":                        []string{"fd"},
	"setpgid":                          []string{"fork"},
	"setsid":                           []string{"process"},
	"setsockopt":                       []string{"socket"},
	"setsockopt-bin":                   []string{"socket"},
	"setsockopt-connected":             []string{"socket"},
	"setsockopt-int":                   []string{"socket"},
	"setsockopt-listen":                []string{"socket"},
	"setsockopt-socket":                []string{"socket"},
	"setsockopt-string":                []string{"socket"},
	"setuid":                           []string{"process"},
	"setuid-early":                     []string{"process"},
	"shell":                            []string{"shell"},
	"shut-close":                       []string{"fd"},
	"shut-down":                        []string{"fd"},
	"shut-none":                        []string{"fd"},
	"shut-null":                        []string{"fd"},
	"sid":                              []string{"process"},
	"sighup":                           []string{"parent"},
	"sigint":                           []string{"parent"},
	"signature-enable":                 []string{"ip-tcp"},
	"sigquit":                          []string{"parent"},
	"siocspgrp":                        []string{"socket"},
	"sitout-eio":                       []string{"pty"},
	"slave":                            []string{"interface"},
	"sndbuf":                           []string{"socket"},
	"sndbuf-late":                      []string{"socket"},
	"sndlowat":                         []string{"socket"},
	"sndtimeo":                         []string{"socket"},
	"snihost":                          []string{"openssl"},
	"so-acceptconn":                    []string{"socket"},
	"so-attach-filter":                 []string{"socket"},
	"so-audit":                         []string{"socket"},
	"so-bindtodevice":                  []string{"socket"},
	"so-broadcast":                     []string{"socket"},
	"so-bsdcompat":                     []string{"socket"},
	"so-cksumrecv":                     []string{"socket"},
	"so-debug":                         []string{"socket"},
	"so-detach-filter":                 []string{"socket"},
	"so-dgram-errind":                  []string{"socket"},
	"so-dontlinger":                    []string{"socket"},
	"so-dontroute":                     []string{"socket"},
	"so-error":                         []string{"socket"},
	"so-keepalive":                     []string{"socket"},
	"so-kernaccept":                    []string{"socket"},
	"so-linger":                        []string{"socket"},
	"so-no-check":                      []string{"socket"},
	"so-noreuseaddr":                   []string{"socket"},
	"so-oobinline":                     []string{"socket"},
	"so-passcred":                      []string{"socket"},
	"so-peercred":                      []string{"socket"},
	"so-priority":                      []string{"socket"},
	"so-protocol":                      []string{"socket"},
	"so-rcvbuf":                        []string{"socket"},
	"so-rcvbuf-late":                   []string{"socket"},
	"so-rcvlowat":                      []string{"socket"},
	"so-rcvtimeo":                      []string{"socket"},
	"so-reuseaddr":                     []string{"socket"},
	"so-reuseport":                     []string{"socket"},
	"so-security-authentication":       []string{"socket"},
	"so-security-encryption-network":   []string{"socket"},
	"so-security-encryption-transport": []string{"socket"},
	"so-sndbuf":                        []string{"socket"},
	"so-sndbuf-late":                   []string{"socket"},
	"so-sndlowat":                      []string{"socket"},
	"so-sndtimeo":                      []string{"socket"},
	"so-timestamp":                     []string{"socket"},
	"so-type":                          []string{"socket"},
	"so-use-ifbufs":                    []string{"socket"},
	"so-useloopback":                   []string{"socket"},
	"sockopt":                          []string{"socket"},
	"sockopt-bin":                      []string{"socket"},
	"sockopt-conn":                     []string{"socket"},
	"sockopt-int":                      []string{"socket"},
	"sockopt-listen":                   []string{"socket"},
	"sockopt-sock":                     []string{"socket"},
	"sockopt-string":                   []string{"socket"},
	"sockspass":                        []string{"socks"},
	"socksport":                        []string{"socks"},
	"socksuser":                        []string{"socks"},
	"source-membership":                []string{"sock-ip4", "sock-ip6"},
	"sourceport":                       []string{"ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"sp":                               []string{"ip-udp", "ip-tcp", "ip-sctp", "ip-dccp", "ip-udplite"},
	"start":                            []string{"termios"},
	"stayopen":                         []string{"sock-ip4", "sock-ip6"},
	"stderr":                           []string{"fork"},
	"stdurg":                           []string{"ip-tcp"},
	"stop":                             []string{"termios"},
	"streams-i-pop-all":                []string{"fd"},
	"streams-i-push":                   []string{"fd"},
	"su":                               []string{"process"},
	"su-d":                             []string{"process"},
	"su-e":                             []string{"process"},
	"substuser":                        []string{"process"},
	"substuser-delayed":                []string{"process"},
	"substuser-early":                  []string{"process"},
	"susp":                             []string{"termios"},
	"swtc":                             []string{"termios"},
	"symbolic-link":                    []string{"pty"},
	"sync":                             []string{"reg"},
	"syncnt":                           []string{"ip-tcp"},
	"tab0":                             []string{"termios"},
	"tab1":                             []string{"termios"},
	"tab2":                             []string{"termios"},
	"tab3":                             []string{"termios"},
	"tabdly":                           []string{"termios"},
	"tclass":                           []string{"sock-ip6"},
	"tcp-abort-threshold":              []string{"ip-tcp"},
	"tcp-conn-abort-threshold":         []string{"ip-tcp"},
	"tcp-cork":                         []string{"ip-tcp"},
	"tcp-defer-accept":                 []string{"ip-tcp"},
	"tcp-info":                         []string{"ip-tcp"},
	"tcp-keepcnt":                      []string{"ip-tcp"},
	"tcp-keepidle":                     []string{"ip-tcp"},
	"tcp-keepinit":                     []string{"ip-tcp"},
	"tcp-keepintvl":                    []string{"ip-tcp"},
	"tcp-linger2":                      []string{"ip-tcp"},
	"tcp-maxseg":                       []string{"ip-tcp"},
	"tcp-maxseg-late":                  []string{"ip-tcp"},
	"tcp-md5sig":                       []string{"ip-tcp"},
	"tcp-nodelay":                      []string{"ip-tcp"},
	"tcp-noopt":                        []string{"ip-tcp"},
	"tcp-nopush":                       []string{"ip-tcp"},
	"tcp-paws":                         []string{"ip-tcp"},
	"tcp-quickack":                     []string{"ip-tcp"},
	"tcp-rfc1323":                      []string{"ip-tcp"},
	"tcp-sack-disable":                 []string{"ip-tcp"},
	"tcp-sackena":                      []string{"ip-tcp"},
	"tcp-signature-enable":             []string{"ip-tcp"},
	"tcp-stdurg":                       []string{"ip-tcp"},
	"tcp-syncnt":                       []string{"ip-tcp"},
	"tcp-tsoptena":                     []string{"ip-tcp"},
	"tcp-window-clamp":                 []string{"ip-tcp"},
	"tcpwrap":                          []string{"range"},
	"tcpwrap-dir":                      []string{"range"},
	"tcpwrap-etc":                      []string{"range"},
	"tcpwrap-hosts-allow-table":        []string{"range"},
	"tcpwrap-hosts-deny-table":         []string{"range"},
	"tcpwrappers":                      []string{"range"},
	"termios-cfmakeraw":                []string{"termios"},
	"termios-rawer":                    []string{"termios"},
	"termios-setflags":                 []string{"termios"},
	"text":                             []string{"open", "fd"},
	"tightsocklen":                     []string{"sock-unix"},
	"time":                             []string{"termios"},
	"timestamp":                        []string{"socket"},
	"tiocsctty":                        []string{"termios"},
	"tiocswinsz":                       []string{"termios"},
	"topdir":                           []string{"reg"},
	"tos":                              []string{"sock-ip4", "sock-ip6"},
	"tostop":                           []string{"termios"},
	"transparent":                      []string{"sock-ip4", "sock-ip6"},
	"trunc":                            []string{"open"},
	"truncate":                         []string{"reg"},
	"tsoptena":                         []string{"ip-tcp"},
	"ttl":                              []string{"sock-ip4", "sock-ip6"},
	"tun-device":                       []string{"interface"},
	"tun-name":                         []string{"interface"},
	"tun-type":                         []string{"interface"},
	"type":                             []string{"socket"},
	"udplite-recv-cscov":               []string{"ip-udplite"},
	"udplite-send-cscov":               []string{"ip-udplite"},
	"uid":                              []string{"fd", "named"},
	"uid-l":                            []string{"fd"},
	"umask":                            nil,
	"unicast-hops":                     []string{"sock-ip6"},
	"unix-bind-tempname":               []string{"sock-unix"},
	"unix-tightsocklen":                []string{"sock-unix"},
	"unlink":                           []string{"named"},
	"unlink-close":                     []string{"named"},
	"unlink-early":                     []string{"named"},
	"unlink-late":                      []string{"named"},
	"unrm":                             []string{"reg"},
	"up":                               []string{"interface"},
	"useifbufs":                        []string{"socket"},
	"useloopback":                      []string{"socket"},
	"user":                             []string{"fd", "named"},
	"user-early":                       []string{"named"},
	"user-late":                        []string{"fd"},
	"usevc":                            []string{"sock-ip4", "sock-ip6"},
	"v4mapped":                         []string{"sock-ip4", "sock-ip6"},
	"vdiscard":                         []string{"termios"},
	"vdsusp":                           []string{"termios"},
	"veof":                             []string{"termios"},
	"veol":                             []string{"termios"},
	"veol2":                            []string{"termios"},
	"verase":                           []string{"termios"},
	"verify":                           []string{"openssl"},
	"vintr":                            []string{"termios"},
	"vkill":                            []string{"termios"},
	"vlnext":                           []string{"termios"},
	"vmin":                             []string{"termios"},
	"vquit":                            []string{"termios"},
	"vreprint":                         []string{"termios"},
	"vstart":                           []string{"termios"},
	"vstop":                            []string{"termios"},
	"vsusp":                            []string{"termios"},
	"vswtc":                            []string{"termios"},
	"vt0":                              []string{"termios"},
	"vt1":                              []string{"termios"},
	"vtdly":                            []string{"termios"},
	"vtime":                            []string{"termios"},
	"vwerase":                          []string{"termios"},
	"wait-slave":                       []string{"pty"},
	"waitlock":                         []string{"appl"},
	"werase":                           []string{"termios"},
	"window-clamp":                     []string{"ip-tcp"},
	"winsz":                            []string{"termios"},
	"wronly":                           []string{"open"},
	"xcase":                            []string{"termios"},
	"xtabs":                            []string{"termios"},
}

// ClassicAddressAliases maps addressnames[] aliases to the canonical addrdesc name.
var ClassicAddressAliases = map[string]string{
	"-":                    "STDIO",
	"ABSTRACT":             "ABSTRACT-CLIENT",
	"ACCEPT":               "ACCEPT-FD",
	"CREAT":                "CREATE",
	"DATAGRAM":             "SOCKET-DATAGRAM",
	"DCCP":                 "DCCP-CONNECT",
	"DCCP-L":               "DCCP-LISTEN",
	"DCCP4":                "DCCP4-CONNECT",
	"DCCP4-L":              "DCCP4-LISTEN",
	"DCCP6":                "DCCP6-CONNECT",
	"DCCP6-L":              "DCCP6-LISTEN",
	"DGRAM":                "SOCKET-DATAGRAM",
	"DTLS":                 "OPENSSL-DTLS-CLIENT",
	"DTLS-C":               "OPENSSL-DTLS-CLIENT",
	"DTLS-CLIENT":          "OPENSSL-DTLS-CLIENT",
	"DTLS-CONNECT":         "OPENSSL-DTLS-CLIENT",
	"DTLS-L":               "OPENSSL-DTLS-SERVER",
	"DTLS-LISTEN":          "OPENSSL-DTLS-SERVER",
	"DTLS-SERVER":          "OPENSSL-DTLS-SERVER",
	"ECHO":                 "PIPE",
	"FIFO":                 "PIPE",
	"FILE":                 "OPEN",
	"IF":                   "INTERFACE",
	"INET":                 "TCP-CONNECT",
	"INET-L":               "TCP-LISTEN",
	"INET-LISTEN":          "TCP-LISTEN",
	"INET4":                "TCP4-CONNECT",
	"INET4-L":              "TCP4-LISTEN",
	"INET4-LISTEN":         "TCP4-LISTEN",
	"INET6":                "TCP6-CONNECT",
	"INET6-L":              "TCP6-LISTEN",
	"INET6-LISTEN":         "TCP6-LISTEN",
	"IP":                   "IP-SENDTO",
	"IP-DGRAM":             "IP-DATAGRAM",
	"IP-SEND":              "IP-SENDTO",
	"IP4":                  "IP4-SENDTO",
	"IP4-DGRAM":            "IP4-DATAGRAM",
	"IP4-SEND":             "IP4-SENDTO",
	"IP6":                  "IP6-SENDTO",
	"IP6-DGRAM":            "IP6-DATAGRAM",
	"IP6-SEND":             "IP6-SENDTO",
	"LOCAL":                "UNIX-CONNECT",
	"OPENSSL-CONNECT":      "OPENSSL",
	"OPENSSL-DTLS-CONNECT": "OPENSSL-DTLS-CLIENT",
	"OPENSSL-DTLS-LISTEN":  "OPENSSL-DTLS-SERVER",
	"POSIXMQ":              "POSIXMQ-BIDIRECTIONAL",
	"POSIXMQ-RECV":         "POSIXMQ-RECEIVE",
	"PROXY-CONNECT":        "PROXY",
	"SCTP":                 "SCTP-CONNECT",
	"SCTP-L":               "SCTP-LISTEN",
	"SCTP4":                "SCTP4-CONNECT",
	"SCTP4-L":              "SCTP4-LISTEN",
	"SCTP6":                "SCTP6-CONNECT",
	"SCTP6-L":              "SCTP6-LISTEN",
	"SENDTO":               "SOCKET-SENDTO",
	"SOCKS":                "SOCKS4",
	"SOCKS5":               "SOCKS5-CONNECT",
	"SOCKS5-BIND":          "SOCKS5-LISTEN",
	"SSL":                  "OPENSSL",
	"SSL-L":                "OPENSSL-LISTEN",
	"TCP":                  "TCP-CONNECT",
	"TCP-L":                "TCP-LISTEN",
	"TCP4":                 "TCP4-CONNECT",
	"TCP4-L":               "TCP4-LISTEN",
	"TCP6":                 "TCP6-CONNECT",
	"TCP6-L":               "TCP6-LISTEN",
	"UDP":                  "UDP-CONNECT",
	"UDP-DGRAM":            "UDP-DATAGRAM",
	"UDP-L":                "UDP-LISTEN",
	"UDP-SEND":             "UDP-SENDTO",
	"UDP4":                 "UDP4-CONNECT",
	"UDP4-DGRAM":           "UDP4-DATAGRAM",
	"UDP4-L":               "UDP4-LISTEN",
	"UDP4-SEND":            "UDP4-SENDTO",
	"UDP6":                 "UDP6-CONNECT",
	"UDP6-DGRAM":           "UDP6-DATAGRAM",
	"UDP6-L":               "UDP6-LISTEN",
	"UDP6-SEND":            "UDP6-SENDTO",
	"UDPLITE":              "UDPLITE-CONNECT",
	"UDPLITE-DGRAM":        "UDPLITE-DATAGRAM",
	"UDPLITE-L":            "UDPLITE-LISTEN",
	"UDPLITE-SEND":         "UDPLITE-SENDTO",
	"UDPLITE4":             "UDPLITE4-CONNECT",
	"UDPLITE4-DGRAM":       "UDPLITE4-DATAGRAM",
	"UDPLITE4-L":           "UDPLITE4-LISTEN",
	"UDPLITE4-SEND":        "UDPLITE4-SENDTO",
	"UDPLITE6":             "UDPLITE6-CONNECT",
	"UDPLITE6-DGRAM":       "UDPLITE6-DATAGRAM",
	"UDPLITE6-L":           "UDPLITE6-LISTEN",
	"UDPLITE6-SEND":        "UDPLITE6-SENDTO",
	"UNIX":                 "UNIX-CLIENT",
	"UNIX-L":               "UNIX-LISTEN",
	"UNIX-SEND":            "UNIX-SENDTO",
	"VSOCK":                "VSOCK-CONNECT",
	"VSOCK-L":              "VSOCK-LISTEN",
}
