package xio_test

import (
	"testing"

	"github.com/oittaa/socat/internal/xio"
	_ "github.com/oittaa/socat/internal/xio/all"
)

func TestAddressAllowsOption(t *testing.T) {
	cases := []struct {
		addr, opt string
		want      bool
	}{
		{"TCP-CONNECT", "readbytes", true},
		{"TCP-CONNECT", "crnl", true},
		{"TCP-CONNECT", "cr", true},
		{"TCP-CONNECT", "shut-down", true},
		{"TCP-CONNECT", "setsid", true},
		{"TCP-CONNECT", "pty", false},
		{"TCP-CONNECT", "echo", false},
		{"TCP-CONNECT", "excl", false},
		{"TCP-CONNECT", "append", true},
		{"TCP-CONNECT", "ftruncate", false},
		{"FD", "ftruncate", true},
		{"FD", "append", true},
		{"EXEC", "append", true},
		{"STDIO", "append", true},
		{"TCP-CONNECT", "fork", true},
		{"UDP-CONNECT", "fork", false},
		{"UDP-CONNECT", "lowport", true},
		{"UDP-LISTEN", "accept-timeout", true},
		{"UDP-RECVFROM", "accept-timeout", false},
		{"UDP-RECVFROM", "range", true},
		{"UNIX-RECVFROM", "range", false},
		{"UNIX-RECVFROM", "accept-timeout", false},
		{"CREATE", "excl", false},
		{"OPEN", "excl", true},
		{"EXEC", "pty", true},
		{"EXEC", "fork", false},
		{"EXEC", "dash", true},
		{"EXEC", "setpgid", true},
		{"SHELL", "dash", true},
		{"SYSTEM", "pgid", true},
		{"TCP-CONNECT", "dash", false},
		{"TCP-CONNECT", "setpgid", false},
		{"EXEC", "sighup", true},
		{"SYSTEM", "sigint", true},
		{"SHELL", "sigquit", true},
		{"TCP-CONNECT", "sighup", false},
		{"OPEN", "sigint", false},
		{"TCP-LISTEN", "sourceport", true},
		{"OPEN", "sourceport", false},
		{"TUN", "rcvtimeo", false},
		{"INTERFACE", "rcvtimeo", true},
		{"OPENSSL", "cert", true},
		{"TCP-CONNECT", "cert", false},
		{"QUIC", "lowport", true},
		{"WS", "nodelay", true},
		{"TCP", "noatime", true},
		{"UDP4", "pktinfo", true},
		{"OPEN", "noatime", true},
		{"CREATE", "pktinfo", false},
		{"OPEN", "o-direct", true},
		{"PIPE", "o-direct", true},
		{"CREATE", "o-direct", false},
		{"OPEN", "o-sync", true},
		{"PIPE", "o-sync", true},
		{"CREATE", "o-sync", false},
		{"FD", "o-sync", false},
		{"OPEN", "async", true},
		{"FD", "async", true},
		{"TCP-CONNECT", "async", true},
		{"CREATE", "async", true},
		{"OPEN", "lseek", true},
		{"FD", "lseek", true},
		{"TCP-CONNECT", "lseek", false},
		{"PIPE", "lseek", false},
		{"FD", "flock", true},
		{"TCP-CONNECT", "flock", true},
		{"OPEN", "flock", true},
		{"FD", "perm-late", true},
		{"OPEN", "perm-late", true},
		{"TCP-CONNECT", "perm-late", true},
		{"OPEN", "fs-noatime", true},
		{"CREATE", "fs-noatime", true},
		{"FD", "fs-noatime", true},
		{"PIPE", "fs-noatime", false},
		{"EXEC", "fs-noatime", false},
		{"OPEN", "fs-append", true},
		{"CREATE", "fs-append", true},
		{"FD", "fs-append", true},
		{"PIPE", "fs-append", false},
		{"EXEC", "fs-append", false},
		{"TCP", "fs-append", false},
		{"OPEN", "nodump", true},
		{"TCP", "nodump", false},
		{"PIPE", "ext2-nodump", false},
		{"OPEN", "notail", true},
		{"EXEC", "fs-immutable", false},
		{"UDP4", "ipv6-join-group", false},
		{"UDP4-RECV", "ipv6-join-group", false},
		{"TCP4", "ipv6-join-group", false},
		{"IP4", "ipv6-join-group", false},
		{"UDP6", "ipv6-join-group", true},
		{"UDP6-RECV", "ipv6-join-group", true},
		{"TCP6", "ipv6-join-group", true},
		{"UDP4", "ip-add-membership", true},
		{"UDP6", "ip-add-membership", true},
		{"UDP4", "join-group", false},
		{"UDP6", "join-group", true},
		{"UDP4", "add-membership", true},
		{"UDP4", "membership", true},
		{"UDP4", "ipv6-multicast-loop", false},
		{"UDP6", "ipv6-multicast-loop", true},
		{"TCP4", "mcloop6", false},
		{"TCP6", "mcloop6", true},
		{"UDP4", "ipv6-join-source-group", false},
		{"UDP6", "ipv6-join-source-group", true},
		{"UDP4", "join-source-group", false},
		{"UDP6", "join-source-group", true},
		{"UDP4", "ip-add-source-membership", true},
		{"UDP6", "ip-add-source-membership", true},
		{"UDP4", "ip-multicast-ttl", true},
		{"TCP", "ip-freebind", true},
		{"TCP", "ip-transparent", true},
		{"ACCEPT-FD", "fork", true},
		{"ACCEPT-FD", "range", true},
		{"ACCEPT-FD", "sourceport", true},
		{"ACCEPT-FD", "lowport", true},
		{"ACCEPT-FD", "tcpwrap", true},
		{"ACCEPT-FD", "backlog", false},
		{"ACCEPT-FD", "accept-timeout", false},
		{"ACCEPT-FD", "pty", false},
		{"ACCEPT-FD", "unlink-early", false},
		{"ACCEPT", "fork", true},
		{"ACCEPT", "excl", false},
		{"TCP-CONNECT", "group-early", false},
		{"OPEN", "group-early", true},
		{"CREATE", "group-early", true},
		{"TCP-CONNECT", "gid-e", false},
		{"TCP-CONNECT", "group-late", true},
		{"TCP-CONNECT", "chdir", true},
		{"TCP-CONNECT", "umask", true},
		{"OPENSSL-L", "cert", true},
		{"SSL-CONNECT", "cert", true},
		{"SSL-LISTEN", "cert", true},
		{"ABSTRACT-L", "backlog", true},
		{"UNIX-DATAGRAM", "unlink-early", true},
	}
	for _, tc := range cases {
		got := xio.AddressAllowsOption(tc.addr, tc.opt)
		if got != tc.want {
			t.Errorf("AddressAllowsOption(%s, %s)=%v want %v", tc.addr, tc.opt, got, tc.want)
		}
	}
}
