package optionmeta

// Address capability tokens.
const (
	CapFD        = "fd"
	CapFIFO      = "fifo"
	CapCHR       = "chr"
	CapBLK       = "blk"
	CapREG       = "reg"
	CapSocket    = "socket"
	CapNamed     = "named"
	CapOpen      = "open"
	CapListen    = "listen"
	CapRange     = "range"
	CapChild     = "child"
	CapRetry     = "retry"
	CapTermios   = "termios"
	CapPTY       = "pty"
	CapParent    = "parent"
	CapFork      = "fork"
	CapExec      = "exec"
	CapShell     = "shell"
	CapSockUNIX  = "sock-unix"
	CapSockIP4   = "sock-ip4"
	CapSockIP6   = "sock-ip6"
	CapIPTCP     = "ip-tcp"
	CapIPUDP     = "ip-udp"
	CapIPSCTP    = "ip-sctp"
	CapOpenSSL   = "openssl"
	CapHTTP      = "http"
	CapSocks     = "socks"
	CapInterface = "interface"
	CapPOSIXMQ   = "posixmq"
)
