package optionmeta

var fileOptions = []Option{
	{Canonical: "binary", Aliases: []string{"bin", "o-binary"},
		Desc: "use Windows binary descriptor mode", Value: OptionalBool,
		Advertise: AdvertiseWindows, Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "text", Aliases: []string{"o-text"},
		Desc: "translate Windows CRLF text on descriptor I/O", Value: OptionalBool,
		Advertise: AdvertiseWindows, Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "noinherit", Aliases: []string{"o-noinherit"},
		Desc: "prevent child processes from inheriting the descriptor", Value: OptionalBool,
		Advertise: AdvertiseWindows, Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "rdonly", Aliases: []string{"o-rdonly", "o_rdonly"},
		Desc:  "open read-only",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "wronly", Aliases: []string{"o-wronly", "o_wronly"},
		Desc:  "open write-only",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "rdwr", Aliases: []string{"o-rdwr", "o_rdwr"},
		Desc:  "open read-write",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "creat", Aliases: []string{"create", "o-creat", "o-create", "o_creat", "o_create"},
		Desc:  "create the file",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "excl", Aliases: []string{"o-excl", "o_excl"},
		Desc:  "fail if the file exists",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "append", Aliases: []string{"o-append"},
		Desc:  "write at the end of the file",
		Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "cloexec",
		Desc: "close the descriptor when executing a child program (=0 keeps it open)", Value: OptionalBool,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "trunc", Aliases: []string{"o-trunc"},
		Desc:  "truncate on open",
		Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "nonblock", Aliases: []string{"o-nonblock", "ndelay", "o-ndelay", "o_ndelay"},
		Desc:      "use nonblocking I/O",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "o-direct", Aliases: []string{"direct", "o_direct"},
		Desc:      "request direct file I/O",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-sync", Aliases: []string{"sync", "o_sync"},
		Desc:      "complete file writes synchronously",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-dsync", Aliases: []string{"dsync", "o_dsync"},
		Desc:      "complete file data writes synchronously",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-rsync", Aliases: []string{"rsync", "o_rsync"},
		Desc:      "synchronize reads with pending writes",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-noctty", Aliases: []string{"noctty", "o_noctty"},
		Desc:      "do not acquire a controlling terminal",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-nofollow", Aliases: []string{"nofollow", "o_nofollow"},
		Desc:      "reject a symbolic link as the final path component",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-directory", Aliases: []string{"directory", "o_directory"},
		Desc:      "require the path to be a directory",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "o-largefile", Aliases: []string{"largefile", "o_largefile"},
		Desc:      "allow access to large files",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capOpen},
	},
	{Canonical: "async", Aliases: []string{"o-async"},
		Desc:      "enable asynchronous I/O notification on the descriptor",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capOpenFD},
	},
	{Canonical: "o-noatime", PublicAliases: []string{"noatime"},
		Desc:      "do not update file access times",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capOpenFD, AddressTypes: fdOptionAddressTypes},
	},
	{Canonical: "fs-append", Aliases: []string{"ext2-append", "ext3-append"},
		Desc: "set the file append-only attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-compr", Aliases: []string{"compr", "ext2-compr", "ext3-compr"},
		Desc: "set the file compression attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-dirsync", Aliases: []string{"dirsync", "ext2-dirsync", "ext3-dirsync"},
		Desc: "set the directory synchronous-update attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-immutable", Aliases: []string{"immutable", "ext2-immutable", "ext3-immutable"},
		Desc: "set the file immutable attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-journal-data", Aliases: []string{"journal", "journal-data", "ext2-journal-data", "ext3-journal-data"},
		Desc: "set the file data-journaling attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-noatime", Aliases: []string{"ext2-noatime", "ext3-noatime"},
		Desc: "set the file no-access-time attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-nodump", Aliases: []string{"nodump", "ext2-nodump", "ext3-nodump"},
		Desc: "exclude the file from dumps", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-notail", Aliases: []string{"notail", "ext2-notail", "ext3-notail"},
		Desc: "disable file tail merging", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-secrm", Aliases: []string{"secrm", "ext2-secrm", "ext3-secrm"},
		Desc: "set the file secure-deletion attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-sync", Aliases: []string{"ext2-sync", "ext3-sync"},
		Desc: "set the file synchronous-update attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-topdir", Aliases: []string{"topdir", "ext2-topdir", "ext3-topdir"},
		Desc: "set the top-level-directory allocation attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "fs-unrm", Aliases: []string{"unrm", "ext2-unrm", "ext3-unrm"},
		Desc: "set the file undelete attribute", Value: OptionalBool,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "f-setpipe-sz", PublicAliases: []string{"pipesz"},
		Desc: "set Linux pipe capacity", Value: IntegerMin1,
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capFIFO, AddressTypes: fdOptionAddressTypes},
	},
	{Canonical: "perm", Aliases: []string{"mode"},
		Desc: "set file permissions after opening", Value: Octal7777,
		Scope: AddressScope{Caps: capFDNamed},
	},
	{Canonical: "perm-late",
		Desc: "set descriptor permissions after perm/user/group", Value: Octal7777,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "perm-early",
		Desc: "set permissions before opening, or after binding a UNIX socket", Value: Octal7777,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "ftruncate", Aliases: []string{"truncate", "ftruncate32", "ftruncate64"},
		Desc: "resize an opened regular file to this length", Value: IntegerMin0,
		Scope: AddressScope{Caps: capREG},
	},
	{Canonical: "lseek", Aliases: []string{"lseek64", "lseek64-set", "seek", "seek-set", "lseek32", "lseek32-set"},
		Desc: "set the file position to this offset", Value: OptionalInt64,
		Scope: AddressScope{Caps: capRegBlk},
	},
	{Canonical: "seek-cur", Aliases: []string{"lseek64-cur", "lseek32-cur"},
		Desc: "move the file position by this offset", Value: OptionalInt64,
		Scope: AddressScope{Caps: capRegBlk},
	},
	{Canonical: "seek-end", Aliases: []string{"lseek64-end", "lseek32-end"},
		Desc: "set the file position relative to the end", Value: OptionalInt64,
		Scope: AddressScope{Caps: capRegBlk},
	},
	{Canonical: "setlk", Aliases: []string{"f-setlk-wr", "f-setlk", "setlk-wr"},
		Desc:      "nonblocking whole-file write lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "setlkw", Aliases: []string{"f-setlkw-wr", "f-setlkw", "lock", "lockw", "setlkw-wr"},
		Desc:      "blocking whole-file write lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "setlk-rd", Aliases: []string{"f-setlk-rd"},
		Desc:      "nonblocking whole-file read lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "setlkw-rd", Aliases: []string{"f-setlkw-rd"},
		Desc:      "blocking whole-file read lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "flock", Aliases: []string{"flock-ex"},
		Desc:      "exclusive whole-file lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "flock-nb", Aliases: []string{"flock-ex-nb"},
		Desc:      "nonblocking exclusive whole-file lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "flock-sh",
		Desc:      "shared whole-file lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "flock-sh-nb",
		Desc:      "nonblocking shared whole-file lock",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "ioctl-void", Aliases: []string{"ioctl"},
		Desc: "device control request with no argument", Value: GenericIoctl,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "ioctl-int",
		Desc: "device control request with an integer argument", Value: GenericIoctl,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "ioctl-intp",
		Desc: "device control request with an integer buffer", Value: GenericIoctl,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "ioctl-bin",
		Desc: "device control request with a dalan byte buffer", Value: GenericIoctl,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "ioctl-string",
		Desc: "device control request with a zero-terminated string", Value: GenericIoctl,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "umask",
		Desc: "file creation permission mask during open or EXEC start", Value: Octal777,
		Advertise: AdvertiseLinuxDarwin,
	},
	{Canonical: "user", Aliases: []string{"uid", "owner"},
		Desc: "file owner", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFDNamed},
	},
	{Canonical: "group", Aliases: []string{"gid"},
		Desc: "file group", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFDNamed},
	},
	{Canonical: "user-late", Aliases: []string{"uid-l"},
		Desc: "set descriptor owner after user/group", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "group-late", Aliases: []string{"gid-l"},
		Desc: "set descriptor group after user/group", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "user-early", Aliases: []string{"uid-e"},
		Desc: "set owner before opening, or after binding a UNIX socket", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "group-early", Aliases: []string{"gid-e"},
		Desc: "set group before opening, or after binding a UNIX socket", Value: RequiredString,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "unlink-early", Aliases: []string{"new"},
		Desc:  "unlink before bind/open",
		Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "unlink", Aliases: []string{"delete", "remove"},
		Desc:  "unlink before open",
		Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "unlink-close",
		Desc:  "unlink on close",
		Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "unlink-late",
		Desc:  "unlink immediately after open",
		Scope: AddressScope{Caps: capNamed},
	},
	{Canonical: "unix-bind-tempname", Aliases: []string{"bind-tempname"},
		Desc: "bind a temporary UNIX name", PathValue: true,
		Scope: AddressScope{Caps: capSockUNIX},
	},
	{Canonical: "unix-tightsocklen", Aliases: []string{"tightsocklen"},
		Desc: "use the shortest UNIX socket address length", Value: UnixTightSocklen,
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSockUNIX},
	},
	{Canonical: "socktype", Aliases: []string{"so-type", "type"},
		Value: IntegerMinNeg1,
		Scope: AddressScope{Caps: capSocket},
	},
}
