package optionmeta

// File, FD, and UNIX options.
var fileDefs = []Def{
	// Files and UNIX
	{
		Canonical:     "binary",
		Section:       SectionFiles,
		PublicAliases: []string{"bin", "o-binary"},
		ParserAliases: []string{"bin", "o-binary"},
		Desc:          "use Windows binary descriptor mode",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapOpenFD},
		Advertise:     AdvertiseWindows,
	},
	{
		Canonical:     "text",
		Section:       SectionFiles,
		PublicAliases: []string{"o-text"},
		ParserAliases: []string{"o-text"},
		Desc:          "translate Windows CRLF text on descriptor I/O",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapOpenFD},
		Advertise:     AdvertiseWindows,
	},
	{
		Canonical:     "noinherit",
		Section:       SectionFiles,
		PublicAliases: []string{"o-noinherit"},
		ParserAliases: []string{"o-noinherit"},
		Desc:          "clear Windows HANDLE_FLAG_INHERIT",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapOpenFD},
		Advertise:     AdvertiseWindows,
	},
	{
		Canonical:     "rdonly",
		Section:       SectionFiles,
		PublicAliases: []string{"o-rdonly", "o_rdonly"},
		ParserAliases: []string{"o-rdonly", "o_rdonly"},
		Desc:          "open read-only",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "wronly",
		Section:       SectionFiles,
		PublicAliases: []string{"o-wronly", "o_wronly"},
		ParserAliases: []string{"o-wronly", "o_wronly"},
		Desc:          "open write-only",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "rdwr",
		Section:       SectionFiles,
		PublicAliases: []string{"o-rdwr", "o_rdwr"},
		ParserAliases: []string{"o-rdwr", "o_rdwr"},
		Desc:          "open read-write",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "creat",
		Section:       SectionFiles,
		PublicAliases: []string{"create", "o-creat", "o-create", "o_creat", "o_create"},
		ParserAliases: []string{"create", "o-creat", "o-create", "o_creat", "o_create"},
		Desc:          "create the file",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "excl",
		Section:       SectionFiles,
		PublicAliases: []string{"o-excl", "o_excl"},
		ParserAliases: []string{"o-excl", "o_excl"},
		Desc:          "fail if the file exists",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "append",
		Section:       SectionFiles,
		PublicAliases: []string{"o-append"},
		ParserAliases: []string{"o-append"},
		Desc:          "open append or fcntl O_APPEND on an exposed fd",
		Apply:         Applicability{Caps: CapOpenFD},
	},
	{
		Canonical: "cloexec",
		Section:   SectionFiles,
		Desc:      "fcntl FD_CLOEXEC on an exposed fd (cloexec=0 clears it)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "trunc",
		Section:       SectionFiles,
		PublicAliases: []string{"o-trunc"},
		ParserAliases: []string{"o-trunc"},
		Desc:          "truncate on open",
		Apply:         Applicability{Caps: CapOpen},
	},
	{
		Canonical:     "nonblock",
		Section:       SectionFiles,
		PublicAliases: []string{"o-nonblock", "ndelay", "o-ndelay", "o_ndelay"},
		ParserAliases: []string{"o-nonblock", "ndelay", "o-ndelay", "o_ndelay"},
		Desc:          "O_NONBLOCK",
		Apply:         Applicability{Caps: CapOpenFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-direct",
		Section:       SectionFiles,
		PublicAliases: []string{"direct", "o_direct"},
		ParserAliases: []string{"direct", "o_direct"},
		Desc:          "set O_DIRECT at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "o-sync",
		Section:       SectionFiles,
		PublicAliases: []string{"sync", "o_sync"},
		ParserAliases: []string{"sync", "o_sync"},
		Desc:          "set O_SYNC at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-dsync",
		Section:       SectionFiles,
		PublicAliases: []string{"dsync", "o_dsync"},
		ParserAliases: []string{"dsync", "o_dsync"},
		Desc:          "set O_DSYNC at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-rsync",
		Section:       SectionFiles,
		PublicAliases: []string{"rsync", "o_rsync"},
		ParserAliases: []string{"rsync", "o_rsync"},
		Desc:          "set O_RSYNC at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "o-noctty",
		Section:       SectionFiles,
		PublicAliases: []string{"noctty", "o_noctty"},
		ParserAliases: []string{"noctty", "o_noctty"},
		Desc:          "set O_NOCTTY at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-nofollow",
		Section:       SectionFiles,
		PublicAliases: []string{"nofollow", "o_nofollow"},
		ParserAliases: []string{"nofollow", "o_nofollow"},
		Desc:          "set O_NOFOLLOW at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-directory",
		Section:       SectionFiles,
		PublicAliases: []string{"directory", "o_directory"},
		ParserAliases: []string{"directory", "o_directory"},
		Desc:          "set O_DIRECTORY at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-largefile",
		Section:       SectionFiles,
		PublicAliases: []string{"largefile", "o_largefile"},
		ParserAliases: []string{"largefile", "o_largefile"},
		Desc:          "set O_LARGEFILE at open",
		Apply:         Applicability{Caps: CapOpen},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "async",
		Section:       SectionFiles,
		PublicAliases: []string{"o-async"},
		ParserAliases: []string{"o-async"},
		Desc:          "fcntl O_ASYNC on the descriptor",
		Apply:         Applicability{Caps: CapOpenFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-noatime",
		Section:       SectionFiles,
		PublicAliases: []string{"noatime"},
		Desc:          "set O_NOATIME on the opened descriptor",
		Apply:         Applicability{Caps: CapOpenFD, TypeSet: TypesFD},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-append",
		Section:       SectionFiles,
		PublicAliases: []string{"ext2-append", "ext3-append"},
		ParserAliases: []string{"ext2-append", "ext3-append"},
		Desc:          "set FS_APPEND_FL on the file (not O_APPEND)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-compr",
		Section:       SectionFiles,
		PublicAliases: []string{"compr", "ext2-compr", "ext3-compr"},
		ParserAliases: []string{"compr", "ext2-compr", "ext3-compr"},
		Desc:          "set FS_COMPR_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-dirsync",
		Section:       SectionFiles,
		PublicAliases: []string{"dirsync", "ext2-dirsync", "ext3-dirsync"},
		ParserAliases: []string{"dirsync", "ext2-dirsync", "ext3-dirsync"},
		Desc:          "set FS_DIRSYNC_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-immutable",
		Section:       SectionFiles,
		PublicAliases: []string{"immutable", "ext2-immutable", "ext3-immutable"},
		ParserAliases: []string{"immutable", "ext2-immutable", "ext3-immutable"},
		Desc:          "set FS_IMMUTABLE_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-journal-data",
		Section:       SectionFiles,
		PublicAliases: []string{"journal", "journal-data", "ext2-journal-data", "ext3-journal-data"},
		ParserAliases: []string{"journal", "journal-data", "ext2-journal-data", "ext3-journal-data"},
		Desc:          "set FS_JOURNAL_DATA_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-noatime",
		Section:       SectionFiles,
		PublicAliases: []string{"ext2-noatime", "ext3-noatime"},
		ParserAliases: []string{"ext2-noatime", "ext3-noatime"},
		Desc:          "set FS_NOATIME_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-nodump",
		Section:       SectionFiles,
		PublicAliases: []string{"nodump", "ext2-nodump", "ext3-nodump"},
		ParserAliases: []string{"nodump", "ext2-nodump", "ext3-nodump"},
		Desc:          "set FS_NODUMP_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-notail",
		Section:       SectionFiles,
		PublicAliases: []string{"notail", "ext2-notail", "ext3-notail"},
		ParserAliases: []string{"notail", "ext2-notail", "ext3-notail"},
		Desc:          "set FS_NOTAIL_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-secrm",
		Section:       SectionFiles,
		PublicAliases: []string{"secrm", "ext2-secrm", "ext3-secrm"},
		ParserAliases: []string{"secrm", "ext2-secrm", "ext3-secrm"},
		Desc:          "set FS_SECRM_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-sync",
		Section:       SectionFiles,
		PublicAliases: []string{"ext2-sync", "ext3-sync"},
		ParserAliases: []string{"ext2-sync", "ext3-sync"},
		Desc:          "set FS_SYNC_FL on the file (not O_SYNC)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-topdir",
		Section:       SectionFiles,
		PublicAliases: []string{"topdir", "ext2-topdir", "ext3-topdir"},
		ParserAliases: []string{"topdir", "ext2-topdir", "ext3-topdir"},
		Desc:          "set FS_TOPDIR_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "fs-unrm",
		Section:       SectionFiles,
		PublicAliases: []string{"unrm", "ext2-unrm", "ext3-unrm"},
		ParserAliases: []string{"unrm", "ext2-unrm", "ext3-unrm"},
		Desc:          "set FS_UNRM_FL on the file",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapREG},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "f-setpipe-sz",
		Section:       SectionFiles,
		PublicAliases: []string{"pipesz"},
		Desc:          "set Linux pipe capacity",
		Value:         IntegerMin1,
		Apply:         Applicability{Caps: CapFIFO, TypeSet: TypesFD},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "perm",
		Section:       SectionFiles,
		PublicAliases: []string{"mode"},
		ParserAliases: []string{"mode"},
		Desc:          "chmod after open or on an exposed fd",
		Value:         Octal7777,
		Apply:         Applicability{Caps: CapFDNamed},
	},
	{
		Canonical: "perm-late",
		Section:   SectionFiles,
		Desc:      "fchmod after perm/user/group",
		Value:     Octal7777,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "perm-early",
		Section:   SectionFiles,
		Desc:      "chmod existing name before open, or UNIX socket after bind",
		Value:     Octal7777,
		Apply:     Applicability{Caps: CapNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ftruncate",
		Section:       SectionFiles,
		PublicAliases: []string{"truncate", "ftruncate32", "ftruncate64"},
		ParserAliases: []string{"truncate", "ftruncate32", "ftruncate64"},
		Desc:          "ftruncate(2) an opened regular file to this length",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapREG},
	},
	{
		Canonical:     "lseek",
		Section:       SectionFiles,
		PublicAliases: []string{"lseek64", "lseek64-set", "seek", "seek-set", "lseek32", "lseek32-set"},
		ParserAliases: []string{"lseek64", "lseek64-set", "seek", "seek-set", "lseek32", "lseek32-set"},
		Desc:          "lseek SEEK_SET on a regular file or block device",
		Value:         OptionalInt64,
		Apply:         Applicability{Caps: CapRegBlk},
	},
	{
		Canonical:     "seek-cur",
		Section:       SectionFiles,
		PublicAliases: []string{"lseek64-cur", "lseek32-cur"},
		ParserAliases: []string{"lseek64-cur", "lseek32-cur"},
		Desc:          "lseek SEEK_CUR on a regular file or block device",
		Value:         OptionalInt64,
		Apply:         Applicability{Caps: CapRegBlk},
	},
	{
		Canonical:     "seek-end",
		Section:       SectionFiles,
		PublicAliases: []string{"lseek64-end", "lseek32-end"},
		ParserAliases: []string{"lseek64-end", "lseek32-end"},
		Desc:          "lseek SEEK_END on a regular file or block device",
		Value:         OptionalInt64,
		Apply:         Applicability{Caps: CapRegBlk},
	},
	{
		Canonical:     "setlk",
		Section:       SectionFiles,
		PublicAliases: []string{"f-setlk-wr", "f-setlk", "setlk-wr"},
		ParserAliases: []string{"f-setlk", "f-setlk-wr", "setlk-wr"},
		Desc:          "nonblocking whole-file write lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "setlkw",
		Section:       SectionFiles,
		PublicAliases: []string{"f-setlkw-wr", "f-setlkw", "lock", "lockw", "setlkw-wr"},
		ParserAliases: []string{"f-setlkw", "f-setlkw-wr", "setlkw-wr", "lock", "lockw"},
		Desc:          "blocking whole-file write lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "setlk-rd",
		Section:       SectionFiles,
		PublicAliases: []string{"f-setlk-rd"},
		ParserAliases: []string{"f-setlk-rd"},
		Desc:          "nonblocking whole-file read lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "setlkw-rd",
		Section:       SectionFiles,
		PublicAliases: []string{"f-setlkw-rd"},
		ParserAliases: []string{"f-setlkw-rd"},
		Desc:          "blocking whole-file read lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "flock",
		Section:       SectionFiles,
		PublicAliases: []string{"flock-ex"},
		ParserAliases: []string{"flock-ex"},
		Desc:          "exclusive flock(2) lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "flock-nb",
		Section:       SectionFiles,
		PublicAliases: []string{"flock-ex-nb"},
		ParserAliases: []string{"flock-ex-nb"},
		Desc:          "nonblocking exclusive flock(2) lock",
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock-sh",
		Section:   SectionFiles,
		Desc:      "shared flock(2) lock",
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock-sh-nb",
		Section:   SectionFiles,
		Desc:      "nonblocking shared flock(2) lock",
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ioctl-void",
		Section:       SectionFiles,
		PublicAliases: []string{"ioctl"},
		ParserAliases: []string{"ioctl"},
		Desc:          "ioctl() with request and NULL as the third argument",
		Value:         GenericIoctl,
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-int",
		Section:   SectionFiles,
		Desc:      "ioctl() with request and integer value",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-intp",
		Section:   SectionFiles,
		Desc:      "ioctl() with request and pointer to integer",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-bin",
		Section:   SectionFiles,
		Desc:      "ioctl() with request and pointer to dalan bytes",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-string",
		Section:   SectionFiles,
		Desc:      "ioctl() with request and pointer to C string (not dalan)",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "umask",
		Section:   SectionFiles,
		Desc:      "umask during open or EXEC start",
		Value:     Octal777,
		Apply:     Applicability{Unrestricted: true},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "user",
		Section:       SectionFiles,
		PublicAliases: []string{"uid", "owner"},
		ParserAliases: []string{"uid", "owner"},
		Desc:          "file owner",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapFDNamed},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "group",
		Section:       SectionFiles,
		PublicAliases: []string{"gid"},
		ParserAliases: []string{"gid"},
		Desc:          "file group",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapFDNamed},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "user-late",
		Section:       SectionFiles,
		PublicAliases: []string{"uid-l"},
		ParserAliases: []string{"uid-l"},
		Desc:          "fchown user after user/group",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "group-late",
		Section:       SectionFiles,
		PublicAliases: []string{"gid-l"},
		ParserAliases: []string{"gid-l"},
		Desc:          "fchown group after user/group",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapFD},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "user-early",
		Section:       SectionFiles,
		PublicAliases: []string{"uid-e"},
		ParserAliases: []string{"uid-e"},
		Desc:          "chown existing name before open, or UNIX socket after bind",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapNamed},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "group-early",
		Section:       SectionFiles,
		PublicAliases: []string{"gid-e"},
		ParserAliases: []string{"gid-e"},
		Desc:          "chgrp existing name before open, or UNIX socket after bind",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapNamed},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "unlink-early",
		Section:       SectionFiles,
		PublicAliases: []string{"new"},
		ParserAliases: []string{"new"},
		Desc:          "unlink before bind/open",
		Apply:         Applicability{Caps: CapNamed},
	},
	{
		Canonical:     "unlink",
		Section:       SectionFiles,
		PublicAliases: []string{"delete", "remove"},
		ParserAliases: []string{"delete", "remove"},
		Desc:          "unlink before open",
		Apply:         Applicability{Caps: CapNamed},
	},
	{
		Canonical: "unlink-close",
		Section:   SectionFiles,
		Desc:      "unlink on close",
		Apply:     Applicability{Caps: CapNamed},
	},
	{
		Canonical: "unlink-late",
		Section:   SectionFiles,
		Desc:      "unlink immediately after open",
		Apply:     Applicability{Caps: CapNamed},
	},
	{
		Canonical:     "unix-bind-tempname",
		Section:       SectionFiles,
		PublicAliases: []string{"bind-tempname"},
		ParserAliases: []string{"bind-tempname"},
		Desc:          "bind a temporary UNIX name",
		Apply:         Applicability{Caps: CapSockUNIX},
		PathValue:     true,
	},
	{
		Canonical:     "unix-tightsocklen",
		Section:       SectionFiles,
		PublicAliases: []string{"tightsocklen"},
		ParserAliases: []string{"tightsocklen"},
		Desc:          "use a tight sockaddr_un length",
		Value:         UnixTightSocklen,
		Apply:         Applicability{Caps: CapSockUNIX},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "socktype",
		Section:       SectionFiles,
		PublicAliases: []string{"so-type", "type"},
		ParserAliases: []string{"so-type", "type"},
		DynamicDesc:   "unix-socktype",
		Value:         IntegerMinNeg1,
		Apply:         Applicability{Caps: CapSocket},
	},
}
