package optionmeta

// File, FD, and UNIX options.
var fileDefs = []Def{
	// Files and UNIX
	{
		Canonical: "binary",
		Section:   SectionFiles,
		Aliases:   []string{"bin", "o-binary"},
		Desc:      "use Windows binary descriptor mode",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capOpenFD},
		Advertise: AdvertiseWindows,
	},
	{
		Canonical: "text",
		Section:   SectionFiles,
		Aliases:   []string{"o-text"},
		Desc:      "translate Windows CRLF text on descriptor I/O",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capOpenFD},
		Advertise: AdvertiseWindows,
	},
	{
		Canonical: "noinherit",
		Section:   SectionFiles,
		Aliases:   []string{"o-noinherit"},
		Desc:      "prevent child processes from inheriting the descriptor",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capOpenFD},
		Advertise: AdvertiseWindows,
	},
	{
		Canonical: "rdonly",
		Section:   SectionFiles,
		Aliases:   []string{"o-rdonly", "o_rdonly"},
		Desc:      "open read-only",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "wronly",
		Section:   SectionFiles,
		Aliases:   []string{"o-wronly", "o_wronly"},
		Desc:      "open write-only",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "rdwr",
		Section:   SectionFiles,
		Aliases:   []string{"o-rdwr", "o_rdwr"},
		Desc:      "open read-write",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "creat",
		Section:   SectionFiles,
		Aliases:   []string{"create", "o-creat", "o-create", "o_creat", "o_create"},
		Desc:      "create the file",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "excl",
		Section:   SectionFiles,
		Aliases:   []string{"o-excl", "o_excl"},
		Desc:      "fail if the file exists",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "append",
		Section:   SectionFiles,
		Aliases:   []string{"o-append"},
		Desc:      "write at the end of the file",
		Apply:     Applicability{Caps: capOpenFD},
	},
	{
		Canonical: "cloexec",
		Section:   SectionFiles,
		Desc:      "close the descriptor when executing a child program (=0 keeps it open)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "trunc",
		Section:   SectionFiles,
		Aliases:   []string{"o-trunc"},
		Desc:      "truncate on open",
		Apply:     Applicability{Caps: capOpen},
	},
	{
		Canonical: "nonblock",
		Section:   SectionFiles,
		Aliases:   []string{"o-nonblock", "ndelay", "o-ndelay", "o_ndelay"},
		Desc:      "use nonblocking I/O",
		Apply:     Applicability{Caps: capOpenFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-direct",
		Section:   SectionFiles,
		Aliases:   []string{"direct", "o_direct"},
		Desc:      "request direct file I/O",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "o-sync",
		Section:   SectionFiles,
		Aliases:   []string{"sync", "o_sync"},
		Desc:      "complete file writes synchronously",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-dsync",
		Section:   SectionFiles,
		Aliases:   []string{"dsync", "o_dsync"},
		Desc:      "complete file data writes synchronously",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-rsync",
		Section:   SectionFiles,
		Aliases:   []string{"rsync", "o_rsync"},
		Desc:      "synchronize reads with pending writes",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "o-noctty",
		Section:   SectionFiles,
		Aliases:   []string{"noctty", "o_noctty"},
		Desc:      "do not acquire a controlling terminal",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-nofollow",
		Section:   SectionFiles,
		Aliases:   []string{"nofollow", "o_nofollow"},
		Desc:      "reject a symbolic link as the final path component",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-directory",
		Section:   SectionFiles,
		Aliases:   []string{"directory", "o_directory"},
		Desc:      "require the path to be a directory",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "o-largefile",
		Section:   SectionFiles,
		Aliases:   []string{"largefile", "o_largefile"},
		Desc:      "allow access to large files",
		Apply:     Applicability{Caps: capOpen},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "async",
		Section:   SectionFiles,
		Aliases:   []string{"o-async"},
		Desc:      "enable asynchronous I/O notification on the descriptor",
		Apply:     Applicability{Caps: capOpenFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "o-noatime",
		Section:       SectionFiles,
		PublicAliases: []string{"noatime"},
		Desc:          "do not update file access times",
		Apply:         Applicability{Caps: capOpenFD, TypeSet: TypesFD},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical: "fs-append",
		Section:   SectionFiles,
		Aliases:   []string{"ext2-append", "ext3-append"},
		Desc:      "set the file append-only attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-compr",
		Section:   SectionFiles,
		Aliases:   []string{"compr", "ext2-compr", "ext3-compr"},
		Desc:      "set the file compression attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-dirsync",
		Section:   SectionFiles,
		Aliases:   []string{"dirsync", "ext2-dirsync", "ext3-dirsync"},
		Desc:      "set the directory synchronous-update attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-immutable",
		Section:   SectionFiles,
		Aliases:   []string{"immutable", "ext2-immutable", "ext3-immutable"},
		Desc:      "set the file immutable attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-journal-data",
		Section:   SectionFiles,
		Aliases:   []string{"journal", "journal-data", "ext2-journal-data", "ext3-journal-data"},
		Desc:      "set the file data-journaling attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-noatime",
		Section:   SectionFiles,
		Aliases:   []string{"ext2-noatime", "ext3-noatime"},
		Desc:      "set the file no-access-time attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-nodump",
		Section:   SectionFiles,
		Aliases:   []string{"nodump", "ext2-nodump", "ext3-nodump"},
		Desc:      "exclude the file from dumps",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-notail",
		Section:   SectionFiles,
		Aliases:   []string{"notail", "ext2-notail", "ext3-notail"},
		Desc:      "disable file tail merging",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-secrm",
		Section:   SectionFiles,
		Aliases:   []string{"secrm", "ext2-secrm", "ext3-secrm"},
		Desc:      "set the file secure-deletion attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-sync",
		Section:   SectionFiles,
		Aliases:   []string{"ext2-sync", "ext3-sync"},
		Desc:      "set the file synchronous-update attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-topdir",
		Section:   SectionFiles,
		Aliases:   []string{"topdir", "ext2-topdir", "ext3-topdir"},
		Desc:      "set the top-level-directory allocation attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fs-unrm",
		Section:   SectionFiles,
		Aliases:   []string{"unrm", "ext2-unrm", "ext3-unrm"},
		Desc:      "set the file undelete attribute",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capREG},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical:     "f-setpipe-sz",
		Section:       SectionFiles,
		PublicAliases: []string{"pipesz"},
		Desc:          "set Linux pipe capacity",
		Value:         IntegerMin1,
		Apply:         Applicability{Caps: capFIFO, TypeSet: TypesFD},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical: "perm",
		Section:   SectionFiles,
		Aliases:   []string{"mode"},
		Desc:      "set file permissions after opening",
		Value:     Octal7777,
		Apply:     Applicability{Caps: capFDNamed},
	},
	{
		Canonical: "perm-late",
		Section:   SectionFiles,
		Desc:      "set descriptor permissions after perm/user/group",
		Value:     Octal7777,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "perm-early",
		Section:   SectionFiles,
		Desc:      "set permissions before opening, or after binding a UNIX socket",
		Value:     Octal7777,
		Apply:     Applicability{Caps: capNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ftruncate",
		Section:   SectionFiles,
		Aliases:   []string{"truncate", "ftruncate32", "ftruncate64"},
		Desc:      "resize an opened regular file to this length",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capREG},
	},
	{
		Canonical: "lseek",
		Section:   SectionFiles,
		Aliases:   []string{"lseek64", "lseek64-set", "seek", "seek-set", "lseek32", "lseek32-set"},
		Desc:      "set the file position to this offset",
		Value:     OptionalInt64,
		Apply:     Applicability{Caps: capRegBlk},
	},
	{
		Canonical: "seek-cur",
		Section:   SectionFiles,
		Aliases:   []string{"lseek64-cur", "lseek32-cur"},
		Desc:      "move the file position by this offset",
		Value:     OptionalInt64,
		Apply:     Applicability{Caps: capRegBlk},
	},
	{
		Canonical: "seek-end",
		Section:   SectionFiles,
		Aliases:   []string{"lseek64-end", "lseek32-end"},
		Desc:      "set the file position relative to the end",
		Value:     OptionalInt64,
		Apply:     Applicability{Caps: capRegBlk},
	},
	{
		Canonical: "setlk",
		Section:   SectionFiles,
		Aliases:   []string{"f-setlk-wr", "f-setlk", "setlk-wr"},
		Desc:      "nonblocking whole-file write lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "setlkw",
		Section:   SectionFiles,
		Aliases:   []string{"f-setlkw-wr", "f-setlkw", "lock", "lockw", "setlkw-wr"},
		Desc:      "blocking whole-file write lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "setlk-rd",
		Section:   SectionFiles,
		Aliases:   []string{"f-setlk-rd"},
		Desc:      "nonblocking whole-file read lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "setlkw-rd",
		Section:   SectionFiles,
		Aliases:   []string{"f-setlkw-rd"},
		Desc:      "blocking whole-file read lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock",
		Section:   SectionFiles,
		Aliases:   []string{"flock-ex"},
		Desc:      "exclusive whole-file lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock-nb",
		Section:   SectionFiles,
		Aliases:   []string{"flock-ex-nb"},
		Desc:      "nonblocking exclusive whole-file lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock-sh",
		Section:   SectionFiles,
		Desc:      "shared whole-file lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "flock-sh-nb",
		Section:   SectionFiles,
		Desc:      "nonblocking shared whole-file lock",
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-void",
		Section:   SectionFiles,
		Aliases:   []string{"ioctl"},
		Desc:      "device control request with no argument",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-int",
		Section:   SectionFiles,
		Desc:      "device control request with an integer argument",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-intp",
		Section:   SectionFiles,
		Desc:      "device control request with an integer buffer",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-bin",
		Section:   SectionFiles,
		Desc:      "device control request with a dalan byte buffer",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ioctl-string",
		Section:   SectionFiles,
		Desc:      "device control request with a zero-terminated string",
		Value:     GenericIoctl,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "umask",
		Section:   SectionFiles,
		Desc:      "file creation permission mask during open or EXEC start",
		Value:     Octal777,
		Apply:     Applicability{Unrestricted: true},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "user",
		Section:   SectionFiles,
		Aliases:   []string{"uid", "owner"},
		Desc:      "file owner",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capFDNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "group",
		Section:   SectionFiles,
		Aliases:   []string{"gid"},
		Desc:      "file group",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capFDNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "user-late",
		Section:   SectionFiles,
		Aliases:   []string{"uid-l"},
		Desc:      "set descriptor owner after user/group",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "group-late",
		Section:   SectionFiles,
		Aliases:   []string{"gid-l"},
		Desc:      "set descriptor group after user/group",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "user-early",
		Section:   SectionFiles,
		Aliases:   []string{"uid-e"},
		Desc:      "set owner before opening, or after binding a UNIX socket",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "group-early",
		Section:   SectionFiles,
		Aliases:   []string{"gid-e"},
		Desc:      "set group before opening, or after binding a UNIX socket",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capNamed},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "unlink-early",
		Section:   SectionFiles,
		Aliases:   []string{"new"},
		Desc:      "unlink before bind/open",
		Apply:     Applicability{Caps: capNamed},
	},
	{
		Canonical: "unlink",
		Section:   SectionFiles,
		Aliases:   []string{"delete", "remove"},
		Desc:      "unlink before open",
		Apply:     Applicability{Caps: capNamed},
	},
	{
		Canonical: "unlink-close",
		Section:   SectionFiles,
		Desc:      "unlink on close",
		Apply:     Applicability{Caps: capNamed},
	},
	{
		Canonical: "unlink-late",
		Section:   SectionFiles,
		Desc:      "unlink immediately after open",
		Apply:     Applicability{Caps: capNamed},
	},
	{
		Canonical: "unix-bind-tempname",
		Section:   SectionFiles,
		Aliases:   []string{"bind-tempname"},
		Desc:      "bind a temporary UNIX name",
		Apply:     Applicability{Caps: capSockUNIX},
		PathValue: true,
	},
	{
		Canonical: "unix-tightsocklen",
		Section:   SectionFiles,
		Aliases:   []string{"tightsocklen"},
		Desc:      "use the shortest UNIX socket address length",
		Value:     UnixTightSocklen,
		Apply:     Applicability{Caps: capSockUNIX},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:   "socktype",
		Section:     SectionFiles,
		Aliases:     []string{"so-type", "type"},
		DynamicDesc: "unix-socktype",
		Value:       IntegerMinNeg1,
		Apply:       Applicability{Caps: capSocket},
	},
}
