package optionmeta

var listenOptions = []Option{
	{Canonical: "reuseaddr", Aliases: []string{"so-reuseaddr"},
		Desc:  "SO_REUSEADDR (TCP listen default on; UDP-LISTEN with fork or this option)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "reuseport", Aliases: []string{"so-reuseport"},
		Desc:      "SO_REUSEPORT",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "fork",
		Desc:  "new session per accept or client redial",
		Scope: AddressScope{Caps: capChild},
	},
	{Canonical: "nofork",
		Desc:  "do not fork (single session)",
		Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "max-children", Aliases: []string{"maxchildren"},
		Desc:  "limit concurrent fork sessions (needs fork)",
		Scope: AddressScope{Caps: capChild},
	},
	{Canonical: "children-shutup", Aliases: []string{"child-shutup"},
		Desc:  "lower fork-child log severity",
		Scope: AddressScope{Caps: capChild},
	},
	{Canonical: "bind",
		Desc:  "local address or interface",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "connect-timeout",
		Desc:  "connect timeout",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "handshake-timeout",
		Desc:  "TLS, DTLS, WebSocket, QUIC, PROXY, or SOCKS handshake timeout",
		Scope: AddressScope{AddressTypes: handshakeAddressTypes},
	},
	{Canonical: "accept-timeout", Aliases: []string{"listen-timeout"},
		Desc:  "listen accept timeout (exit 0)",
		Scope: AddressScope{Caps: capListen},
	},
	{Canonical: "backlog",
		Desc:      "listen backlog",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capListen, AddressTypes: backlogListenAddressTypes},
	},
	{Canonical: "pf", Aliases: []string{"protocol-family"},
		Desc:  "address family (4, 6, IP4, IP6, …)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "ai-addrconfig", Aliases: []string{"addrconfig"},
		Desc:  "skip addresses whose family is not configured on this host (default on without a family hint; =0 disables)",
		Scope: resolverScope,
	},
	{Canonical: "ai-passive", Aliases: []string{"passive"},
		Desc:  "use wildcard addresses for listen/bind (default); =0 uses loopback, and dual-stack connect prefers IPv6",
		Scope: resolverScope,
	},
	{Canonical: "ai-v4mapped", Aliases: []string{"v4mapped"},
		Desc:  "map IPv4 answers onto IPv6 lookups (off unless set)",
		Scope: resolverScope,
	},
	{Canonical: "ai-all",
		Desc:  "with ai-v4mapped, also return mapped IPv4 answers when IPv6 answers exist",
		Scope: resolverScope,
	},
	{Canonical: "ipv6-v6only", Aliases: []string{"ipv6only", "v6only"},
		Desc:  "IPV6_V6ONLY",
		Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "retry",
		Desc:  "retry count on connect failure",
		Scope: AddressScope{Caps: capRetry},
	},
	{Canonical: "forever",
		Desc:  "retry without limit",
		Scope: AddressScope{Caps: capRetry},
	},
	{Canonical: "interval", Aliases: []string{"intervall"},
		Desc:  "retry or fork-redial interval",
		Scope: AddressScope{Caps: capRetry},
	},
}
