package optionmeta

// Listen, connect, and security-filter options.
var listenDefs = []Def{
	// Listen and connect
	{
		Canonical: "reuseaddr",
		Section:   SectionListen,
		Aliases:   []string{"so-reuseaddr"},
		Desc:      "SO_REUSEADDR (TCP listen default on; UDP-LISTEN with fork or this option)",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "reuseport",
		Section:   SectionListen,
		Aliases:   []string{"so-reuseport"},
		Desc:      "SO_REUSEPORT",
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "fork",
		Section:   SectionListen,
		Desc:      "new session per accept or client redial",
		Apply:     Applicability{Caps: capChild},
	},
	{
		Canonical: "nofork",
		Section:   SectionListen,
		Desc:      "do not fork (single session)",
		Apply:     Applicability{Caps: capFork},
	},
	{
		Canonical: "max-children",
		Section:   SectionListen,
		Aliases:   []string{"maxchildren"},
		Desc:      "limit concurrent fork sessions (needs fork)",
		Value:     IntegerMin1,
		Apply:     Applicability{Caps: capChild},
	},
	{
		Canonical: "children-shutup",
		Section:   SectionListen,
		Aliases:   []string{"child-shutup"},
		Desc:      "lower fork-child log severity",
		Value:     OptionalInteger0,
		Apply:     Applicability{Caps: capChild},
	},
	{
		Canonical: "bind",
		Section:   SectionListen,
		Desc:      "local address or interface",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "connect-timeout",
		Section:   SectionListen,
		Desc:      "connect timeout",
		Value:     Duration,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "handshake-timeout",
		Section:   SectionListen,
		Desc:      "TLS, DTLS, WebSocket, QUIC, PROXY, or SOCKS handshake timeout",
		Value:     Duration,
		Apply:     Applicability{TypeSet: TypesHandshake},
	},
	{
		Canonical: "accept-timeout",
		Section:   SectionListen,
		Aliases:   []string{"listen-timeout"},
		Desc:      "listen accept timeout (exit 0)",
		Value:     Duration,
		Apply:     Applicability{Caps: capListen},
	},
	{
		Canonical: "backlog",
		Section:   SectionListen,
		Desc:      "listen backlog",
		Value:     IntegerMin1,
		Apply:     Applicability{Caps: capListen, TypeSet: TypesBacklog},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "pf",
		Section:   SectionListen,
		Aliases:   []string{"protocol-family"},
		Desc:      "address family (4, 6, IP4, IP6, …)",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "ai-addrconfig",
		Section:   SectionListen,
		Aliases:   []string{"addrconfig"},
		Desc:      "skip addresses whose family is not configured on this host (default on without a family hint; =0 disables)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "ai-passive",
		Section:   SectionListen,
		Aliases:   []string{"passive"},
		Desc:      "use wildcard addresses for listen/bind (default); =0 uses loopback, and dual-stack connect prefers IPv6",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "ai-v4mapped",
		Section:   SectionListen,
		Aliases:   []string{"v4mapped"},
		Desc:      "map IPv4 answers onto IPv6 lookups (off unless set)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "ai-all",
		Section:   SectionListen,
		Desc:      "with ai-v4mapped, also return mapped IPv4 answers when IPv6 answers exist",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "ipv6-v6only",
		Section:   SectionListen,
		Aliases:   []string{"ipv6only", "v6only"},
		Desc:      "IPV6_V6ONLY",
		Apply:     Applicability{Caps: capIP6},
	},
	{
		Canonical: "retry",
		Section:   SectionListen,
		Desc:      "retry count on connect failure",
		Value:     IntegerMinNeg1,
		Apply:     Applicability{Caps: capRetry},
	},
	{
		Canonical: "forever",
		Section:   SectionListen,
		Desc:      "retry without limit",
		Apply:     Applicability{Caps: capRetry},
	},
	{
		Canonical: "interval",
		Section:   SectionListen,
		Aliases:   []string{"intervall"},
		Desc:      "retry or fork-redial interval",
		Value:     Duration,
		Apply:     Applicability{Caps: capRetry},
	},
	// Security filters
	{
		Canonical: "range",
		Section:   SectionSecurity,
		Desc:      "accept only peers in this network",
		Apply:     Applicability{Caps: capRange},
	},
	{
		Canonical: "sourceport",
		Section:   SectionSecurity,
		Aliases:   []string{"sp"},
		Desc:      "peer source port (listen) or bind port (connect); DATAGRAM dest-port receive filter",
		Apply:     Applicability{Caps: capIPApp},
	},
	{
		Canonical: "lowport",
		Section:   SectionSecurity,
		Desc:      "require or bind a low source port",
		Apply:     Applicability{Caps: capIPApp},
	},
	{
		Canonical: "tcpwrap",
		Section:   SectionSecurity,
		Aliases:   []string{"tcpwrappers", "tcpwrapper", "libwrap", "wrap"},
		Desc:      "apply hosts.allow / hosts.deny",
		Apply:     Applicability{Caps: capRange},
	},
	{
		Canonical: "tcpwrap-etc",
		Section:   SectionSecurity,
		Aliases:   []string{"tcpwrap-dir"},
		Desc:      "directory of hosts.allow / hosts.deny",
		Apply:     Applicability{Caps: capRange},
	},
	{
		Canonical: "hosts-allow",
		Section:   SectionSecurity,
		Aliases:   []string{"allow-table", "tcpwrap-hosts-allow-table"},
		Desc:      "allow table path",
		Apply:     Applicability{Caps: capRange},
		PathValue: true,
	},
	{
		Canonical: "hosts-deny",
		Section:   SectionSecurity,
		Aliases:   []string{"deny-table", "tcpwrap-hosts-deny-table"},
		Desc:      "deny table path",
		Apply:     Applicability{Caps: capRange},
		PathValue: true,
	},
}
