package optionmeta

// Listen, connect, and security-filter options.
var listenDefs = []Def{
	// Listen and connect
	{
		Canonical:     "reuseaddr",
		Section:       SectionListen,
		PublicAliases: []string{"so-reuseaddr"},
		ParserAliases: []string{"so-reuseaddr"},
		Desc:          "SO_REUSEADDR (TCP listen default on; UDP-LISTEN with fork or this option)",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "reuseport",
		Section:       SectionListen,
		PublicAliases: []string{"so-reuseport"},
		ParserAliases: []string{"so-reuseport"},
		Desc:          "SO_REUSEPORT",
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical: "fork",
		Section:   SectionListen,
		Desc:      "new session per accept or client redial",
		Apply:     Applicability{Caps: CapChild},
	},
	{
		Canonical: "nofork",
		Section:   SectionListen,
		Desc:      "do not fork (single session)",
		Apply:     Applicability{Caps: CapFork},
	},
	{
		Canonical:     "max-children",
		Section:       SectionListen,
		PublicAliases: []string{"maxchildren"},
		ParserAliases: []string{"maxchildren"},
		Desc:          "limit concurrent fork sessions (needs fork)",
		Value:         IntegerMin1,
		Apply:         Applicability{Caps: CapChild},
	},
	{
		Canonical:     "children-shutup",
		Section:       SectionListen,
		PublicAliases: []string{"child-shutup"},
		ParserAliases: []string{"child-shutup"},
		Desc:          "lower fork-child log severity",
		Value:         OptionalInteger0,
		Apply:         Applicability{Caps: CapChild},
	},
	{
		Canonical: "bind",
		Section:   SectionListen,
		Desc:      "local address or interface",
		Apply:     Applicability{Caps: CapSocket},
	},
	{
		Canonical: "connect-timeout",
		Section:   SectionListen,
		Desc:      "connect timeout",
		Value:     Duration,
		Apply:     Applicability{Caps: CapSocket},
	},
	{
		Canonical: "handshake-timeout",
		Section:   SectionListen,
		Desc:      "TLS, DTLS, WebSocket, QUIC, PROXY, or SOCKS handshake timeout",
		Value:     Duration,
		Apply:     Applicability{TypeSet: TypesHandshake},
	},
	{
		Canonical:     "accept-timeout",
		Section:       SectionListen,
		PublicAliases: []string{"listen-timeout"},
		ParserAliases: []string{"listen-timeout"},
		Desc:          "listen accept timeout (exit 0)",
		Value:         Duration,
		Apply:         Applicability{Caps: CapListen},
	},
	{
		Canonical: "backlog",
		Section:   SectionListen,
		Desc:      "listen backlog",
		Value:     IntegerMin1,
		Apply:     Applicability{Caps: CapListen, TypeSet: TypesBacklog},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "pf",
		Section:       SectionListen,
		PublicAliases: []string{"protocol-family"},
		ParserAliases: []string{"protocol-family"},
		Desc:          "address family (4, 6, IP4, IP6, …)",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "ai-addrconfig",
		Section:       SectionListen,
		PublicAliases: []string{"addrconfig"},
		ParserAliases: []string{"addrconfig"},
		Desc:          "skip addresses whose family is not configured on this host (default on without a family hint; =0 disables)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical:     "ai-passive",
		Section:       SectionListen,
		PublicAliases: []string{"passive"},
		ParserAliases: []string{"passive"},
		Desc:          "use wildcard addresses for listen/bind (default); =0 uses loopback, and dual-stack connect prefers IPv6",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical:     "ai-v4mapped",
		Section:       SectionListen,
		PublicAliases: []string{"v4mapped"},
		ParserAliases: []string{"v4mapped"},
		Desc:          "map IPv4 answers onto IPv6 lookups (off unless set)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "ai-all",
		Section:   SectionListen,
		Desc:      "with ai-v4mapped, also return mapped IPv4 answers when IPv6 answers exist",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical:     "ipv6-v6only",
		Section:       SectionListen,
		PublicAliases: []string{"ipv6only", "v6only"},
		ParserAliases: []string{"ipv6only", "v6only"},
		Desc:          "IPV6_V6ONLY",
		Apply:         Applicability{Caps: CapIP6},
	},
	{
		Canonical: "retry",
		Section:   SectionListen,
		Desc:      "retry count on connect failure",
		Value:     IntegerMinNeg1,
		Apply:     Applicability{Caps: CapRetry},
	},
	{
		Canonical: "forever",
		Section:   SectionListen,
		Desc:      "retry without limit",
		Apply:     Applicability{Caps: CapRetry},
	},
	{
		Canonical:     "interval",
		Section:       SectionListen,
		PublicAliases: []string{"intervall"},
		ParserAliases: []string{"intervall"},
		Desc:          "retry or fork-redial interval",
		Value:         Duration,
		Apply:         Applicability{Caps: CapRetry},
	},
	// Security filters
	{
		Canonical: "range",
		Section:   SectionSecurity,
		Desc:      "accept only peers in this network",
		Apply:     Applicability{Caps: CapRange},
	},
	{
		Canonical:     "sourceport",
		Section:       SectionSecurity,
		PublicAliases: []string{"sp"},
		ParserAliases: []string{"sp"},
		Desc:          "peer source port (listen) or bind port (connect); DATAGRAM dest-port receive filter",
		Apply:         Applicability{Caps: CapIPApp},
	},
	{
		Canonical: "lowport",
		Section:   SectionSecurity,
		Desc:      "require or bind a low source port",
		Apply:     Applicability{Caps: CapIPApp},
	},
	{
		Canonical:     "tcpwrap",
		Section:       SectionSecurity,
		PublicAliases: []string{"tcpwrappers", "tcpwrapper", "libwrap", "wrap"},
		ParserAliases: []string{"tcpwrappers", "tcpwrapper", "libwrap", "wrap"},
		Desc:          "apply hosts.allow / hosts.deny",
		Apply:         Applicability{Caps: CapRange},
	},
	{
		Canonical:     "tcpwrap-etc",
		Section:       SectionSecurity,
		PublicAliases: []string{"tcpwrap-dir"},
		ParserAliases: []string{"tcpwrap-dir"},
		Desc:          "directory of hosts.allow / hosts.deny",
		Apply:         Applicability{Caps: CapRange},
	},
	{
		Canonical:     "hosts-allow",
		Section:       SectionSecurity,
		PublicAliases: []string{"allow-table", "tcpwrap-hosts-allow-table"},
		ParserAliases: []string{"allow-table", "tcpwrap-hosts-allow-table"},
		Desc:          "allow table path",
		Apply:         Applicability{Caps: CapRange},
		PathValue:     true,
	},
	{
		Canonical:     "hosts-deny",
		Section:       SectionSecurity,
		PublicAliases: []string{"deny-table", "tcpwrap-hosts-deny-table"},
		ParserAliases: []string{"deny-table", "tcpwrap-hosts-deny-table"},
		Desc:          "deny table path",
		Apply:         Applicability{Caps: CapRange},
		PathValue:     true,
	},
}
