package optionmeta

// EXEC/SYSTEM/SHELL, PTY, and advertised TERMIOS options.
var processDefs = []Def{
	// EXEC, SYSTEM, SHELL
	{
		Canonical: "pipes",
		Section:   SectionExec,
		Desc:      "connect with pipes",
		Apply:     Applicability{Caps: CapFork},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "pty",
		Section:   SectionExec,
		Desc:      "run on a pseudo-terminal",
		Apply:     Applicability{Caps: CapFork},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "setsid",
		Section:       SectionExec,
		PublicAliases: []string{"sid"},
		ParserAliases: []string{"sid"},
		Desc:          "new session",
		Apply:         Applicability{Unrestricted: true},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "dash",
		Section:       SectionExec,
		PublicAliases: []string{"login"},
		ParserAliases: []string{"login"},
		Desc:          "prefix EXEC argv[0] with '-' (login shell); unused on SYSTEM/SHELL",
		Apply:         Applicability{Caps: CapExec},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "setpgid",
		Section:       SectionExec,
		PublicAliases: []string{"pgid"},
		ParserAliases: []string{"pgid"},
		Desc:          "set child process group; omitted/0/1 start a new group",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapFork},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical: "sighup",
		Section:   SectionExec,
		Desc:      "pass SIGHUP to the EXEC/SYSTEM/SHELL child instead of exiting",
		Value:     NoValue,
		Apply:     Applicability{Caps: CapParent},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "sigint",
		Section:   SectionExec,
		Desc:      "pass SIGINT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Value:     NoValue,
		Apply:     Applicability{Caps: CapParent},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "sigquit",
		Section:   SectionExec,
		Desc:      "pass SIGQUIT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Value:     NoValue,
		Apply:     Applicability{Caps: CapParent},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "stderr",
		Section:   SectionExec,
		Desc:      "include child stderr",
		Apply:     Applicability{Caps: CapFork},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "fdin",
		Section:   SectionExec,
		Desc:      "child stdin fd number",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: CapFork},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "fdout",
		Section:   SectionExec,
		Desc:      "child stdout fd number",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: CapFork},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "shell",
		Section:   SectionExec,
		Desc:      "use a shell",
		Apply:     Applicability{Caps: CapShell},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "chdir",
		Section:       SectionExec,
		PublicAliases: []string{"cd"},
		ParserAliases: []string{"cd"},
		Desc:          "change directory before open or exec",
		Value:         RequiredString,
		Apply:         Applicability{Unrestricted: true},
		PathValue:     true,
	},
	{
		Canonical: "shut-none",
		Section:   SectionExec,
		Desc:      "do not half-close the write side",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapFD},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "shut-down",
		Section:   SectionExec,
		Desc:      "shutdown(SHUT_WR) instead of the address default",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapFD},
	},
	{
		Canonical: "shut-close",
		Section:   SectionExec,
		Desc:      "fully close instead of half-closing",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapFD},
	},
	{
		Canonical:     "end-close",
		Section:       SectionExec,
		PublicAliases: []string{"close"},
		ParserAliases: []string{"close"},
		Desc:          "just close file descriptors; do not kill EXEC child",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapFD},
	},
	{
		Canonical: "shut",
		Section:   SectionExec,
		Desc:      "half-close mode (none, down, close, or null)",
		Value:     Shut,
		Apply:     Applicability{Caps: CapFD},
	},
	{
		Canonical: "shut-null",
		Section:   SectionExec,
		Desc:      "0-byte datagram as half-close",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapFD},
	},
	// PTY and TERMIOS
	{
		Canonical:     "link",
		Section:       SectionPTY,
		PublicAliases: []string{"symbolic-link"},
		ParserAliases: []string{"symbolic-link"},
		Desc:          "symlink to the PTY slave",
		Apply:         Applicability{Caps: CapPTY},
		PathValue:     true,
	},
	{
		Canonical: "raw",
		Section:   SectionPTY,
		Desc:      "obsolete raw termios mode",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "cfmakeraw",
		Section:       SectionPTY,
		PublicAliases: []string{"termios-cfmakeraw"},
		ParserAliases: []string{"termios-cfmakeraw"},
		Desc:          "raw termios (cfmakeraw)",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "rawer",
		Section:       SectionPTY,
		PublicAliases: []string{"termios-rawer"},
		ParserAliases: []string{"termios-rawer"},
		Desc:          "stricter raw termios",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical: "sane",
		Section:   SectionPTY,
		Desc:      "reset termios to sane defaults",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical: "echo",
		Section:   SectionPTY,
		Desc:      "terminal echo",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "echoe",
		Section:       SectionPTY,
		PublicAliases: []string{"crterase"},
		ParserAliases: []string{"crterase"},
		Desc:          "ECHOE",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "echoke",
		Section:       SectionPTY,
		PublicAliases: []string{"crtkill"},
		ParserAliases: []string{"crtkill"},
		Desc:          "ECHOKE",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "echoctl",
		Section:       SectionPTY,
		PublicAliases: []string{"ctlecho"},
		ParserAliases: []string{"ctlecho"},
		Desc:          "ECHOCTL",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "hupcl",
		Section:       SectionPTY,
		PublicAliases: []string{"hup"},
		ParserAliases: []string{"hup"},
		Desc:          "HUPCL",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "ixoff",
		Section:       SectionPTY,
		PublicAliases: []string{"tandem"},
		ParserAliases: []string{"tandem"},
		Desc:          "IXOFF",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical: "opost",
		Section:   SectionPTY,
		Desc:      "output post-processing",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical: "ispeed",
		Section:   SectionPTY,
		Desc:      "input baud",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical: "ospeed",
		Section:   SectionPTY,
		Desc:      "output baud",
		Apply:     Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "tiocswinsz",
		Section:       SectionPTY,
		PublicAliases: []string{"winsz"},
		ParserAliases: []string{"winsz"},
		Desc:          "window size cols:rows",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical:     "pty-wait-slave",
		Section:       SectionPTY,
		PublicAliases: []string{"wait-slave", "waitslave"},
		ParserAliases: []string{"wait-slave", "waitslave"},
		Desc:          "wait until the slave is open",
		Apply:         Applicability{Caps: CapPTY},
	},
	{
		Canonical:     "pty-interval",
		Section:       SectionPTY,
		PublicAliases: []string{"pty-intervall"},
		ParserAliases: []string{"pty-intervall"},
		Desc:          "poll interval while waiting for slave",
		Value:         Duration,
		Apply:         Applicability{Caps: CapPTY},
	},
	{
		Canonical: "sitout-eio",
		Section:   SectionPTY,
		Desc:      "wait this long on PTY master EIO after the slave closes",
		Value:     Duration,
		Apply:     Applicability{Caps: CapPTY},
	},
	{
		Canonical:     "ctty",
		Section:       SectionPTY,
		PublicAliases: []string{"tiocsctty"},
		ParserAliases: []string{"tiocsctty"},
		Desc:          "make the PTY the controlling tty",
		Apply:         Applicability{Caps: CapTermios},
	},
	{
		Canonical: "ptmx",
		Section:   SectionPTY,
		Desc:      "run on a pseudo-terminal via /dev/ptmx",
		Apply:     Applicability{Caps: CapPTY},
	},
	{
		Canonical: "openpty",
		Section:   SectionPTY,
		Desc:      "run on a pseudo-terminal",
		Apply:     Applicability{Caps: CapPTY},
	},
	{
		Canonical: "escape",
		Section:   SectionPTY,
		Desc:      "escape character",
		Apply:     Applicability{Unrestricted: true},
	},
}
