package optionmeta

var processOptions = []Option{
	{Canonical: "pipes", Kind: KindBool,
		Desc:      "connect with pipes",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "pty", Kind: KindBool,
		Desc:      "run on a pseudo-terminal",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "setsid", Kind: KindBool, Aliases: []string{"sid"},
		Desc:      "new session",
		Advertise: AdvertiseLinuxDarwin,
	},
	{Canonical: "dash", Kind: KindBool, Aliases: []string{"login"},
		Desc:      "prefix EXEC argv[0] with '-' (login shell); unused on SYSTEM/SHELL",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capExec},
	},
	{Canonical: "setpgid", Kind: KindOmittedInt, Aliases: []string{"pgid"},
		Desc:      "set child process group; omitted/0/1 start a new group",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "sighup", Kind: KindNoValueSpell,
		Desc:      "pass SIGHUP to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "sigint", Kind: KindNoValueSpell,
		Desc:      "pass SIGINT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "sigquit", Kind: KindNoValueSpell,
		Desc:      "pass SIGQUIT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "stderr", Kind: KindBool,
		Desc:      "include child stderr",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "fdin", Kind: KindFD,
		Desc:      "child stdin fd number",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "fdout", Kind: KindFD,
		Desc:      "child stdout fd number",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "shell", Kind: KindPresent,
		Desc:      "use a shell",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capShell},
	},
	{Canonical: "chdir", Kind: KindString, Aliases: []string{"cd"},
		Desc: "change directory before open or exec", PathValue: true,
	},
	{Canonical: "shut-none", Kind: KindNamedShut,
		Desc:  "do not half-close the write side",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-down", Kind: KindNamedShut,
		Desc:  "stop socket writes while keeping the read side open",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-close", Kind: KindNamedShut,
		Desc:  "fully close instead of half-closing",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "end-close", Kind: KindBool, Aliases: []string{"close"},
		Desc:  "just close file descriptors; do not kill EXEC child",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut", Kind: KindShut,
		Desc:  "half-close mode (none, down, close, or null)",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-null", Kind: KindNamedShut,
		Desc:  "0-byte datagram as half-close",
		Scope: AddressScope{Caps: capFD},
	},
}
