package optionmeta

var processOptions = []Option{
	{Canonical: "pipes",
		Desc:      "connect with pipes",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "pty",
		Desc:      "run on a pseudo-terminal",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "setsid", Aliases: []string{"sid"},
		Desc:      "new session",
		Advertise: AdvertiseLinuxDarwin,
	},
	{Canonical: "dash", Aliases: []string{"login"},
		Desc:      "prefix EXEC argv[0] with '-' (login shell); unused on SYSTEM/SHELL",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capExec},
	},
	{Canonical: "setpgid", Aliases: []string{"pgid"},
		Desc:      "set child process group; omitted/0/1 start a new group",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "sighup",
		Desc:      "pass SIGHUP to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "sigint",
		Desc:      "pass SIGINT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "sigquit",
		Desc:      "pass SIGQUIT to the EXEC/SYSTEM/SHELL child instead of exiting",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capParent},
	},
	{Canonical: "stderr",
		Desc:      "include child stderr",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "fdin",
		Desc:      "child stdin fd number",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "fdout",
		Desc:      "child stdout fd number",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFork},
	},
	{Canonical: "shell",
		Desc:      "use a shell",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capShell},
	},
	{Canonical: "chdir", Aliases: []string{"cd"},
		Desc: "change directory before open or exec", PathValue: true,
	},
	{Canonical: "shut-none",
		Desc:      "do not half-close the write side",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-down",
		Desc:  "stop socket writes while keeping the read side open",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-close",
		Desc:  "fully close instead of half-closing",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "end-close", Aliases: []string{"close"},
		Desc:  "just close file descriptors; do not kill EXEC child",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut",
		Desc:  "half-close mode (none, down, close, or null)",
		Scope: AddressScope{Caps: capFD},
	},
	{Canonical: "shut-null",
		Desc:  "0-byte datagram as half-close",
		Scope: AddressScope{Caps: capFD},
	},
}
