package optionmeta

var proxyOptions = []Option{
	{Canonical: "proxyport",
		Desc:  "HTTP proxy port",
		Scope: proxyScope,
	},
	{Canonical: "http-version",
		Desc:  "CONNECT HTTP version (1.0, 1.1, 2, 3)",
		Scope: proxyScope,
	},
	{Canonical: "h2c",
		Desc:  "cleartext HTTP/2 CONNECT",
		Scope: AddressScope{AddressTypes: proxyAddressTypes},
	},
	{Canonical: "ignorecr",
		Desc:  "accept LF as HTTP CONNECT response line terminator",
		Scope: proxyScope,
	},
	{Canonical: "proxy-resolve", Aliases: []string{"resolve", "resolv"},
		Desc:  "resolve CONNECT target locally",
		Scope: proxyScope,
	},
	{Canonical: "proxy-authorization", Aliases: []string{"proxyauth", "proxy-auth"},
		Desc:  "proxy basic auth user:pass",
		Scope: proxyScope,
	},
	{Canonical: "proxy-authorization-file", Aliases: []string{"proxyauthfile"},
		Desc: "read proxy auth from a file", PathValue: true,
		Scope: proxyScope,
	},
	{Canonical: "socksport",
		Desc:  "SOCKS server port",
		Scope: socksScope,
	},
	{Canonical: "socksuser",
		Desc:  "SOCKS user name",
		Scope: socksScope,
	},
	{Canonical: "sockspass", Aliases: []string{"sockspassword"},
		Desc:  "SOCKS password",
		Scope: socksScope,
	},
}
