package optionmeta

var proxyOptions = []Option{
	{Canonical: "proxyport", Kind: KindPort,
		Desc:  "HTTP proxy port",
		Scope: proxyScope,
	},
	{Canonical: "http-version", Kind: KindHTTPVersion,
		Desc:  "CONNECT HTTP version (1.0, 1.1, 2, 3)",
		Scope: proxyScope,
	},
	{Canonical: "h2c", Kind: KindBool,
		Desc:  "cleartext HTTP/2 CONNECT",
		Scope: AddressScope{AddressTypes: proxyAddressTypes},
	},
	{Canonical: "ignorecr", Kind: KindBool,
		Desc:  "accept LF as HTTP CONNECT response line terminator",
		Scope: proxyScope,
	},
	{Canonical: "proxy-resolve", Kind: KindBool, Aliases: []string{"resolve", "resolv"},
		Desc:  "resolve CONNECT target locally",
		Scope: proxyScope,
	},
	{Canonical: "proxy-authorization", Kind: KindPresent, Aliases: []string{"proxyauth", "proxy-auth"},
		Desc:  "proxy basic auth user:pass",
		Scope: proxyScope,
	},
	{Canonical: "proxy-authorization-file", Kind: KindPresent, Aliases: []string{"proxyauthfile"},
		Desc: "read proxy auth from a file", PathValue: true,
		Scope: proxyScope,
	},
	{Canonical: "socksport", Kind: KindPresentPort,
		Desc:  "SOCKS server port",
		Scope: socksScope,
	},
	{Canonical: "socksuser", Kind: KindPresent,
		Desc:  "SOCKS user name",
		Scope: socksScope,
	},
	{Canonical: "sockspass", Kind: KindPresent, Aliases: []string{"sockspassword"},
		Desc:  "SOCKS password",
		Scope: socksScope,
	},
}
