package optionmeta

var securityOptions = []Option{
	{Canonical: "range",
		Desc:  "accept only peers in this network",
		Scope: AddressScope{Caps: capRange},
	},
	{Canonical: "sourceport", Aliases: []string{"sp"},
		Desc:  "peer source port (listen) or bind port (connect); DATAGRAM dest-port receive filter",
		Scope: AddressScope{Caps: capIPApp},
	},
	{Canonical: "lowport",
		Desc:  "require or bind a low source port",
		Scope: AddressScope{Caps: capIPApp},
	},
	{Canonical: "tcpwrap", Aliases: []string{"tcpwrappers", "tcpwrapper", "libwrap", "wrap"},
		Desc:  "apply hosts.allow / hosts.deny",
		Scope: AddressScope{Caps: capRange},
	},
	{Canonical: "tcpwrap-etc", Aliases: []string{"tcpwrap-dir"},
		Desc:  "directory of hosts.allow / hosts.deny",
		Scope: AddressScope{Caps: capRange},
	},
	{Canonical: "hosts-allow", Aliases: []string{"allow-table", "tcpwrap-hosts-allow-table"},
		Desc: "allow table path", PathValue: true,
		Scope: AddressScope{Caps: capRange},
	},
	{Canonical: "hosts-deny", Aliases: []string{"deny-table", "tcpwrap-hosts-deny-table"},
		Desc: "deny table path", PathValue: true,
		Scope: AddressScope{Caps: capRange},
	},
}
