package optionmeta

var socketOptions = []Option{
	{Canonical: "nodelay", Kind: KindFlagInt, Aliases: []string{"tcp-nodelay"},
		Desc:  "send small TCP writes without delay",
		Scope: tcpStreamScope,
	},
	{Canonical: "keepalive", Kind: KindFlagInt, Aliases: []string{"so-keepalive"}, ParserAliases: []string{"tcp-keepalive"},
		Desc:  "enable socket keepalive probes",
		Scope: AddressScope{Caps: capSocket, AddressTypes: tcpStreamAddressTypes},
	},
	{Canonical: "keepidle", Kind: KindPositiveDuration, Aliases: []string{"so-keepidle", "tcp-keepidle"},
		Desc:  "idle time before TCP keepalive probes (requires keepalive)",
		Scope: tcpStreamScope,
	},
	{Canonical: "keepintvl", Kind: KindPositiveDuration, Aliases: []string{"so-keepintvl", "tcp-keepintvl"},
		Desc:  "interval between TCP keepalive probes",
		Scope: tcpStreamScope,
	},
	{Canonical: "keepcnt", Kind: KindKeepCnt, Aliases: []string{"so-keepcnt", "tcp-keepcnt"},
		Desc:  "number of unanswered TCP keepalive probes before failure",
		Scope: tcpStreamScope,
	},
	{Canonical: "broadcast", Kind: KindWordInt, Aliases: []string{"so-broadcast"},
		Desc:  "allow sending broadcast packets",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-debug", Kind: KindNamedWord, Aliases: []string{"debug"},
		Desc:  "enable socket debugging",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-dontroute", Kind: KindNamedWord, Aliases: []string{"dontroute"},
		Desc:  "send packets directly without routing through a gateway",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-oobinline", Kind: KindNamedWord, Aliases: []string{"oobinline"},
		Desc:  "include urgent data in the normal receive stream",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-rcvlowat", Kind: KindNamedInt, Aliases: []string{"rcvlowat"},
		Desc:      "receive low-water mark in bytes",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-sndlowat", Kind: KindNamedInt, Aliases: []string{"sndlowat"},
		Desc:      "send low-water mark in bytes",
		Advertise: AdvertiseDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-priority", Kind: KindNamedInt, Aliases: []string{"priority"},
		Desc:      "outgoing packet priority (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-passcred", Kind: KindNamedInt, Aliases: []string{"passcred"},
		Desc:      "receive sender credentials (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-no-check", Kind: KindNamedInt, Aliases: []string{"no-check", "nocheck"},
		Desc:      "disable outgoing UDP checksums (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-detach-filter", Kind: KindNamedInt, Aliases: []string{"detach-filter", "detachfilter"},
		Desc:      "remove the socket packet filter (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "fiosetown", Kind: KindNamedCInt,
		Desc:      "process ID receiving asynchronous socket notifications",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "siocspgrp", Kind: KindNamedCInt,
		Desc:      "process group receiving asynchronous socket notifications",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "tcp-cork", Kind: KindNamedWord, Aliases: []string{"cork"},
		Desc:      "defer sending partial TCP segments (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-defer-accept", Kind: KindNamedInt, Aliases: []string{"defer-accept"},
		Desc:      "wait for data before accepting TCP, in seconds (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-linger2", Kind: KindNamedInt, Aliases: []string{"linger2"},
		Desc:      "TCP FIN-WAIT-2 timeout in seconds (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-maxseg", Kind: KindNamedInt, Aliases: []string{"maxseg", "mss"},
		Desc:      "maximum TCP segment size before connection",
		Advertise: AdvertiseLinuxDarwin, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-maxseg-late", Kind: KindNamedInt, Aliases: []string{"maxseg-late", "mss-late"},
		Desc:      "maximum TCP segment size after connection or accept",
		Advertise: AdvertiseLinuxDarwin, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-quickack", Kind: KindNamedInt, Aliases: []string{"quickack"},
		Desc:      "acknowledge TCP packets promptly (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-syncnt", Kind: KindNamedInt, Aliases: []string{"syncnt"},
		Desc:      "number of TCP connection-request retries (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "tcp-window-clamp", Kind: KindNamedInt, Aliases: []string{"window-clamp"},
		Desc:      "maximum advertised TCP receive window (Linux)",
		Advertise: AdvertiseLinux, Scope: tcpStreamScope,
	},
	{Canonical: "nopush", Kind: KindNamedWord, Aliases: []string{"tcp-nopush"},
		Desc:      "defer sending partial TCP segments (macOS)",
		Advertise: AdvertiseDarwin, Scope: tcpStreamScope,
	},
	{Canonical: "noopt", Kind: KindNamedWord, Aliases: []string{"tcp-noopt"},
		Desc:      "disable TCP options (macOS)",
		Advertise: AdvertiseDarwin, Scope: tcpStreamScope,
	},
	{Canonical: "sctp-nodelay", Kind: KindNamedWord,
		Desc:      "send small SCTP writes without delay (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSCTP, ImplGroups: []string{GroupSCTP}},
	},
	{Canonical: "sctp-maxseg", Kind: KindNamedInt,
		Desc:      "maximum SCTP fragment size before connection",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capSCTP, ImplGroups: []string{GroupSCTP}},
	},
	{Canonical: "ip-add-membership", Kind: KindMcastJoin4, Aliases: []string{"add-membership", "ip-membership", "membership"},
		Desc:      "join an IPv4 multicast group",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ipv6-join-group", Kind: KindMcastJoin6, Aliases: []string{"ipv6-add-membership", "join-group"},
		Desc:      "join an IPv6 multicast group",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ip-multicast-if", Kind: KindMcastIf, Aliases: []string{"multicast-if"},
		Desc:      "outgoing IPv4 multicast interface",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-multicast-loop", Kind: KindMcastLoop4, Aliases: []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"},
		Desc:      "loop outgoing IPv4 multicast packets back locally",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-multicast-ttl", Kind: KindMcastTTL, Aliases: []string{"multicast-ttl", "ipmulticastttl", "multicastttl"},
		Desc:      "outgoing IPv4 multicast TTL",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ipv6-multicast-loop", Kind: KindMcastLoop6, Aliases: []string{"ipv6-mcloop", "mcloop6"},
		Desc:      "loop outgoing IPv6 multicast packets back locally",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ip-mtu-discover", Kind: KindMTUDiscover, Aliases: []string{"mtudiscover", "ipmtudiscover"},
		Desc:      "IPv4 path MTU discovery policy",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ipv6-mtu-discover", Kind: KindMTUDiscover, Aliases: []string{"mtudiscover6"},
		Desc:      "IPv6 path MTU discovery policy",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-add-source-membership", Kind: KindMcastSource4, Aliases: []string{"add-source-membership", "source-membership"},
		Desc:      "join an IPv4 multicast group for one source",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ipv6-join-source-group", Kind: KindMcastSource6, Aliases: []string{"ipv6-add-source-membership", "join-source-group"},
		Desc:      "join an IPv6 multicast group for one source",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ip-freebind", Kind: KindWordInt, Aliases: []string{"freebind", "ipfreebind"},
		Desc:      "allow binding a nonlocal IPv4 address (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-transparent", Kind: KindTransparent, Aliases: []string{"transparent"},
		Desc:      "allow transparent proxy binding (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-router-alert", Kind: KindRouterAlert, Aliases: []string{"iprouteralert", "routeralert"},
		Desc:      "receive IPv4 Router Alert packets (Linux raw sockets; protocol 255 excluded)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6, ImplGroups: []string{GroupRawIP}},
	},
	{Canonical: "setsockopt", Kind: KindSockoptDalan, Aliases: []string{"sockopt"},
		Desc:  "set a socket option after connection (dalan value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-int", Kind: KindSockoptInt, Aliases: []string{"sockopt-int"},
		Desc:  "set a socket option after connection (integer value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-bin", Kind: KindSockoptDalan, Aliases: []string{"sockopt-bin"},
		Desc:  "set a socket option after connection (binary value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-string", Kind: KindSockoptString, Aliases: []string{"sockopt-string"},
		Desc:  "set a socket option after connection (string value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-listen", Kind: KindSockoptDalan, Aliases: []string{"sockopt-listen"},
		Desc:  "set a socket option before binding (dalan value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-socket", Kind: KindSockoptDalan, Aliases: []string{"sockopt-sock"},
		Desc:  "set a socket option before binding or connecting (dalan value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "setsockopt-connected", Kind: KindSockoptDalan, Aliases: []string{"sockopt-conn"},
		Desc:  "set a socket option after connection (dalan value)",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "so-timestamp", Kind: KindAncillary, Aliases: []string{"timestamp"},
		Desc:      "include receive timestamps with packets",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "ip-pktinfo", Kind: KindAncillary, Aliases: []string{"pktinfo", "ippktinfo"},
		Desc:      "include IPv4 destination and interface information with packets",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recvttl", Kind: KindAncillary, Aliases: []string{"recvttl", "iprecvttl"},
		Desc:      "include received IPv4 packet TTL",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recvtos", Kind: KindAncillary, Aliases: []string{"recvtos", "iprecvtos"},
		Desc:      "include received IPv4 packet type of service",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recvopts", Kind: KindAncillary, Aliases: []string{"recvopts", "iprecvopts"},
		Desc:      "include received IPv4 header options",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recverr", Kind: KindRecvErr, Aliases: []string{"recverr", "iprecverr"},
		Desc:      "receive extended IPv4 network errors (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-retopts", Kind: KindAncillary, Aliases: []string{"retopts", "ipretopts"},
		Desc:      "include IPv4 return options with received packets (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recvdstaddr", Kind: KindAncillary, Aliases: []string{"recvdstaddr", "iprecvdstaddr"},
		Desc:      "include received IPv4 destination address (macOS)",
		Advertise: AdvertiseDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-recvif", Kind: KindAncillary, Aliases: []string{"recvif"},
		Desc:      "include received IPv4 interface information (macOS)",
		Advertise: AdvertiseDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-ttl", Kind: KindAncillary, Aliases: []string{"ttl", "ipttl"},
		Desc:  "outgoing IPv4 packet TTL",
		Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-tos", Kind: KindAncillary, Aliases: []string{"tos", "iptos"},
		Desc:  "outgoing IPv4 packet type of service",
		Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-options", Kind: KindIPOptions, Aliases: []string{"ipoptions"},
		Desc:      "outgoing IPv4 header options",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ip-hdrincl", Kind: KindAncillary, Aliases: []string{"hdrincl", "iphdrincl"},
		Desc:      "include your own IPv4 header on raw packets",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP4IP6},
	},
	{Canonical: "ipv6-recvpktinfo", Kind: KindAncillary, Aliases: []string{"recvpktinfo"},
		Desc:      "include IPv6 destination and interface information with packets",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvhoplimit", Kind: KindAncillary, Aliases: []string{"recvhoplimit"},
		Desc:      "include received IPv6 hop limit",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvtclass", Kind: KindAncillary, Aliases: []string{"recvtclass"},
		Desc:      "include received IPv6 traffic class",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvdstopts", Kind: KindAncillary, Aliases: []string{"recvdstopts"},
		Desc:      "include received IPv6 destination options (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvhopopts", Kind: KindAncillary, Aliases: []string{"recvhopopts"},
		Desc:      "include received IPv6 hop-by-hop options (Linux)",
		Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvrthdr", Kind: KindAncillary, Aliases: []string{"recvrthdr"},
		Desc:      "include received IPv6 routing headers",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-recvpathmtu", Kind: KindAncillary,
		Desc:      "receive IPv6 path MTU updates",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-unicast-hops", Kind: KindAncillary, Aliases: []string{"unicast-hops"},
		Desc:      "outgoing IPv6 unicast hop limit",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "ipv6-tclass", Kind: KindAncillary, Aliases: []string{"tclass"},
		Desc:      "outgoing IPv6 traffic class",
		Advertise: AdvertiseLinuxDarwin, Scope: AddressScope{Caps: capIP6},
	},
	{Canonical: "res-nsaddr", Kind: KindResNS, Aliases: []string{"dns", "nameserver", "nsaddr"},
		Desc:  "per-address IPv4 DNS nameserver host[:port]",
		Scope: resolverScope,
	},
	{Canonical: "res-usevc", Kind: KindBool, Aliases: []string{"usevc"},
		Desc:  "per-address DNS over TCP; =0 restores UDP then TCP even if resolv.conf has use-vc",
		Scope: resolverScope,
	},
	{Canonical: "rcvtimeo", Kind: KindTimeout, Aliases: []string{"so-rcvtimeo"},
		Desc:  "per-operation socket receive timeout; retry after expiration",
		Scope: socketTimeoutScope,
	},
	{Canonical: "sndtimeo", Kind: KindTimeout, Aliases: []string{"so-sndtimeo"},
		Desc:  "per-operation socket send timeout; retry after expiration",
		Scope: socketTimeoutScope,
	},
	{Canonical: "so-linger", Kind: KindLinger, PublicAliases: []string{"linger"},
		Desc:  "socket close timeout in seconds",
		Scope: socketTimeoutScope,
	},
	{Canonical: "sndbuf", Kind: KindBuffer, Aliases: []string{"so-sndbuf"},
		Desc:  "socket send buffer size in bytes",
		Scope: socketTimeoutScope,
	},
	{Canonical: "rcvbuf", Kind: KindBuffer, Aliases: []string{"so-rcvbuf"},
		Desc:  "socket receive buffer size in bytes",
		Scope: socketTimeoutScope,
	},
	{Canonical: "sndbuf-late", Kind: KindBuffer, Aliases: []string{"so-sndbuf-late"},
		Desc:  "socket send buffer size after connect, accept, or bind",
		Scope: socketTimeoutScope,
	},
	{Canonical: "rcvbuf-late", Kind: KindBuffer, Aliases: []string{"so-rcvbuf-late"},
		Desc:  "socket receive buffer size after connect, accept, or bind",
		Scope: socketTimeoutScope,
	},
	{Canonical: "bindtodevice", Kind: KindBindDevice, Aliases: []string{"so-bindtodevice", "if", "interface"},
		Desc:      "restrict socket traffic to this interface",
		Advertise: AdvertiseLinux, Scope: socketTimeoutScope,
	},
	{Canonical: "so-protocol", Kind: KindSocketInt, Aliases: []string{"so-prototype", "prototype"},
		Desc:  "socket protocol number",
		Scope: AddressScope{Caps: capSocket, ImplGroups: []string{GroupSocket, GroupVSOCK}},
	},
}
