package optionmeta

// Socket, IP, and TCP options.
var socketDefs = []Def{
	// Sockets
	{
		Canonical:     "nodelay",
		Section:       SectionSockets,
		PublicAliases: []string{"tcp-nodelay"},
		ParserAliases: []string{"tcp-nodelay"},
		Desc:          "TCP_NODELAY",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "keepalive",
		Section:       SectionSockets,
		PublicAliases: []string{"so-keepalive"},
		ParserAliases: []string{"so-keepalive", "tcp-keepalive"},
		Desc:          "SO_KEEPALIVE",
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "keepidle",
		Section:       SectionSockets,
		PublicAliases: []string{"so-keepidle", "tcp-keepidle"},
		ParserAliases: []string{"so-keepidle", "tcp-keepidle"},
		Desc:          "TCP_KEEPIDLE idle time (requires keepalive)",
		Value:         Duration,
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "keepintvl",
		Section:       SectionSockets,
		PublicAliases: []string{"so-keepintvl", "tcp-keepintvl"},
		ParserAliases: []string{"so-keepintvl", "tcp-keepintvl"},
		Desc:          "TCP_KEEPINTVL probe interval",
		Value:         Duration,
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "keepcnt",
		Section:       SectionSockets,
		PublicAliases: []string{"so-keepcnt", "tcp-keepcnt"},
		ParserAliases: []string{"so-keepcnt", "tcp-keepcnt"},
		Desc:          "TCP_KEEPCNT probe count",
		Value:         IntegerMin1,
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "broadcast",
		Section:       SectionSockets,
		PublicAliases: []string{"so-broadcast"},
		ParserAliases: []string{"so-broadcast"},
		Desc:          "SO_BROADCAST",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "so-debug",
		Section:       SectionSockets,
		PublicAliases: []string{"debug"},
		ParserAliases: []string{"debug"},
		Desc:          "SO_DEBUG",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "so-dontroute",
		Section:       SectionSockets,
		PublicAliases: []string{"dontroute"},
		ParserAliases: []string{"dontroute"},
		Desc:          "SO_DONTROUTE",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "so-oobinline",
		Section:       SectionSockets,
		PublicAliases: []string{"oobinline"},
		ParserAliases: []string{"oobinline"},
		Desc:          "SO_OOBINLINE",
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "so-rcvlowat",
		Section:       SectionSockets,
		PublicAliases: []string{"rcvlowat"},
		ParserAliases: []string{"rcvlowat"},
		Desc:          "SO_RCVLOWAT receive low-water mark",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "so-sndlowat",
		Section:       SectionSockets,
		PublicAliases: []string{"sndlowat"},
		ParserAliases: []string{"sndlowat"},
		Desc:          "SO_SNDLOWAT send low-water mark",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseDarwin,
	},
	{
		Canonical:     "so-priority",
		Section:       SectionSockets,
		PublicAliases: []string{"priority"},
		ParserAliases: []string{"priority"},
		Desc:          "SO_PRIORITY (Linux)",
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "so-passcred",
		Section:       SectionSockets,
		PublicAliases: []string{"passcred"},
		ParserAliases: []string{"passcred"},
		Desc:          "SO_PASSCRED (Linux)",
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "so-no-check",
		Section:       SectionSockets,
		PublicAliases: []string{"no-check", "nocheck"},
		ParserAliases: []string{"nocheck", "no-check"},
		Desc:          "SO_NO_CHECK (Linux)",
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "so-detach-filter",
		Section:       SectionSockets,
		PublicAliases: []string{"detach-filter", "detachfilter"},
		ParserAliases: []string{"detach-filter", "detachfilter"},
		Desc:          "SO_DETACH_FILTER (Linux)",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapSocket},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical: "fiosetown",
		Section:   SectionSockets,
		Desc:      "FIOSETOWN SIGIO owner pid",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: CapSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "siocspgrp",
		Section:   SectionSockets,
		Desc:      "SIOCSPGRP SIGIO process group",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: CapSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "tcp-cork",
		Section:       SectionSockets,
		PublicAliases: []string{"cork"},
		ParserAliases: []string{"cork"},
		Desc:          "TCP_CORK (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "tcp-defer-accept",
		Section:       SectionSockets,
		PublicAliases: []string{"defer-accept"},
		ParserAliases: []string{"defer-accept"},
		Desc:          "TCP_DEFER_ACCEPT seconds (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "tcp-linger2",
		Section:       SectionSockets,
		PublicAliases: []string{"linger2"},
		ParserAliases: []string{"linger2"},
		Desc:          "TCP_LINGER2 FIN_WAIT-2 timeout in seconds (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "tcp-maxseg",
		Section:       SectionSockets,
		PublicAliases: []string{"maxseg", "mss"},
		ParserAliases: []string{"maxseg", "mss"},
		Desc:          "TCP_MAXSEG after socket",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "tcp-maxseg-late",
		Section:       SectionSockets,
		PublicAliases: []string{"maxseg-late", "mss-late"},
		ParserAliases: []string{"maxseg-late", "mss-late"},
		Desc:          "TCP_MAXSEG after connect or accept",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "tcp-quickack",
		Section:       SectionSockets,
		PublicAliases: []string{"quickack"},
		ParserAliases: []string{"quickack"},
		Desc:          "TCP_QUICKACK (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "tcp-syncnt",
		Section:       SectionSockets,
		PublicAliases: []string{"syncnt"},
		ParserAliases: []string{"syncnt"},
		Desc:          "TCP_SYNCNT SYN retries (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "tcp-window-clamp",
		Section:       SectionSockets,
		PublicAliases: []string{"window-clamp"},
		ParserAliases: []string{"window-clamp"},
		Desc:          "TCP_WINDOW_CLAMP advertised window (Linux)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "nopush",
		Section:       SectionSockets,
		PublicAliases: []string{"tcp-nopush"},
		ParserAliases: []string{"tcp-nopush"},
		Desc:          "TCP_NOPUSH (Darwin)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseDarwin,
	},
	{
		Canonical:     "noopt",
		Section:       SectionSockets,
		PublicAliases: []string{"tcp-noopt"},
		ParserAliases: []string{"tcp-noopt"},
		Desc:          "TCP_NOOPT (Darwin)",
		Apply:         Applicability{Caps: CapIPTCP, TypeSet: TypesTCPStream},
		Advertise:     AdvertiseDarwin,
	},
	{
		Canonical: "sctp-nodelay",
		Section:   SectionSockets,
		Desc:      "SCTP_NODELAY (Linux)",
		Apply:     Applicability{Caps: CapSCTP, ImplGroups: []string{GroupSCTP}},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "sctp-maxseg",
		Section:   SectionSockets,
		Desc:      "SCTP_MAXSEG after socket",
		Apply:     Applicability{Caps: CapSCTP, ImplGroups: []string{GroupSCTP}},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical:     "ip-add-membership",
		Section:       SectionSockets,
		PublicAliases: []string{"add-membership", "ip-membership", "membership"},
		ParserAliases: []string{"add-membership", "ip-membership", "membership"},
		Desc:          "IPv4 multicast join (IP_ADD_MEMBERSHIP)",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ipv6-join-group",
		Section:       SectionSockets,
		PublicAliases: []string{"ipv6-add-membership", "join-group"},
		ParserAliases: []string{"ipv6-add-membership", "join-group"},
		Desc:          "IPv6 multicast join (IPV6_JOIN_GROUP)",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ip-multicast-if",
		Section:       SectionSockets,
		PublicAliases: []string{"multicast-if"},
		ParserAliases: []string{"multicast-if"},
		Desc:          "IPv4 multicast interface (IP_MULTICAST_IF)",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ip-multicast-loop",
		Section:       SectionSockets,
		PublicAliases: []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"},
		ParserAliases: []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"},
		Desc:          "multicast loopback (IP_MULTICAST_LOOP)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ip-multicast-ttl",
		Section:       SectionSockets,
		PublicAliases: []string{"multicast-ttl", "ipmulticastttl", "multicastttl"},
		ParserAliases: []string{"multicast-ttl", "ipmulticastttl", "multicastttl"},
		Desc:          "multicast TTL (IP_MULTICAST_TTL)",
		Value:         OptionalByte,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ipv6-multicast-loop",
		Section:       SectionSockets,
		PublicAliases: []string{"ipv6-mcloop", "mcloop6"},
		ParserAliases: []string{"ipv6-mcloop", "mcloop6"},
		Desc:          "IPv6 multicast loopback (IPV6_MULTICAST_LOOP)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ip-mtu-discover",
		Section:       SectionSockets,
		PublicAliases: []string{"mtudiscover", "ipmtudiscover"},
		ParserAliases: []string{"mtudiscover", "ipmtudiscover"},
		Desc:          "IPv4 path MTU discovery policy (IP_MTU_DISCOVER)",
		Value:         IntegerRange0_2,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "ipv6-mtu-discover",
		Section:       SectionSockets,
		PublicAliases: []string{"mtudiscover6"},
		ParserAliases: []string{"mtudiscover6"},
		Desc:          "IPv6 path MTU discovery policy (IPV6_MTU_DISCOVER)",
		Value:         IntegerRange0_2,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "ip-add-source-membership",
		Section:       SectionSockets,
		PublicAliases: []string{"add-source-membership", "source-membership"},
		ParserAliases: []string{"add-source-membership", "source-membership"},
		Desc:          "IPv4 source-specific multicast join (IP_ADD_SOURCE_MEMBERSHIP)",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ipv6-join-source-group",
		Section:       SectionSockets,
		PublicAliases: []string{"ipv6-add-source-membership", "join-source-group"},
		ParserAliases: []string{"ipv6-add-source-membership", "join-source-group"},
		Desc:          "IPv6 source-specific multicast join (MCAST_JOIN_SOURCE_GROUP)",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP6},
		Advertise:     AdvertiseLinuxDarwin,
	},
	{
		Canonical:     "ip-freebind",
		Section:       SectionSockets,
		PublicAliases: []string{"freebind", "ipfreebind"},
		ParserAliases: []string{"freebind", "ipfreebind"},
		Desc:          "IP_FREEBIND (Linux)",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "ip-transparent",
		Section:       SectionSockets,
		PublicAliases: []string{"transparent"},
		ParserAliases: []string{"transparent"},
		Desc:          "IP_TRANSPARENT before bind (Linux)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "ip-router-alert",
		Section:       SectionSockets,
		PublicAliases: []string{"iprouteralert", "routeralert"},
		ParserAliases: []string{"iprouteralert", "routeralert"},
		Desc:          "IP_ROUTER_ALERT (Linux raw IPv4; not IPPROTO_RAW)",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapIP4IP6, ImplGroups: []string{GroupRawIP}},
		Advertise:     AdvertiseLinux,
		Platform:      PlatformLinuxRemainingIPv4,
	},
	{
		Canonical:     "setsockopt",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt"},
		ParserAliases: []string{"sockopt"},
		Desc:          "raw setsockopt after connect (dalan value)",
		Value:         SockoptBin,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-int",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-int"},
		ParserAliases: []string{"sockopt-int"},
		Desc:          "raw setsockopt after connect (int value)",
		Value:         SockoptInt,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-bin",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-bin"},
		ParserAliases: []string{"sockopt-bin"},
		Desc:          "raw setsockopt after connect (binary value)",
		Value:         SockoptBin,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-string",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-string"},
		ParserAliases: []string{"sockopt-string"},
		Desc:          "raw setsockopt after connect (string value)",
		Value:         SockoptString,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-listen",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-listen"},
		ParserAliases: []string{"sockopt-listen"},
		Desc:          "raw setsockopt before bind (dalan value)",
		Value:         SockoptBin,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-socket",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-sock"},
		ParserAliases: []string{"sockopt-sock"},
		Desc:          "raw setsockopt after socket (dalan value)",
		Value:         SockoptBin,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "setsockopt-connected",
		Section:       SectionSockets,
		PublicAliases: []string{"sockopt-conn"},
		ParserAliases: []string{"sockopt-conn"},
		Desc:          "raw setsockopt after connect (dalan value)",
		Value:         SockoptBin,
		Apply:         Applicability{Caps: CapSocket},
	},
	{
		Canonical:     "so-timestamp",
		Section:       SectionSockets,
		PublicAliases: []string{"timestamp"},
		ParserAliases: []string{"timestamp"},
		Desc:          "SO_TIMESTAMP ancillary",
		Apply:         Applicability{Caps: CapSocket, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-pktinfo",
		Section:       SectionSockets,
		PublicAliases: []string{"pktinfo", "ippktinfo"},
		ParserAliases: []string{"pktinfo", "ippktinfo"},
		Desc:          "IP_PKTINFO",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recvttl",
		Section:       SectionSockets,
		PublicAliases: []string{"recvttl", "iprecvttl"},
		ParserAliases: []string{"recvttl", "iprecvttl"},
		Desc:          "IP_RECVTTL",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recvtos",
		Section:       SectionSockets,
		PublicAliases: []string{"recvtos", "iprecvtos"},
		ParserAliases: []string{"recvtos", "iprecvtos"},
		Desc:          "IP_RECVTOS",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recvopts",
		Section:       SectionSockets,
		PublicAliases: []string{"recvopts", "iprecvopts"},
		ParserAliases: []string{"recvopts", "iprecvopts"},
		Desc:          "IP_RECVOPTS",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recverr",
		Section:       SectionSockets,
		PublicAliases: []string{"recverr", "iprecverr"},
		ParserAliases: []string{"recverr", "iprecverr"},
		Desc:          "IP_RECVERR (Linux)",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6},
		Advertise:     AdvertiseLinux,
		Platform:      PlatformLinuxRecvErr,
	},
	{
		Canonical:     "ip-retopts",
		Section:       SectionSockets,
		PublicAliases: []string{"retopts", "ipretopts"},
		ParserAliases: []string{"retopts", "ipretopts"},
		Desc:          "IP_RETOPTS (Linux)",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinux,
		Platform:      PlatformLinuxRemainingIPv4,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recvdstaddr",
		Section:       SectionSockets,
		PublicAliases: []string{"recvdstaddr", "iprecvdstaddr"},
		ParserAliases: []string{"recvdstaddr", "iprecvdstaddr"},
		Desc:          "IP_RECVDSTADDR (Darwin)",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseDarwin,
		Platform:      PlatformDarwinIPRecv,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-recvif",
		Section:       SectionSockets,
		PublicAliases: []string{"recvif"},
		ParserAliases: []string{"recvif"},
		Desc:          "IP_RECVIF (Darwin)",
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseDarwin,
		Platform:      PlatformDarwinIPRecv,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-ttl",
		Section:       SectionSockets,
		PublicAliases: []string{"ttl", "ipttl"},
		ParserAliases: []string{"ipttl", "ttl"},
		Desc:          "IP_TTL",
		Value:         IntegerMinNeg1,
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Ancillary:     true,
	},
	{
		Canonical:     "ip-tos",
		Section:       SectionSockets,
		PublicAliases: []string{"tos", "iptos"},
		ParserAliases: []string{"iptos", "tos"},
		Desc:          "IP_TOS",
		Value:         Int64,
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Ancillary:     true,
	},
	{
		Canonical:     "ip-options",
		Section:       SectionSockets,
		PublicAliases: []string{"ipoptions"},
		ParserAliases: []string{"ipoptions"},
		Desc:          "IP_OPTIONS",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ip-hdrincl",
		Section:       SectionSockets,
		PublicAliases: []string{"hdrincl", "iphdrincl"},
		ParserAliases: []string{"hdrincl", "iphdrincl"},
		Desc:          "IP_HDRINCL (raw IPv4)",
		Value:         OptionalSignedInteger,
		Apply:         Applicability{Caps: CapIP4IP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvpktinfo",
		Section:       SectionSockets,
		PublicAliases: []string{"recvpktinfo"},
		ParserAliases: []string{"recvpktinfo"},
		Desc:          "IPV6_RECVPKTINFO",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvhoplimit",
		Section:       SectionSockets,
		PublicAliases: []string{"recvhoplimit"},
		ParserAliases: []string{"recvhoplimit"},
		Desc:          "IPV6_RECVHOPLIMIT",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvtclass",
		Section:       SectionSockets,
		PublicAliases: []string{"recvtclass"},
		ParserAliases: []string{"recvtclass"},
		Desc:          "IPV6_RECVTCLASS",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvdstopts",
		Section:       SectionSockets,
		PublicAliases: []string{"recvdstopts"},
		ParserAliases: []string{"recvdstopts"},
		Desc:          "IPV6_RECVDSTOPTS (Linux)",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinux,
		Platform:      PlatformLinuxIPv6RecvExt,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvhopopts",
		Section:       SectionSockets,
		PublicAliases: []string{"recvhopopts"},
		ParserAliases: []string{"recvhopopts"},
		Desc:          "IPV6_RECVHOPOPTS (Linux)",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinux,
		Platform:      PlatformLinuxIPv6RecvExt,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-recvrthdr",
		Section:       SectionSockets,
		PublicAliases: []string{"recvrthdr"},
		ParserAliases: []string{"recvrthdr"},
		Desc:          "IPV6_RECVRTHDR",
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical: "ipv6-recvpathmtu",
		Section:   SectionSockets,
		Desc:      "IPV6_RECVPATHMTU",
		Apply:     Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical:     "ipv6-unicast-hops",
		Section:       SectionSockets,
		PublicAliases: []string{"unicast-hops"},
		ParserAliases: []string{"unicast-hops"},
		Desc:          "IPV6_UNICAST_HOPS",
		Value:         IntegerMinNeg1,
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "ipv6-tclass",
		Section:       SectionSockets,
		PublicAliases: []string{"tclass"},
		ParserAliases: []string{"tclass"},
		Desc:          "IPV6_TCLASS",
		Value:         Int64,
		Apply:         Applicability{Caps: CapIP6, ImplSet: ImplAncillary},
		Advertise:     AdvertiseLinuxDarwin,
		Ancillary:     true,
	},
	{
		Canonical:     "res-nsaddr",
		Section:       SectionSockets,
		PublicAliases: []string{"dns", "nameserver", "nsaddr"},
		ParserAliases: []string{"dns", "nameserver", "nsaddr"},
		Desc:          "per-address IPv4 DNS nameserver host[:port]",
		Value:         ResNSAddr,
		Apply:         Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical:     "res-usevc",
		Section:       SectionSockets,
		PublicAliases: []string{"usevc"},
		ParserAliases: []string{"usevc"},
		Desc:          "per-address DNS over TCP (RES_USEVC); =0 restores UDP then TCP even if resolv.conf has use-vc",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical:     "rcvtimeo",
		Section:       SectionSockets,
		PublicAliases: []string{"so-rcvtimeo"},
		ParserAliases: []string{"so-rcvtimeo"},
		Desc:          "per-operation socket receive timeout; retry after expiration",
		Value:         Duration,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "sndtimeo",
		Section:       SectionSockets,
		PublicAliases: []string{"so-sndtimeo"},
		ParserAliases: []string{"so-sndtimeo"},
		Desc:          "per-operation socket send timeout; retry after expiration",
		Value:         Duration,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "so-linger",
		Section:       SectionSockets,
		PublicAliases: []string{"linger"},
		Desc:          "SO_LINGER timeout in seconds",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "sndbuf",
		Section:       SectionSockets,
		PublicAliases: []string{"so-sndbuf"},
		ParserAliases: []string{"so-sndbuf"},
		Desc:          "SO_SNDBUF size in bytes",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "rcvbuf",
		Section:       SectionSockets,
		PublicAliases: []string{"so-rcvbuf"},
		ParserAliases: []string{"so-rcvbuf"},
		Desc:          "SO_RCVBUF size in bytes",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "sndbuf-late",
		Section:       SectionSockets,
		PublicAliases: []string{"so-sndbuf-late"},
		ParserAliases: []string{"so-sndbuf-late"},
		Desc:          "SO_SNDBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "rcvbuf-late",
		Section:       SectionSockets,
		PublicAliases: []string{"so-rcvbuf-late"},
		ParserAliases: []string{"so-rcvbuf-late"},
		Desc:          "SO_RCVBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "bindtodevice",
		Section:       SectionSockets,
		PublicAliases: []string{"so-bindtodevice", "if", "interface"},
		ParserAliases: []string{"so-bindtodevice", "if", "interface"},
		Desc:          "SO_BINDTODEVICE interface name",
		Value:         RequiredString,
		Apply:         Applicability{Caps: CapSocket, TypeSet: TypesSocketTimeout},
		Advertise:     AdvertiseLinux,
	},
	{
		Canonical:     "so-protocol",
		Section:       SectionSockets,
		PublicAliases: []string{"so-prototype", "prototype"},
		ParserAliases: []string{"so-prototype", "prototype"},
		Desc:          "socket() protocol number",
		Value:         IntegerMinNeg1,
		Apply:         Applicability{Caps: CapSocket, ImplGroups: []string{GroupSocket, GroupVSOCK}},
	},
}
