package optionmeta

// Socket, IP, and TCP options.
var socketDefs = []Def{
	// Sockets
	{
		Canonical: "nodelay",
		Section:   SectionSockets,
		Aliases:   []string{"tcp-nodelay"},
		Desc:      "send small TCP writes without delay",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical:     "keepalive",
		Section:       SectionSockets,
		Aliases:       []string{"so-keepalive"},
		ParserAliases: []string{"tcp-keepalive"},
		Desc:          "enable socket keepalive probes",
		Apply:         Applicability{Caps: capSocket, TypeSet: TypesTCPStream},
	},
	{
		Canonical: "keepidle",
		Section:   SectionSockets,
		Aliases:   []string{"so-keepidle", "tcp-keepidle"},
		Desc:      "idle time before TCP keepalive probes (requires keepalive)",
		Value:     Duration,
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical: "keepintvl",
		Section:   SectionSockets,
		Aliases:   []string{"so-keepintvl", "tcp-keepintvl"},
		Desc:      "interval between TCP keepalive probes",
		Value:     Duration,
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical: "keepcnt",
		Section:   SectionSockets,
		Aliases:   []string{"so-keepcnt", "tcp-keepcnt"},
		Desc:      "number of unanswered TCP keepalive probes before failure",
		Value:     IntegerMin1,
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
	},
	{
		Canonical: "broadcast",
		Section:   SectionSockets,
		Aliases:   []string{"so-broadcast"},
		Desc:      "allow sending broadcast packets",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "so-debug",
		Section:   SectionSockets,
		Aliases:   []string{"debug"},
		Desc:      "enable socket debugging",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "so-dontroute",
		Section:   SectionSockets,
		Aliases:   []string{"dontroute"},
		Desc:      "send packets directly without routing through a gateway",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "so-oobinline",
		Section:   SectionSockets,
		Aliases:   []string{"oobinline"},
		Desc:      "include urgent data in the normal receive stream",
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "so-rcvlowat",
		Section:   SectionSockets,
		Aliases:   []string{"rcvlowat"},
		Desc:      "receive low-water mark in bytes",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "so-sndlowat",
		Section:   SectionSockets,
		Aliases:   []string{"sndlowat"},
		Desc:      "send low-water mark in bytes",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseDarwin,
	},
	{
		Canonical: "so-priority",
		Section:   SectionSockets,
		Aliases:   []string{"priority"},
		Desc:      "outgoing packet priority (Linux)",
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "so-passcred",
		Section:   SectionSockets,
		Aliases:   []string{"passcred"},
		Desc:      "receive sender credentials (Linux)",
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "so-no-check",
		Section:   SectionSockets,
		Aliases:   []string{"no-check", "nocheck"},
		Desc:      "disable outgoing UDP checksums (Linux)",
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "so-detach-filter",
		Section:   SectionSockets,
		Aliases:   []string{"detach-filter", "detachfilter"},
		Desc:      "remove the socket packet filter (Linux)",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "fiosetown",
		Section:   SectionSockets,
		Desc:      "process ID receiving asynchronous socket notifications",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "siocspgrp",
		Section:   SectionSockets,
		Desc:      "process group receiving asynchronous socket notifications",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capSocket},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "tcp-cork",
		Section:   SectionSockets,
		Aliases:   []string{"cork"},
		Desc:      "defer sending partial TCP segments (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "tcp-defer-accept",
		Section:   SectionSockets,
		Aliases:   []string{"defer-accept"},
		Desc:      "wait for data before accepting TCP, in seconds (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "tcp-linger2",
		Section:   SectionSockets,
		Aliases:   []string{"linger2"},
		Desc:      "TCP FIN-WAIT-2 timeout in seconds (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "tcp-maxseg",
		Section:   SectionSockets,
		Aliases:   []string{"maxseg", "mss"},
		Desc:      "maximum TCP segment size before connection",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "tcp-maxseg-late",
		Section:   SectionSockets,
		Aliases:   []string{"maxseg-late", "mss-late"},
		Desc:      "maximum TCP segment size after connection or accept",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "tcp-quickack",
		Section:   SectionSockets,
		Aliases:   []string{"quickack"},
		Desc:      "acknowledge TCP packets promptly (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "tcp-syncnt",
		Section:   SectionSockets,
		Aliases:   []string{"syncnt"},
		Desc:      "number of TCP connection-request retries (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "tcp-window-clamp",
		Section:   SectionSockets,
		Aliases:   []string{"window-clamp"},
		Desc:      "maximum advertised TCP receive window (Linux)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "nopush",
		Section:   SectionSockets,
		Aliases:   []string{"tcp-nopush"},
		Desc:      "defer sending partial TCP segments (macOS)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseDarwin,
	},
	{
		Canonical: "noopt",
		Section:   SectionSockets,
		Aliases:   []string{"tcp-noopt"},
		Desc:      "disable TCP options (macOS)",
		Apply:     Applicability{Caps: capIPTCP, TypeSet: TypesTCPStream},
		Advertise: AdvertiseDarwin,
	},
	{
		Canonical: "sctp-nodelay",
		Section:   SectionSockets,
		Desc:      "send small SCTP writes without delay (Linux)",
		Apply:     Applicability{Caps: capSCTP, ImplGroups: []string{GroupSCTP}},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "sctp-maxseg",
		Section:   SectionSockets,
		Desc:      "maximum SCTP fragment size before connection",
		Apply:     Applicability{Caps: capSCTP, ImplGroups: []string{GroupSCTP}},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ip-add-membership",
		Section:   SectionSockets,
		Aliases:   []string{"add-membership", "ip-membership", "membership"},
		Desc:      "join an IPv4 multicast group",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ipv6-join-group",
		Section:   SectionSockets,
		Aliases:   []string{"ipv6-add-membership", "join-group"},
		Desc:      "join an IPv6 multicast group",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ip-multicast-if",
		Section:   SectionSockets,
		Aliases:   []string{"multicast-if"},
		Desc:      "outgoing IPv4 multicast interface",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ip-multicast-loop",
		Section:   SectionSockets,
		Aliases:   []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"},
		Desc:      "loop outgoing IPv4 multicast packets back locally",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ip-multicast-ttl",
		Section:   SectionSockets,
		Aliases:   []string{"multicast-ttl", "ipmulticastttl", "multicastttl"},
		Desc:      "outgoing IPv4 multicast TTL",
		Value:     OptionalByte,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ipv6-multicast-loop",
		Section:   SectionSockets,
		Aliases:   []string{"ipv6-mcloop", "mcloop6"},
		Desc:      "loop outgoing IPv6 multicast packets back locally",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ip-mtu-discover",
		Section:   SectionSockets,
		Aliases:   []string{"mtudiscover", "ipmtudiscover"},
		Desc:      "IPv4 path MTU discovery policy",
		Value:     IntegerRange0_2,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ipv6-mtu-discover",
		Section:   SectionSockets,
		Aliases:   []string{"mtudiscover6"},
		Desc:      "IPv6 path MTU discovery policy",
		Value:     IntegerRange0_2,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ip-add-source-membership",
		Section:   SectionSockets,
		Aliases:   []string{"add-source-membership", "source-membership"},
		Desc:      "join an IPv4 multicast group for one source",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ipv6-join-source-group",
		Section:   SectionSockets,
		Aliases:   []string{"ipv6-add-source-membership", "join-source-group"},
		Desc:      "join an IPv6 multicast group for one source",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP6},
		Advertise: AdvertiseLinuxDarwin,
	},
	{
		Canonical: "ip-freebind",
		Section:   SectionSockets,
		Aliases:   []string{"freebind", "ipfreebind"},
		Desc:      "allow binding a nonlocal IPv4 address (Linux)",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ip-transparent",
		Section:   SectionSockets,
		Aliases:   []string{"transparent"},
		Desc:      "allow transparent proxy binding (Linux)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ip-router-alert",
		Section:   SectionSockets,
		Aliases:   []string{"iprouteralert", "routeralert"},
		Desc:      "receive IPv4 Router Alert packets (Linux raw sockets; protocol 255 excluded)",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capIP4IP6, ImplGroups: []string{GroupRawIP}},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "setsockopt",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt"},
		Desc:      "set a socket option after connection (dalan value)",
		Value:     SockoptBin,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-int",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-int"},
		Desc:      "set a socket option after connection (integer value)",
		Value:     SockoptInt,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-bin",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-bin"},
		Desc:      "set a socket option after connection (binary value)",
		Value:     SockoptBin,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-string",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-string"},
		Desc:      "set a socket option after connection (string value)",
		Value:     SockoptString,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-listen",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-listen"},
		Desc:      "set a socket option before binding (dalan value)",
		Value:     SockoptBin,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-socket",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-sock"},
		Desc:      "set a socket option before binding or connecting (dalan value)",
		Value:     SockoptBin,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "setsockopt-connected",
		Section:   SectionSockets,
		Aliases:   []string{"sockopt-conn"},
		Desc:      "set a socket option after connection (dalan value)",
		Value:     SockoptBin,
		Apply:     Applicability{Caps: capSocket},
	},
	{
		Canonical: "so-timestamp",
		Section:   SectionSockets,
		Aliases:   []string{"timestamp"},
		Desc:      "include receive timestamps with packets",
		Apply:     Applicability{Caps: capSocket, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-pktinfo",
		Section:   SectionSockets,
		Aliases:   []string{"pktinfo", "ippktinfo"},
		Desc:      "include IPv4 destination and interface information with packets",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-recvttl",
		Section:   SectionSockets,
		Aliases:   []string{"recvttl", "iprecvttl"},
		Desc:      "include received IPv4 packet TTL",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-recvtos",
		Section:   SectionSockets,
		Aliases:   []string{"recvtos", "iprecvtos"},
		Desc:      "include received IPv4 packet type of service",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-recvopts",
		Section:   SectionSockets,
		Aliases:   []string{"recvopts", "iprecvopts"},
		Desc:      "include received IPv4 header options",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-recverr",
		Section:   SectionSockets,
		Aliases:   []string{"recverr", "iprecverr"},
		Desc:      "receive extended IPv4 network errors (Linux)",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "ip-retopts",
		Section:   SectionSockets,
		Aliases:   []string{"retopts", "ipretopts"},
		Desc:      "include IPv4 return options with received packets (Linux)",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinux,
		Ancillary: true,
	},
	{
		Canonical: "ip-recvdstaddr",
		Section:   SectionSockets,
		Aliases:   []string{"recvdstaddr", "iprecvdstaddr"},
		Desc:      "include received IPv4 destination address (macOS)",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-recvif",
		Section:   SectionSockets,
		Aliases:   []string{"recvif"},
		Desc:      "include received IPv4 interface information (macOS)",
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-ttl",
		Section:   SectionSockets,
		Aliases:   []string{"ttl", "ipttl"},
		Desc:      "outgoing IPv4 packet TTL",
		Value:     IntegerMinNeg1,
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Ancillary: true,
	},
	{
		Canonical: "ip-tos",
		Section:   SectionSockets,
		Aliases:   []string{"tos", "iptos"},
		Desc:      "outgoing IPv4 packet type of service",
		Value:     Int64,
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Ancillary: true,
	},
	{
		Canonical: "ip-options",
		Section:   SectionSockets,
		Aliases:   []string{"ipoptions"},
		Desc:      "outgoing IPv4 header options",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ip-hdrincl",
		Section:   SectionSockets,
		Aliases:   []string{"hdrincl", "iphdrincl"},
		Desc:      "include your own IPv4 header on raw packets",
		Value:     OptionalSignedInteger,
		Apply:     Applicability{Caps: capIP4IP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvpktinfo",
		Section:   SectionSockets,
		Aliases:   []string{"recvpktinfo"},
		Desc:      "include IPv6 destination and interface information with packets",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvhoplimit",
		Section:   SectionSockets,
		Aliases:   []string{"recvhoplimit"},
		Desc:      "include received IPv6 hop limit",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvtclass",
		Section:   SectionSockets,
		Aliases:   []string{"recvtclass"},
		Desc:      "include received IPv6 traffic class",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvdstopts",
		Section:   SectionSockets,
		Aliases:   []string{"recvdstopts"},
		Desc:      "include received IPv6 destination options (Linux)",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinux,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvhopopts",
		Section:   SectionSockets,
		Aliases:   []string{"recvhopopts"},
		Desc:      "include received IPv6 hop-by-hop options (Linux)",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinux,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvrthdr",
		Section:   SectionSockets,
		Aliases:   []string{"recvrthdr"},
		Desc:      "include received IPv6 routing headers",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-recvpathmtu",
		Section:   SectionSockets,
		Desc:      "receive IPv6 path MTU updates",
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-unicast-hops",
		Section:   SectionSockets,
		Aliases:   []string{"unicast-hops"},
		Desc:      "outgoing IPv6 unicast hop limit",
		Value:     IntegerMinNeg1,
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "ipv6-tclass",
		Section:   SectionSockets,
		Aliases:   []string{"tclass"},
		Desc:      "outgoing IPv6 traffic class",
		Value:     Int64,
		Apply:     Applicability{Caps: capIP6, ImplSet: ImplAncillary},
		Advertise: AdvertiseLinuxDarwin,
		Ancillary: true,
	},
	{
		Canonical: "res-nsaddr",
		Section:   SectionSockets,
		Aliases:   []string{"dns", "nameserver", "nsaddr"},
		Desc:      "per-address IPv4 DNS nameserver host[:port]",
		Value:     ResNSAddr,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "res-usevc",
		Section:   SectionSockets,
		Aliases:   []string{"usevc"},
		Desc:      "per-address DNS over TCP; =0 restores UDP then TCP even if resolv.conf has use-vc",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capIP4IP6, TypeSet: TypesResolver, ImplSet: ImplResolver},
	},
	{
		Canonical: "rcvtimeo",
		Section:   SectionSockets,
		Aliases:   []string{"so-rcvtimeo"},
		Desc:      "per-operation socket receive timeout; retry after expiration",
		Value:     Duration,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "sndtimeo",
		Section:   SectionSockets,
		Aliases:   []string{"so-sndtimeo"},
		Desc:      "per-operation socket send timeout; retry after expiration",
		Value:     Duration,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical:     "so-linger",
		Section:       SectionSockets,
		PublicAliases: []string{"linger"},
		Desc:          "socket close timeout in seconds",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "sndbuf",
		Section:   SectionSockets,
		Aliases:   []string{"so-sndbuf"},
		Desc:      "socket send buffer size in bytes",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "rcvbuf",
		Section:   SectionSockets,
		Aliases:   []string{"so-rcvbuf"},
		Desc:      "socket receive buffer size in bytes",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "sndbuf-late",
		Section:   SectionSockets,
		Aliases:   []string{"so-sndbuf-late"},
		Desc:      "socket send buffer size after connect, accept, or bind",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "rcvbuf-late",
		Section:   SectionSockets,
		Aliases:   []string{"so-rcvbuf-late"},
		Desc:      "socket receive buffer size after connect, accept, or bind",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
	},
	{
		Canonical: "bindtodevice",
		Section:   SectionSockets,
		Aliases:   []string{"so-bindtodevice", "if", "interface"},
		Desc:      "restrict socket traffic to this interface",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capSocket, TypeSet: TypesSocketTimeout},
		Advertise: AdvertiseLinux,
	},
	{
		Canonical: "so-protocol",
		Section:   SectionSockets,
		Aliases:   []string{"so-prototype", "prototype"},
		Desc:      "socket protocol number",
		Value:     IntegerMinNeg1,
		Apply:     Applicability{Caps: capSocket, ImplGroups: []string{GroupSocket, GroupVSOCK}},
	},
}
