package optionmeta

var terminalOptions = []Option{
	{Canonical: "link", Kind: KindLink, Aliases: []string{"symbolic-link"},
		Desc: "symlink to the PTY slave", PathValue: true,
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "raw", Kind: KindNoValueName,
		Desc:  "obsolete raw termios mode",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "cfmakeraw", Kind: KindNoValueName, Aliases: []string{"termios-cfmakeraw"},
		Desc:  "raw terminal mode without echo or character processing",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "rawer", Kind: KindNoValueName, Aliases: []string{"termios-rawer"},
		Desc:  "stricter raw termios",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "sane", Kind: KindNoValueName,
		Desc:  "reset termios to sane defaults",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echo", Kind: KindBool,
		Desc:  "terminal echo",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoe", Kind: KindBool, Aliases: []string{"crterase"},
		Desc:  "erase the previous character when echoing erase",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoke", Kind: KindBool, Aliases: []string{"crtkill"},
		Desc:  "erase the current line when echoing kill",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoctl", Kind: KindBool, Aliases: []string{"ctlecho"},
		Desc:  "echo control characters in caret notation",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "hupcl", Kind: KindBool, Aliases: []string{"hup"},
		Desc:  "hang up the terminal on last close",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ixoff", Kind: KindBool, Aliases: []string{"tandem"},
		Desc:  "enable software flow control for input",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "opost", Kind: KindBool,
		Desc:  "output post-processing",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ispeed", Kind: KindTermiosUint,
		Desc:  "input baud",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ospeed", Kind: KindTermiosUint,
		Desc:  "output baud",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "tiocswinsz", Kind: KindWinSize, Aliases: []string{"winsz"},
		Desc:  "window size cols:rows",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "pty-wait-slave", Kind: KindBool, Aliases: []string{"wait-slave", "waitslave"},
		Desc:  "wait until the slave is open",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "pty-interval", Kind: KindDuration, Aliases: []string{"pty-intervall"},
		Desc:  "poll interval while waiting for slave",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "sitout-eio", Kind: KindSitout,
		Desc:  "wait this long on PTY master EIO after the slave closes",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "ctty", Kind: KindBool, Aliases: []string{"tiocsctty"},
		Desc:  "make the PTY the controlling tty",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ptmx", Kind: KindBool,
		Desc:  "run on a pseudo-terminal via /dev/ptmx",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "openpty", Kind: KindBool,
		Desc:  "run on a pseudo-terminal",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "escape", Kind: KindEscape,
		Desc: "escape character",
	},
}

var terminalAliases = []Option{
	{Canonical: "termios-setflags", Kind: KindTermiosFlags, ParserAliases: []string{"setflags"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoprt", Kind: KindBool, ParserAliases: []string{"prterase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vintr", Kind: KindTermiosByte, ParserAliases: []string{"intr"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vquit", Kind: KindTermiosByte, ParserAliases: []string{"quit"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "verase", Kind: KindTermiosByte, ParserAliases: []string{"erase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vkill", Kind: KindTermiosByte, ParserAliases: []string{"kill"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veof", Kind: KindTermiosByte, ParserAliases: []string{"eof"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veol", Kind: KindTermiosByte, ParserAliases: []string{"eol"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veol2", Kind: KindTermiosByte, ParserAliases: []string{"eol2"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vmin", Kind: KindTermiosByte, ParserAliases: []string{"min"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vtime", Kind: KindTermiosByte, ParserAliases: []string{"time"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vstart", Kind: KindTermiosByte, ParserAliases: []string{"start"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vstop", Kind: KindTermiosByte, ParserAliases: []string{"stop"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vsusp", Kind: KindTermiosByte, ParserAliases: []string{"susp"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vwerase", Kind: KindTermiosByte, ParserAliases: []string{"werase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vlnext", Kind: KindTermiosByte, ParserAliases: []string{"lnext"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vdiscard", Kind: KindTermiosByte, ParserAliases: []string{"discard"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vreprint", Kind: KindTermiosByte, ParserAliases: []string{"reprint", "rprnt"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vswtc", Kind: KindTermiosByte, ParserAliases: []string{"swtc", "swtch"},
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "iuclc", Kind: KindBool,
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "olcuc", Kind: KindBool,
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "xcase", Kind: KindBool,
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "xtabs", Kind: KindNoValueName,
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "tabdly", Kind: KindTermiosField,
		Hidden: true, Advertise: AdvertiseLinux, Scope: AddressScope{Caps: capTermios},
	},
}
