package optionmeta

var terminalOptions = []Option{
	{Canonical: "link", Aliases: []string{"symbolic-link"},
		Desc: "symlink to the PTY slave", PathValue: true,
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "raw",
		Desc:  "obsolete raw termios mode",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "cfmakeraw", Aliases: []string{"termios-cfmakeraw"},
		Desc:  "raw terminal mode without echo or character processing",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "rawer", Aliases: []string{"termios-rawer"},
		Desc:  "stricter raw termios",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "sane",
		Desc:  "reset termios to sane defaults",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echo",
		Desc:  "terminal echo",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoe", Aliases: []string{"crterase"},
		Desc:  "erase the previous character when echoing erase",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoke", Aliases: []string{"crtkill"},
		Desc:  "erase the current line when echoing kill",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoctl", Aliases: []string{"ctlecho"},
		Desc:  "echo control characters in caret notation",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "hupcl", Aliases: []string{"hup"},
		Desc:  "hang up the terminal on last close",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ixoff", Aliases: []string{"tandem"},
		Desc:  "enable software flow control for input",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "opost",
		Desc:  "output post-processing",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ispeed",
		Desc:  "input baud",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ospeed",
		Desc:  "output baud",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "tiocswinsz", Aliases: []string{"winsz"},
		Desc:  "window size cols:rows",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "pty-wait-slave", Aliases: []string{"wait-slave", "waitslave"},
		Desc:  "wait until the slave is open",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "pty-interval", Aliases: []string{"pty-intervall"},
		Desc: "poll interval while waiting for slave", Value: Duration,
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "sitout-eio",
		Desc: "wait this long on PTY master EIO after the slave closes", Value: Duration,
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "ctty", Aliases: []string{"tiocsctty"},
		Desc:  "make the PTY the controlling tty",
		Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "ptmx",
		Desc:  "run on a pseudo-terminal via /dev/ptmx",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "openpty",
		Desc:  "run on a pseudo-terminal",
		Scope: AddressScope{Caps: capPTY},
	},
	{Canonical: "escape",
		Desc: "escape character",
	},
}

var terminalAliases = []Option{
	{Canonical: "termios-setflags", ParserAliases: []string{"setflags"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "echoprt", ParserAliases: []string{"prterase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vintr", ParserAliases: []string{"intr"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vquit", ParserAliases: []string{"quit"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "verase", ParserAliases: []string{"erase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vkill", ParserAliases: []string{"kill"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veof", ParserAliases: []string{"eof"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veol", ParserAliases: []string{"eol"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "veol2", ParserAliases: []string{"eol2"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vmin", ParserAliases: []string{"min"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vtime", ParserAliases: []string{"time"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vstart", ParserAliases: []string{"start"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vstop", ParserAliases: []string{"stop"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vsusp", ParserAliases: []string{"susp"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vwerase", ParserAliases: []string{"werase"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vlnext", ParserAliases: []string{"lnext"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vdiscard", ParserAliases: []string{"discard"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vreprint", ParserAliases: []string{"reprint", "rprnt"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
	{Canonical: "vswtc", ParserAliases: []string{"swtc", "swtch"},
		Hidden: true, Scope: AddressScope{Caps: capTermios},
	},
}
