package optionmeta

var tlsOptions = []Option{
	{Canonical: "cert", Aliases: []string{"certificate", "openssl-certificate"},
		Desc: "certificate file (PEM); required on listen", PathValue: true,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "key", Aliases: []string{"openssl-key"},
		Desc: "private key file (PEM)", PathValue: true,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "cafile", Aliases: []string{"ca", "openssl-cafile"},
		Desc: "CA file (PEM or DER)", PathValue: true,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "capath", Aliases: []string{"tls-capath", "openssl-capath"},
		Desc: "directory of CA certificates", PathValue: true,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "verify", Aliases: []string{"openssl-verify"},
		Desc:      "verify the peer (default on; 0 skips)",
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "commonname", Aliases: []string{"cn", "tls-commonname", "openssl-commonname"},
		Desc:      "name to check (empty skips the name check)",
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "snihost", Aliases: []string{"tls-snihost", "openssl-snihost"},
		Desc:      "TLS SNI host name",
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "nosni", Aliases: []string{"no-sni", "tls-no-sni", "openssl-no-sni"},
		Desc:      "do not send SNI",
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "ciphers", Aliases: []string{"cipher", "cipherlist", "openssl-cipherlist"},
		Desc: "TLS 1.2 cipher suite list", Value: RequiredString,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "openssl-compress", Aliases: []string{"compress"},
		Desc: "TLS compression policy (only none is supported)", Value: RequiredString,
		PublicTLS: true, TLSRejectReason: "Go crypto/tls has no TLS compression", Scope: tlsScope,
	},
	{Canonical: "openssl-min-proto-version", Aliases: []string{"min-proto-version", "min-version"},
		Desc: "minimum TLS or DTLS protocol version", Value: RequiredString,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "openssl-max-proto-version", Aliases: []string{"max-proto-version", "max-version"},
		Desc: "maximum TLS or DTLS protocol version", Value: RequiredString,
		PublicTLS: true, Scope: tlsScope,
	},
	{Canonical: "alpn",
		Desc:      "DTLS, QUIC, or HTTP/2/3 proxy ALPN",
		PublicTLS: true, Scope: AddressScope{AddressTypes: alpnAddressTypes},
	},
}
