package optionmeta

// TLS, DTLS, WebSocket, PROXY, and SOCKS options.
var tlsDefs = []Def{
	// TLS, DTLS, WSS, and QUIC
	{
		Canonical: "cert",
		Section:   SectionTLS,
		Aliases:   []string{"certificate", "openssl-certificate"},
		Desc:      "certificate file (PEM); required on listen",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
		PathValue: true,
	},
	{
		Canonical: "key",
		Section:   SectionTLS,
		Aliases:   []string{"openssl-key"},
		Desc:      "private key file (PEM)",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
		PathValue: true,
	},
	{
		Canonical: "cafile",
		Section:   SectionTLS,
		Aliases:   []string{"ca", "openssl-cafile"},
		Desc:      "CA file (PEM or DER)",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
		PathValue: true,
	},
	{
		Canonical: "capath",
		Section:   SectionTLS,
		Aliases:   []string{"tls-capath", "openssl-capath"},
		Desc:      "directory of CA certificates",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
		PathValue: true,
	},
	{
		Canonical: "verify",
		Section:   SectionTLS,
		Aliases:   []string{"openssl-verify"},
		Desc:      "verify the peer (default on; 0 skips)",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "commonname",
		Section:   SectionTLS,
		Aliases:   []string{"cn", "tls-commonname", "openssl-commonname"},
		Desc:      "name to check (empty skips the name check)",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "snihost",
		Section:   SectionTLS,
		Aliases:   []string{"tls-snihost", "openssl-snihost"},
		Desc:      "TLS SNI host name",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "nosni",
		Section:   SectionTLS,
		Aliases:   []string{"no-sni", "tls-no-sni", "openssl-no-sni"},
		Desc:      "do not send SNI",
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "ciphers",
		Section:   SectionTLS,
		Aliases:   []string{"cipher", "cipherlist", "openssl-cipherlist"},
		Desc:      "TLS 1.2 cipher suite list",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical:       "openssl-compress",
		Section:         SectionTLS,
		Aliases:         []string{"compress"},
		Desc:            "TLS compression policy (only none is supported)",
		Value:           RequiredString,
		Apply:           Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS:       true,
		TLSRejectReason: "Go crypto/tls has no TLS compression",
	},
	{
		Canonical: "openssl-min-proto-version",
		Section:   SectionTLS,
		Aliases:   []string{"min-proto-version", "min-version"},
		Desc:      "minimum TLS or DTLS protocol version",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "openssl-max-proto-version",
		Section:   SectionTLS,
		Aliases:   []string{"max-proto-version", "max-version"},
		Desc:      "maximum TLS or DTLS protocol version",
		Value:     RequiredString,
		Apply:     Applicability{Caps: capOpenSSL, AddressGroups: tlsAddressGroups(), TypeSet: TypesTLS},
		PublicTLS: true,
	},
	{
		Canonical: "alpn",
		Section:   SectionTLS,
		Desc:      "DTLS, QUIC, or HTTP/2/3 proxy ALPN",
		Apply:     Applicability{AddressGroups: tlsAddressGroups(), TypeSet: TypesALPN},
		PublicTLS: true,
	},
	// Datagram TLS
	{
		Canonical: "dtls-mtu",
		Section:   SectionDTLS,
		Desc:      "maximum UDP payload in bytes (256..65507, default 1200)",
		Value:     IntegerRange256_65507,
		Apply:     Applicability{TypeSet: TypesDTLS},
	},
	{
		Canonical: "dtls-migration",
		Section:   SectionDTLS,
		Desc:      "negotiate connection IDs and validated address migration (default on)",
		Value:     OptionalBool,
		Apply:     Applicability{TypeSet: TypesDTLS},
	},
	{
		Canonical: "dtls-unfragmented-probes",
		Section:   SectionDTLS,
		Desc:      "confirm and discover path MTU on a dedicated socket (default on with migration)",
		Value:     OptionalBool,
		Apply:     Applicability{TypeSet: TypesDTLS},
	},
	// WebSocket
	{
		Canonical: "path",
		Section:   SectionWebSocket,
		Desc:      "WebSocket URL path",
		Apply:     Applicability{Caps: capExec, AddressGroups: []string{GroupWebSocket}},
	},
	{
		Canonical: "origin",
		Section:   SectionWebSocket,
		Desc:      "WebSocket Origin header",
		Apply:     Applicability{AddressGroups: []string{GroupWebSocket}},
	},
	{
		Canonical: "protocol",
		Section:   SectionWebSocket,
		Desc:      "WebSocket subprotocol; VSOCK or SOCKET-* protocol number",
		Apply:     Applicability{Caps: capSocket, AddressGroups: []string{GroupWebSocket}, ImplGroups: []string{GroupWebSocket, GroupVSOCK, GroupSocket}},
	},
	// PROXY and SOCKS
	{
		Canonical: "proxyport",
		Section:   SectionProxy,
		Desc:      "HTTP proxy port",
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "http-version",
		Section:   SectionProxy,
		Desc:      "CONNECT HTTP version (1.0, 1.1, 2, 3)",
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "h2c",
		Section:   SectionProxy,
		Desc:      "cleartext HTTP/2 CONNECT",
		Apply:     Applicability{AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "ignorecr",
		Section:   SectionProxy,
		Desc:      "accept LF as HTTP CONNECT response line terminator",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "proxy-resolve",
		Section:   SectionProxy,
		Aliases:   []string{"resolve", "resolv"},
		Desc:      "resolve CONNECT target locally",
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "proxy-authorization",
		Section:   SectionProxy,
		Aliases:   []string{"proxyauth", "proxy-auth"},
		Desc:      "proxy basic auth user:pass",
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
	},
	{
		Canonical: "proxy-authorization-file",
		Section:   SectionProxy,
		Aliases:   []string{"proxyauthfile"},
		Desc:      "read proxy auth from a file",
		Apply:     Applicability{Caps: capHTTP, AddressGroups: []string{GroupProxy}, TypeSet: TypesProxy},
		PathValue: true,
	},
	{
		Canonical: "socksport",
		Section:   SectionProxy,
		Desc:      "SOCKS server port",
		Apply:     Applicability{Caps: capSocks, AddressGroups: []string{GroupProxy}, TypeSet: TypesSocks},
	},
	{
		Canonical: "socksuser",
		Section:   SectionProxy,
		Desc:      "SOCKS user name",
		Apply:     Applicability{Caps: capSocks, AddressGroups: []string{GroupProxy}, TypeSet: TypesSocks},
	},
	{
		Canonical: "sockspass",
		Section:   SectionProxy,
		Aliases:   []string{"sockspassword"},
		Desc:      "SOCKS password",
		Apply:     Applicability{Caps: capSocks, AddressGroups: []string{GroupProxy}, TypeSet: TypesSocks},
	},
}
