package optionmeta

var hiddenTLSOptions = []Option{
	{Canonical: "openssl-method", ParserAliases: []string{"opensslmethod", "method"},
		Value:           RequiredString,
		TLSRejectReason: "stream TLS only", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-fips", ParserAliases: []string{"fips"},
		Value:           OptionalBool,
		TLSRejectReason: "Go crypto/tls has no OpenSSL FIPS module", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-egd", ParserAliases: []string{"egd"},
		Value:           RequiredString,
		TLSRejectReason: "Go does not use EGD for randomness", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-pseudo", ParserAliases: []string{"pseudo"},
		Value:           OptionalBool,
		TLSRejectReason: "Go crypto/tls does not use OpenSSL pseudo-random bytes", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-dhparam", ParserAliases: []string{"openssl-dhparams", "dhparam", "dhparams", "dh"},
		Value:           RequiredString,
		TLSRejectReason: "Go crypto/tls does not load DH parameters", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-maxfraglen", ParserAliases: []string{"maxfraglen"},
		Value:           OptionalSignedInteger,
		TLSRejectReason: "Go crypto/tls has no max fragment length option", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-maxsendfrag", ParserAliases: []string{"maxsendfrag"},
		Value:           OptionalSignedInteger,
		TLSRejectReason: "Go crypto/tls has no max send fragment option", Hidden: true, Scope: hiddenTLSScope,
	},
}
