package optionmeta

var hiddenTLSOptions = []Option{
	{Canonical: "openssl-method", Kind: KindHiddenString, ParserAliases: []string{"opensslmethod", "method"},
		TLSRejectReason: "stream TLS only", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-fips", Kind: KindHiddenBool, ParserAliases: []string{"fips"},
		TLSRejectReason: "Go crypto/tls has no OpenSSL FIPS module", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-egd", Kind: KindHiddenString, ParserAliases: []string{"egd"},
		TLSRejectReason: "Go does not use EGD for randomness", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-pseudo", Kind: KindHiddenBool, ParserAliases: []string{"pseudo"},
		TLSRejectReason: "Go crypto/tls does not use OpenSSL pseudo-random bytes", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-dhparam", Kind: KindHiddenString, ParserAliases: []string{"openssl-dhparams", "dhparam", "dhparams", "dh"},
		TLSRejectReason: "Go crypto/tls does not load DH parameters", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-maxfraglen", Kind: KindHiddenInt, ParserAliases: []string{"maxfraglen"},
		TLSRejectReason: "Go crypto/tls has no max fragment length option", Hidden: true, Scope: hiddenTLSScope,
	},
	{Canonical: "openssl-maxsendfrag", Kind: KindHiddenInt, ParserAliases: []string{"maxsendfrag"},
		TLSRejectReason: "Go crypto/tls has no max send fragment option", Hidden: true, Scope: hiddenTLSScope,
	},
}
