package optionmeta

var transferOptions = []Option{
	{Canonical: "cr", Kind: KindNoValueSpell,
		Desc: "convert NL to/from CR",
	},
	{Canonical: "crnl", Kind: KindNoValueSpell, Aliases: []string{"crlf"},
		Desc: "convert CR/NL",
	},
	{Canonical: "crorlf", Kind: KindBool,
		Desc: "convert CR or LF",
	},
	{Canonical: "ignoreeof", Kind: KindBool, Aliases: []string{"ignoreof"},
		Desc: "do not close on EOF",
	},
	{Canonical: "null-eof", Kind: KindBool,
		Desc:  "treat a zero-length read as EOF",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "readbytes", Kind: KindSize, Aliases: []string{"bytes"},
		Desc: "read at most N bytes",
	},
	{Canonical: "lockfile", Kind: KindString,
		Desc: "create lock file or fail if it exists (like -L)",
	},
	{Canonical: "waitlock", Kind: KindString,
		Desc: "wait until lock file is gone, then create it (1s poll)",
	},
}
