package optionmeta

var transferOptions = []Option{
	{Canonical: "cr",
		Desc: "convert NL to/from CR",
	},
	{Canonical: "crnl", Aliases: []string{"crlf"},
		Desc: "convert CR/NL",
	},
	{Canonical: "crorlf",
		Desc: "convert CR or LF",
	},
	{Canonical: "ignoreeof", Aliases: []string{"ignoreof"},
		Desc: "do not close on EOF",
	},
	{Canonical: "null-eof",
		Desc:  "treat a zero-length read as EOF",
		Scope: AddressScope{Caps: capSocket},
	},
	{Canonical: "readbytes", Aliases: []string{"bytes"},
		Desc: "read at most N bytes",
	},
	{Canonical: "lockfile",
		Desc: "create lock file or fail if it exists (like -L)",
	},
	{Canonical: "waitlock",
		Desc: "wait until lock file is gone, then create it (1s poll)",
	},
}
