package optionmeta

var tunOptions = []Option{
	{Canonical: "tun-device",
		Desc:  "path to the TUN clone device",
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "tun-name",
		Desc:  "TUN/TAP interface name",
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "tun-type",
		Desc:  "tun or tap",
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-no-pi", Aliases: []string{"no-pi", "tun-no-pi"},
		Desc: "no packet information header", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-up", Aliases: []string{"up"},
		Desc: "bring the interface up", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-broadcast",
		Desc: "set the interface broadcast flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-debug",
		Desc: "enable interface debugging", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-loopback", Aliases: []string{"loopback"},
		Desc: "set the interface loopback flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-pointopoint", Aliases: []string{"pointopoint"},
		Desc: "set the interface point-to-point flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-running", Aliases: []string{"running"},
		Desc: "set the interface running flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-noarp", Aliases: []string{"noarp"},
		Desc: "disable address resolution on the interface", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-promisc", Aliases: []string{"promisc"},
		Desc: "enable interface promiscuous mode", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-allmulti", Aliases: []string{"allmulti"},
		Desc: "receive all multicast packets on the interface", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-multicast", Aliases: []string{"multicast"},
		Desc: "set the interface multicast flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-notrailers", Aliases: []string{"notrailers"},
		Desc: "set the interface no-trailers flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-master", Aliases: []string{"master"},
		Desc: "set the interface master flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-slave", Aliases: []string{"slave"},
		Desc: "set the interface slave flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-portsel", Aliases: []string{"portsel"},
		Desc: "set the interface port-selection flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "iff-automedia", Aliases: []string{"automedia"},
		Desc: "set the interface automatic-media flag", Value: OptionalBool,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "if-mtu", Aliases: []string{"interface-mtu"},
		Desc: "interface MTU", Value: PositiveInt64,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{Canonical: "retrieve-vlan",
		Desc: "restore stripped 802.1Q VLAN tags on INTERFACE packets", Value: NoValue,
		Scope: AddressScope{Caps: capInterface, AddressGroups: []string{GroupTUN}, AddressTypes: []string{"INTERFACE"}, RestrictTypes: true},
	},
}
