package optionmeta

// POSIX-MQ, TUN/INTERFACE, and namespace options.
var tunDefs = []Def{
	// POSIX message queues
	{
		Canonical: "mq-prio",
		Section:   SectionPOSIXMQ,
		Aliases:   []string{"posixmq-priority"},
		Desc:      "message priority",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical: "mq-flush",
		Section:   SectionPOSIXMQ,
		Aliases:   []string{"posixmq-flush"},
		Desc:      "drain the queue before use",
		Apply:     Applicability{Caps: capPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical: "mq-maxmsg",
		Section:   SectionPOSIXMQ,
		Aliases:   []string{"posixmq-maxmsg"},
		Desc:      "maximum number of messages in a new queue",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical: "mq-msgsize",
		Section:   SectionPOSIXMQ,
		Aliases:   []string{"posixmq-msgsize"},
		Desc:      "maximum message size in a new queue",
		Value:     IntegerMin0,
		Apply:     Applicability{Caps: capPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	// TUN and INTERFACE
	{
		Canonical: "tun-device",
		Section:   SectionTUN,
		Desc:      "path to the TUN clone device",
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "tun-name",
		Section:   SectionTUN,
		Desc:      "TUN/TAP interface name",
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "tun-type",
		Section:   SectionTUN,
		Desc:      "tun or tap",
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-no-pi",
		Section:   SectionTUN,
		Aliases:   []string{"no-pi", "tun-no-pi"},
		Desc:      "no packet information header",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-up",
		Section:   SectionTUN,
		Aliases:   []string{"up"},
		Desc:      "bring the interface up",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-broadcast",
		Section:   SectionTUN,
		Desc:      "set the interface broadcast flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-debug",
		Section:   SectionTUN,
		Desc:      "enable interface debugging",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-loopback",
		Section:   SectionTUN,
		Aliases:   []string{"loopback"},
		Desc:      "set the interface loopback flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-pointopoint",
		Section:   SectionTUN,
		Aliases:   []string{"pointopoint"},
		Desc:      "set the interface point-to-point flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-running",
		Section:   SectionTUN,
		Aliases:   []string{"running"},
		Desc:      "set the interface running flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-noarp",
		Section:   SectionTUN,
		Aliases:   []string{"noarp"},
		Desc:      "disable address resolution on the interface",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-promisc",
		Section:   SectionTUN,
		Aliases:   []string{"promisc"},
		Desc:      "enable interface promiscuous mode",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-allmulti",
		Section:   SectionTUN,
		Aliases:   []string{"allmulti"},
		Desc:      "receive all multicast packets on the interface",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-multicast",
		Section:   SectionTUN,
		Aliases:   []string{"multicast"},
		Desc:      "set the interface multicast flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-notrailers",
		Section:   SectionTUN,
		Aliases:   []string{"notrailers"},
		Desc:      "set the interface no-trailers flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-master",
		Section:   SectionTUN,
		Aliases:   []string{"master"},
		Desc:      "set the interface master flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-slave",
		Section:   SectionTUN,
		Aliases:   []string{"slave"},
		Desc:      "set the interface slave flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-portsel",
		Section:   SectionTUN,
		Aliases:   []string{"portsel"},
		Desc:      "set the interface port-selection flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-automedia",
		Section:   SectionTUN,
		Aliases:   []string{"automedia"},
		Desc:      "set the interface automatic-media flag",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "if-mtu",
		Section:   SectionTUN,
		Aliases:   []string{"interface-mtu"},
		Desc:      "interface MTU",
		Value:     PositiveInt64,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "retrieve-vlan",
		Section:   SectionTUN,
		Desc:      "restore stripped 802.1Q VLAN tags on INTERFACE packets",
		Value:     NoValue,
		Apply:     Applicability{Caps: capInterface, AddressGroups: []string{GroupTUN}, AddressTypes: []string{"INTERFACE"}, RestrictTypes: true},
	},
	// Namespaces
	{
		Canonical: "netns",
		Section:   SectionNamespaces,
		Desc:      "open this address in a Linux network namespace",
		Apply:     Applicability{Unrestricted: true},
	},
}
