package optionmeta

// POSIX-MQ, TUN/INTERFACE, and namespace options.
var tunDefs = []Def{
	// POSIX message queues
	{
		Canonical:     "mq-prio",
		Section:       SectionPOSIXMQ,
		PublicAliases: []string{"posixmq-priority"},
		ParserAliases: []string{"posixmq-priority"},
		Desc:          "message priority",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical:     "mq-flush",
		Section:       SectionPOSIXMQ,
		PublicAliases: []string{"posixmq-flush"},
		ParserAliases: []string{"posixmq-flush"},
		Desc:          "drain the queue before use",
		Apply:         Applicability{Caps: CapPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical:     "mq-maxmsg",
		Section:       SectionPOSIXMQ,
		PublicAliases: []string{"posixmq-maxmsg"},
		ParserAliases: []string{"posixmq-maxmsg"},
		Desc:          "mq_maxmsg",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	{
		Canonical:     "mq-msgsize",
		Section:       SectionPOSIXMQ,
		PublicAliases: []string{"posixmq-msgsize"},
		ParserAliases: []string{"posixmq-msgsize"},
		Desc:          "mq_msgsize",
		Value:         IntegerMin0,
		Apply:         Applicability{Caps: CapPOSIXMQ, AddressGroups: []string{GroupPOSIXMQ}},
	},
	// TUN and INTERFACE
	{
		Canonical: "tun-device",
		Section:   SectionTUN,
		Desc:      "path to the TUN clone device",
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "tun-name",
		Section:   SectionTUN,
		Desc:      "TUN/TAP interface name",
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "tun-type",
		Section:   SectionTUN,
		Desc:      "tun or tap",
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-no-pi",
		Section:       SectionTUN,
		PublicAliases: []string{"no-pi", "tun-no-pi"},
		ParserAliases: []string{"no-pi", "tun-no-pi"},
		Desc:          "no packet information header",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-up",
		Section:       SectionTUN,
		PublicAliases: []string{"up"},
		ParserAliases: []string{"up"},
		Desc:          "bring the interface up",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-broadcast",
		Section:   SectionTUN,
		Desc:      "IFF_BROADCAST",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "iff-debug",
		Section:   SectionTUN,
		Desc:      "IFF_DEBUG",
		Value:     OptionalBool,
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-loopback",
		Section:       SectionTUN,
		PublicAliases: []string{"loopback"},
		ParserAliases: []string{"loopback"},
		Desc:          "IFF_LOOPBACK",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-pointopoint",
		Section:       SectionTUN,
		PublicAliases: []string{"pointopoint"},
		ParserAliases: []string{"pointopoint"},
		Desc:          "IFF_POINTOPOINT",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-running",
		Section:       SectionTUN,
		PublicAliases: []string{"running"},
		ParserAliases: []string{"running"},
		Desc:          "IFF_RUNNING",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-noarp",
		Section:       SectionTUN,
		PublicAliases: []string{"noarp"},
		ParserAliases: []string{"noarp"},
		Desc:          "IFF_NOARP",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-promisc",
		Section:       SectionTUN,
		PublicAliases: []string{"promisc"},
		ParserAliases: []string{"promisc"},
		Desc:          "IFF_PROMISC",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-allmulti",
		Section:       SectionTUN,
		PublicAliases: []string{"allmulti"},
		ParserAliases: []string{"allmulti"},
		Desc:          "IFF_ALLMULTI",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-multicast",
		Section:       SectionTUN,
		PublicAliases: []string{"multicast"},
		ParserAliases: []string{"multicast"},
		Desc:          "IFF_MULTICAST",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-notrailers",
		Section:       SectionTUN,
		PublicAliases: []string{"notrailers"},
		ParserAliases: []string{"notrailers"},
		Desc:          "IFF_NOTRAILERS",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-master",
		Section:       SectionTUN,
		PublicAliases: []string{"master"},
		ParserAliases: []string{"master"},
		Desc:          "IFF_MASTER",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-slave",
		Section:       SectionTUN,
		PublicAliases: []string{"slave"},
		ParserAliases: []string{"slave"},
		Desc:          "IFF_SLAVE",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-portsel",
		Section:       SectionTUN,
		PublicAliases: []string{"portsel"},
		ParserAliases: []string{"portsel"},
		Desc:          "IFF_PORTSEL",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "iff-automedia",
		Section:       SectionTUN,
		PublicAliases: []string{"automedia"},
		ParserAliases: []string{"automedia"},
		Desc:          "IFF_AUTOMEDIA",
		Value:         OptionalBool,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical:     "if-mtu",
		Section:       SectionTUN,
		PublicAliases: []string{"interface-mtu"},
		ParserAliases: []string{"interface-mtu"},
		Desc:          "interface MTU",
		Value:         PositiveInt64,
		Apply:         Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}},
	},
	{
		Canonical: "retrieve-vlan",
		Section:   SectionTUN,
		Desc:      "restore 802.1Q from PACKET_AUXDATA on INTERFACE",
		Value:     NoValue,
		Apply:     Applicability{Caps: CapInterface, AddressGroups: []string{GroupTUN}, AddressTypes: []string{"INTERFACE"}, RestrictTypes: true},
	},
	// Namespaces
	{
		Canonical: "netns",
		Section:   SectionNamespaces,
		Desc:      "open this address in a Linux network namespace",
		Apply:     Applicability{Unrestricted: true},
	},
}
