package cli

import "github.com/oittaa/socat/internal/xio"

// Socket, IP, and TCP options.
func socketOptionGroups() []helpOptGroup {
	return []helpOptGroup{
		{"Sockets", []helpOpt{
			{name: "nodelay", optionCaps: capIPTCP, desc: "TCP_NODELAY", aliases: []string{"tcp-nodelay"}, addressTypes: tcpStreamAddressTypes()},
			{name: "keepalive", optionCaps: capSocket, desc: "SO_KEEPALIVE", aliases: []string{"so-keepalive"}, addressTypes: tcpStreamAddressTypes()},
			{name: "keepidle", optionCaps: capIPTCP, desc: "TCP_KEEPIDLE idle time (requires keepalive)", aliases: []string{"so-keepidle", "tcp-keepidle"}, addressTypes: tcpStreamAddressTypes(), validate: validateDurationOption},
			{name: "keepintvl", optionCaps: capIPTCP, desc: "TCP_KEEPINTVL probe interval", aliases: []string{"so-keepintvl", "tcp-keepintvl"}, addressTypes: tcpStreamAddressTypes(), validate: validateDurationOption},
			{name: "keepcnt", optionCaps: capIPTCP, desc: "TCP_KEEPCNT probe count", aliases: []string{"so-keepcnt", "tcp-keepcnt"}, addressTypes: tcpStreamAddressTypes(), validate: validateInteger(1)},
			{name: "broadcast", optionCaps: capSocket, desc: "SO_BROADCAST", aliases: []string{"so-broadcast"}},
			{name: "so-debug", optionCaps: capSocket, desc: "SO_DEBUG", aliases: []string{"debug"}},
			{name: "so-dontroute", optionCaps: capSocket, desc: "SO_DONTROUTE", aliases: []string{"dontroute"}},
			{name: "so-oobinline", optionCaps: capSocket, desc: "SO_OOBINLINE", aliases: []string{"oobinline"}},
			{name: "so-rcvlowat", optionCaps: capSocket, desc: "SO_RCVLOWAT receive low-water mark", aliases: []string{"rcvlowat"}, validate: validateOptionalSignedInteger},
			{name: "so-sndlowat", optionCaps: capSocket, desc: "SO_SNDLOWAT send low-water mark", aliases: []string{"sndlowat"}, validate: validateOptionalSignedInteger},
			{name: "so-priority", optionCaps: capSocket, desc: "SO_PRIORITY (Linux)", aliases: []string{"priority"}},
			{name: "so-passcred", optionCaps: capSocket, desc: "SO_PASSCRED (Linux)", aliases: []string{"passcred"}},
			{name: "so-no-check", optionCaps: capSocket, desc: "SO_NO_CHECK (Linux)", aliases: []string{"no-check", "nocheck"}},
			{name: "so-detach-filter", optionCaps: capSocket, desc: "SO_DETACH_FILTER (Linux)", aliases: []string{"detach-filter", "detachfilter"}, validate: validateOptionalSignedInteger},
			{name: "fiosetown", optionCaps: capSocket, desc: "FIOSETOWN SIGIO owner pid", validate: validateOptionalSignedInteger},
			{name: "siocspgrp", optionCaps: capSocket, desc: "SIOCSPGRP SIGIO process group", validate: validateOptionalSignedInteger},
			{name: "tcp-cork", optionCaps: capIPTCP, desc: "TCP_CORK (Linux)", aliases: []string{"cork"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-defer-accept", optionCaps: capIPTCP, desc: "TCP_DEFER_ACCEPT seconds (Linux)", aliases: []string{"defer-accept"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-linger2", optionCaps: capIPTCP, desc: "TCP_LINGER2 FIN_WAIT-2 timeout in seconds (Linux)", aliases: []string{"linger2"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-maxseg", optionCaps: capIPTCP, desc: "TCP_MAXSEG after socket", aliases: []string{"maxseg", "mss"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-maxseg-late", optionCaps: capIPTCP, desc: "TCP_MAXSEG after connect or accept", aliases: []string{"maxseg-late", "mss-late"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-quickack", optionCaps: capIPTCP, desc: "TCP_QUICKACK (Linux)", aliases: []string{"quickack"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-syncnt", optionCaps: capIPTCP, desc: "TCP_SYNCNT SYN retries (Linux)", aliases: []string{"syncnt"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-window-clamp", optionCaps: capIPTCP, desc: "TCP_WINDOW_CLAMP advertised window (Linux)", aliases: []string{"window-clamp"}, addressTypes: tcpStreamAddressTypes()},
			{name: "nopush", optionCaps: capIPTCP, desc: "TCP_NOPUSH (Darwin)", aliases: []string{"tcp-nopush"}, addressTypes: tcpStreamAddressTypes()},
			{name: "noopt", optionCaps: capIPTCP, desc: "TCP_NOOPT (Darwin)", aliases: []string{"tcp-noopt"}, addressTypes: tcpStreamAddressTypes()},
			{name: "sctp-nodelay", optionCaps: capSCTP, desc: "SCTP_NODELAY (Linux)", implementationGroups: []string{xio.GroupSCTP}},
			{name: "sctp-maxseg", optionCaps: capSCTP, desc: "SCTP_MAXSEG after socket", implementationGroups: []string{xio.GroupSCTP}},
			{name: "ip-add-membership", optionCaps: capIP4IP6, desc: "IPv4 multicast join (IP_ADD_MEMBERSHIP)", aliases: []string{"add-membership", "ip-membership", "membership"}, validate: validateRequiredString},
			{name: "ipv6-join-group", optionCaps: capIP6, desc: "IPv6 multicast join (IPV6_JOIN_GROUP)", aliases: []string{"ipv6-add-membership", "join-group"}, validate: validateRequiredString},
			{name: "ip-multicast-if", optionCaps: capIP4IP6, desc: "IPv4 multicast interface (IP_MULTICAST_IF)", aliases: []string{"multicast-if"}, validate: validateRequiredString},
			{name: "ip-multicast-loop", optionCaps: capIP4IP6, desc: "multicast loopback (IP_MULTICAST_LOOP)", aliases: []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"}, validate: validateOptionalBool},
			{name: "ip-multicast-ttl", optionCaps: capIP4IP6, desc: "multicast TTL (IP_MULTICAST_TTL)", aliases: []string{"multicast-ttl", "ipmulticastttl", "multicastttl"}, validate: validateOptionalByte},
			{name: "ipv6-multicast-loop", optionCaps: capIP6, desc: "IPv6 multicast loopback (IPV6_MULTICAST_LOOP)", aliases: []string{"ipv6-mcloop", "mcloop6"}, validate: validateOptionalBool},
			{name: "ip-mtu-discover", optionCaps: capIP4IP6, desc: "IPv4 path MTU discovery policy (IP_MTU_DISCOVER)", aliases: []string{"mtudiscover", "ipmtudiscover"}, validate: validateIntegerRange(0, 2)},
			{name: "ipv6-mtu-discover", optionCaps: capIP4IP6, desc: "IPv6 path MTU discovery policy (IPV6_MTU_DISCOVER)", aliases: []string{"mtudiscover6"}, validate: validateIntegerRange(0, 2)},
			{name: "ip-add-source-membership", optionCaps: capIP4IP6, desc: "IPv4 source-specific multicast join (IP_ADD_SOURCE_MEMBERSHIP)", aliases: []string{"add-source-membership", "source-membership"}, validate: validateRequiredString},
			{name: "ipv6-join-source-group", optionCaps: capIP6, desc: "IPv6 source-specific multicast join (MCAST_JOIN_SOURCE_GROUP)", aliases: []string{"ipv6-add-source-membership", "join-source-group"}, validate: validateRequiredString},
			{name: "ip-freebind", optionCaps: capIP4IP6, desc: "IP_FREEBIND (Linux)", aliases: []string{"freebind", "ipfreebind"}, validate: validateOptionalSignedInteger},
			{name: "ip-transparent", optionCaps: capIP4IP6, desc: "IP_TRANSPARENT before bind (Linux)", aliases: []string{"transparent"}, validate: validateOptionalBool},
			{name: "ip-router-alert", optionCaps: capIP4IP6, desc: "IP_ROUTER_ALERT (Linux raw IPv4; not IPPROTO_RAW)", aliases: []string{"iprouteralert", "routeralert"}, implementationGroups: []string{xio.GroupRawIP}, validate: validateOptionalSignedInteger},
			{name: "setsockopt", optionCaps: capSocket, desc: "raw setsockopt after connect (dalan value)", aliases: []string{"sockopt"}, validate: validateSockoptBin},
			{name: "setsockopt-int", optionCaps: capSocket, desc: "raw setsockopt after connect (int value)", aliases: []string{"sockopt-int"}, validate: validateSockoptInt},
			{name: "setsockopt-bin", optionCaps: capSocket, desc: "raw setsockopt after connect (binary value)", aliases: []string{"sockopt-bin"}, validate: validateSockoptBin},
			{name: "setsockopt-string", optionCaps: capSocket, desc: "raw setsockopt after connect (string value)", aliases: []string{"sockopt-string"}, validate: validateSockoptString},
			{name: "setsockopt-listen", optionCaps: capSocket, desc: "raw setsockopt before bind (dalan value)", aliases: []string{"sockopt-listen"}, validate: validateSockoptBin},
			{name: "setsockopt-socket", optionCaps: capSocket, desc: "raw setsockopt after socket (dalan value)", aliases: []string{"sockopt-sock"}, validate: validateSockoptBin},
			{name: "setsockopt-connected", optionCaps: capSocket, desc: "raw setsockopt after connect (dalan value)", aliases: []string{"sockopt-conn"}, validate: validateSockoptBin},
			{name: "so-timestamp", optionCaps: capSocket, desc: "SO_TIMESTAMP ancillary", aliases: []string{"timestamp"}, implementationGroups: xio.IPAncillaryImplementationGroups("so-timestamp")},
			{name: "ip-pktinfo", optionCaps: capIP4IP6, desc: "IP_PKTINFO", aliases: []string{"pktinfo", "ippktinfo"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-pktinfo")},
			{name: "ip-recvttl", optionCaps: capIP4IP6, desc: "IP_RECVTTL", aliases: []string{"recvttl", "iprecvttl"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvttl")},
			{name: "ip-recvtos", optionCaps: capIP4IP6, desc: "IP_RECVTOS", aliases: []string{"recvtos", "iprecvtos"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvtos")},
			{name: "ip-recvopts", optionCaps: capIP4IP6, desc: "IP_RECVOPTS", aliases: []string{"recvopts", "iprecvopts"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvopts")},
			{name: "ip-recverr", optionCaps: capIP4IP6, desc: "IP_RECVERR (Linux)", aliases: []string{"recverr", "iprecverr"}, validate: validateOptionalBool},
			{name: "ip-retopts", optionCaps: capIP4IP6, desc: "IP_RETOPTS (Linux)", aliases: []string{"retopts", "ipretopts"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-retopts")},
			{name: "ip-recvdstaddr", optionCaps: capIP4IP6, desc: "IP_RECVDSTADDR (Darwin)", aliases: []string{"recvdstaddr", "iprecvdstaddr"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvdstaddr")},
			{name: "ip-recvif", optionCaps: capIP4IP6, desc: "IP_RECVIF (Darwin)", aliases: []string{"recvif"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvif")},
			{name: "ip-ttl", optionCaps: capIP4IP6, desc: "IP_TTL", aliases: []string{"ttl", "ipttl"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-ttl"), validate: validateInteger(-1)},
			{name: "ip-tos", optionCaps: capIP4IP6, desc: "IP_TOS", aliases: []string{"tos", "iptos"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-tos"), validate: validateInt64(false)},
			{name: "ip-options", optionCaps: capIP4IP6, desc: "IP_OPTIONS", aliases: []string{"ipoptions"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-options"), validate: validateRequiredString},
			{name: "ip-hdrincl", optionCaps: capIP4IP6, desc: "IP_HDRINCL (raw IPv4)", aliases: []string{"hdrincl", "iphdrincl"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-hdrincl"), validate: validateOptionalSignedInteger},
			{name: "ipv6-recvpktinfo", optionCaps: capIP6, desc: "IPV6_RECVPKTINFO", aliases: []string{"recvpktinfo"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvpktinfo")},
			{name: "ipv6-recvhoplimit", optionCaps: capIP6, desc: "IPV6_RECVHOPLIMIT", aliases: []string{"recvhoplimit"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvhoplimit")},
			{name: "ipv6-recvtclass", optionCaps: capIP6, desc: "IPV6_RECVTCLASS", aliases: []string{"recvtclass"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvtclass")},
			{name: "ipv6-recvdstopts", optionCaps: capIP6, desc: "IPV6_RECVDSTOPTS (Linux)", aliases: []string{"recvdstopts"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvdstopts")},
			{name: "ipv6-recvhopopts", optionCaps: capIP6, desc: "IPV6_RECVHOPOPTS (Linux)", aliases: []string{"recvhopopts"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvhopopts")},
			{name: "ipv6-recvrthdr", optionCaps: capIP6, desc: "IPV6_RECVRTHDR", aliases: []string{"recvrthdr"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvrthdr")},
			{name: "ipv6-recvpathmtu", optionCaps: capIP6, desc: "IPV6_RECVPATHMTU", implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvpathmtu")},
			{name: "ipv6-unicast-hops", optionCaps: capIP6, desc: "IPV6_UNICAST_HOPS", aliases: []string{"unicast-hops"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-unicast-hops"), validate: validateInteger(-1)},
			{name: "ipv6-tclass", optionCaps: capIP6, desc: "IPV6_TCLASS", aliases: []string{"tclass"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-tclass"), validate: validateInt64(false)},
			{name: "res-nsaddr", optionCaps: capIP4IP6, desc: "per-address IPv4 DNS nameserver host[:port]", aliases: []string{"dns", "nameserver", "nsaddr"}, addressTypes: resolverAddressTypes(), implementationGroups: resolverImplementationGroups(), validate: validateResNSAddr},
			{name: "res-usevc", optionCaps: capIP4IP6, desc: "per-address DNS over TCP (RES_USEVC); =0 restores UDP then TCP even if resolv.conf has use-vc", aliases: []string{"usevc"}, addressTypes: resolverAddressTypes(), implementationGroups: resolverImplementationGroups(), validate: validateOptionalBool},
			{name: "rcvtimeo", optionCaps: capSocket, desc: "per-operation socket receive timeout; retry after expiration", aliases: []string{"so-rcvtimeo"}, addressTypes: socketTimeoutAddressTypes(), validate: validateDurationOption},
			{name: "sndtimeo", optionCaps: capSocket, desc: "per-operation socket send timeout; retry after expiration", aliases: []string{"so-sndtimeo"}, addressTypes: socketTimeoutAddressTypes(), validate: validateDurationOption},
			{name: "so-linger", optionCaps: capSocket, desc: "SO_LINGER timeout in seconds", aliases: []string{"linger"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "sndbuf", optionCaps: capSocket, desc: "SO_SNDBUF size in bytes", aliases: []string{"so-sndbuf"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "rcvbuf", optionCaps: capSocket, desc: "SO_RCVBUF size in bytes", aliases: []string{"so-rcvbuf"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "sndbuf-late", optionCaps: capSocket, desc: "SO_SNDBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)", aliases: []string{"so-sndbuf-late"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "rcvbuf-late", optionCaps: capSocket, desc: "SO_RCVBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)", aliases: []string{"so-rcvbuf-late"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "bindtodevice", optionCaps: capSocket, desc: "SO_BINDTODEVICE interface name", aliases: []string{"so-bindtodevice", "if", "interface"}, addressTypes: socketTimeoutAddressTypes(), validate: validateRequiredString},
			{name: "so-protocol", optionCaps: capSocket, desc: "socket() protocol number", aliases: []string{"so-prototype", "prototype"}, implementationGroups: []string{xio.GroupSocket, xio.GroupVSOCK}, validate: validateInteger(-1)},
		}},
	}
}
