package cli

// EXEC/SYSTEM/SHELL, PTY, and TERMIOS options.
func processOptionGroups() []helpOptGroup {
	return []helpOptGroup{
		{"EXEC, SYSTEM, SHELL", []helpOpt{
			{name: "pipes", optionCaps: capFork, desc: "connect with pipes"},
			{name: "pty", optionCaps: capFork, desc: "run on a pseudo-terminal"},
			{name: "setsid", unrestricted: true, desc: "new session", aliases: []string{"sid"}},
			{name: "dash", optionCaps: capExec, desc: "prefix EXEC argv[0] with '-' (login shell); unused on SYSTEM/SHELL", aliases: []string{"login"}},
			{name: "setpgid", optionCaps: capFork, desc: "set child process group; omitted/0/1 start a new group", aliases: []string{"pgid"}, validate: validateOptionalSignedInteger},
			{name: "sighup", optionCaps: capParent, desc: "pass SIGHUP to the EXEC/SYSTEM/SHELL child instead of exiting", validate: validateNoValue},
			{name: "sigint", optionCaps: capParent, desc: "pass SIGINT to the EXEC/SYSTEM/SHELL child instead of exiting", validate: validateNoValue},
			{name: "sigquit", optionCaps: capParent, desc: "pass SIGQUIT to the EXEC/SYSTEM/SHELL child instead of exiting", validate: validateNoValue},
			{name: "stderr", optionCaps: capFork, desc: "include child stderr"},
			{name: "fdin", optionCaps: capFork, desc: "child stdin fd number", validate: validateInteger(0)},
			{name: "fdout", optionCaps: capFork, desc: "child stdout fd number", validate: validateInteger(0)},
			{name: "shell", optionCaps: capShell, desc: "use a shell"},
			{name: "chdir", unrestricted: true, desc: "change directory before open or exec", aliases: []string{"cd"}, validate: validateRequiredString},
			{name: "shut-none", optionCaps: capFD, desc: "do not half-close; do not kill EXEC child on close", validate: validateOptionalBool},
			{name: "shut-down", optionCaps: capFD, desc: "shutdown(SHUT_WR) instead of the address default", validate: validateOptionalBool},
			{name: "shut-close", optionCaps: capFD, desc: "fully close instead of half-closing", validate: validateOptionalBool},
			{name: "end-close", optionCaps: capFD, desc: "close on EOF", aliases: []string{"close"}},
			{name: "shut", optionCaps: capFD, desc: "half-close mode (none, down, close, or null)", validate: validateShutOption},
			{name: "shut-null", optionCaps: capFD, desc: "0-byte datagram as half-close", validate: validateOptionalBool},
		}},
		{"PTY and TERMIOS", []helpOpt{
			{name: "link", optionCaps: capPTY, desc: "symlink to the PTY slave", aliases: []string{"symbolic-link"}},
			{name: "raw", optionCaps: capTermios, desc: "obsolete raw termios mode"},
			{name: "cfmakeraw", optionCaps: capTermios, desc: "raw termios (cfmakeraw)", aliases: []string{"termios-cfmakeraw"}},
			{name: "rawer", optionCaps: capTermios, desc: "stricter raw termios", aliases: []string{"termios-rawer"}},
			{name: "sane", optionCaps: capTermios, desc: "reset termios to sane defaults"},
			{name: "echo", optionCaps: capTermios, desc: "terminal echo"},
			{name: "echoe", optionCaps: capTermios, desc: "ECHOE", aliases: []string{"crterase"}},
			{name: "echoke", optionCaps: capTermios, desc: "ECHOKE", aliases: []string{"crtkill"}},
			{name: "echoctl", optionCaps: capTermios, desc: "ECHOCTL", aliases: []string{"ctlecho"}},
			{name: "hupcl", optionCaps: capTermios, desc: "HUPCL", aliases: []string{"hup"}},
			{name: "ixoff", optionCaps: capTermios, desc: "IXOFF", aliases: []string{"tandem"}},
			{name: "opost", optionCaps: capTermios, desc: "output post-processing"},
			{name: "ispeed", optionCaps: capTermios, desc: "input baud"},
			{name: "ospeed", optionCaps: capTermios, desc: "output baud"},
			{name: "tiocswinsz", optionCaps: capTermios, desc: "window size cols:rows", aliases: []string{"winsz"}},
			{name: "pty-wait-slave", optionCaps: capPTY, desc: "wait until the slave is open", aliases: []string{"wait-slave", "waitslave"}},
			{name: "pty-interval", optionCaps: capPTY, desc: "poll interval while waiting for slave", aliases: []string{"pty-intervall"}, validate: validateDurationOption},
			{name: "sitout-eio", optionCaps: capPTY, desc: "wait this long on PTY master EIO after the slave closes", validate: validateDurationOption},
			{name: "ctty", optionCaps: capTermios, desc: "make the PTY the controlling tty", aliases: []string{"tiocsctty"}},
			{name: "ptmx", optionCaps: capPTY, desc: "run on a pseudo-terminal via /dev/ptmx"},
			{name: "escape", unrestricted: true, desc: "escape character"},
		}},
	}
}
