package cli

import "github.com/oittaa/socat/internal/xio"

// Socket, IP, and TCP options.
func socketOptionGroups() []helpOptGroup {
	return []helpOptGroup{
		{"Sockets", []helpOpt{
			{name: "nodelay", desc: "TCP_NODELAY", aliases: []string{"tcp-nodelay"}, addressTypes: tcpStreamAddressTypes()},
			{name: "keepalive", desc: "SO_KEEPALIVE", aliases: []string{"so-keepalive"}, addressTypes: tcpStreamAddressTypes()},
			{name: "keepidle", desc: "TCP_KEEPIDLE idle time (requires keepalive)", aliases: []string{"so-keepidle", "tcp-keepidle"}, addressTypes: tcpStreamAddressTypes(), validate: validateDurationOption},
			{name: "keepintvl", desc: "TCP_KEEPINTVL probe interval", aliases: []string{"so-keepintvl", "tcp-keepintvl"}, addressTypes: tcpStreamAddressTypes(), validate: validateDurationOption},
			{name: "keepcnt", desc: "TCP_KEEPCNT probe count", aliases: []string{"so-keepcnt", "tcp-keepcnt"}, addressTypes: tcpStreamAddressTypes(), validate: validateInteger(1)},
			{name: "broadcast", desc: "SO_BROADCAST", aliases: []string{"so-broadcast"}},
			{name: "so-debug", desc: "SO_DEBUG", aliases: []string{"debug"}},
			{name: "so-dontroute", desc: "SO_DONTROUTE", aliases: []string{"dontroute"}},
			{name: "so-oobinline", desc: "SO_OOBINLINE", aliases: []string{"oobinline"}},
			{name: "so-rcvlowat", desc: "SO_RCVLOWAT receive low-water mark", aliases: []string{"rcvlowat"}, validate: validateOptionalSignedInteger},
			{name: "so-sndlowat", desc: "SO_SNDLOWAT send low-water mark", aliases: []string{"sndlowat"}, validate: validateOptionalSignedInteger},
			{name: "so-priority", desc: "SO_PRIORITY (Linux)", aliases: []string{"priority"}},
			{name: "so-passcred", desc: "SO_PASSCRED (Linux)", aliases: []string{"passcred"}},
			{name: "so-no-check", desc: "SO_NO_CHECK (Linux)", aliases: []string{"no-check", "nocheck"}},
			{name: "tcp-cork", desc: "TCP_CORK (Linux)", aliases: []string{"cork"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-defer-accept", desc: "TCP_DEFER_ACCEPT seconds (Linux)", aliases: []string{"defer-accept"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-linger2", desc: "TCP_LINGER2 FIN_WAIT-2 timeout in seconds (Linux)", aliases: []string{"linger2"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-maxseg", desc: "TCP_MAXSEG after socket (PH_PASTSOCKET)", aliases: []string{"maxseg", "mss"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-maxseg-late", desc: "TCP_MAXSEG after connect or accept (PH_CONNECTED)", aliases: []string{"maxseg-late", "mss-late"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-quickack", desc: "TCP_QUICKACK (Linux)", aliases: []string{"quickack"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-syncnt", desc: "TCP_SYNCNT SYN retries (Linux)", aliases: []string{"syncnt"}, addressTypes: tcpStreamAddressTypes()},
			{name: "tcp-window-clamp", desc: "TCP_WINDOW_CLAMP advertised window (Linux)", aliases: []string{"window-clamp"}, addressTypes: tcpStreamAddressTypes()},
			{name: "nopush", desc: "TCP_NOPUSH (Darwin/BSD)", aliases: []string{"tcp-nopush"}, addressTypes: tcpStreamAddressTypes()},
			{name: "noopt", desc: "TCP_NOOPT (Darwin/BSD)", aliases: []string{"tcp-noopt"}, addressTypes: tcpStreamAddressTypes()},
			{name: "sctp-nodelay", desc: "SCTP_NODELAY (Linux)", implementationGroups: []string{xio.GroupSCTP}},
			{name: "sctp-maxseg", desc: "SCTP_MAXSEG after socket (PH_PASTSOCKET)", implementationGroups: []string{xio.GroupSCTP}},
			{name: "ip-add-membership", desc: "IPv4 multicast join (IP_ADD_MEMBERSHIP)", aliases: []string{"add-membership", "ip-membership", "membership"}, validate: validateRequiredString},
			{name: "ipv6-join-group", desc: "IPv6 multicast join (IPV6_JOIN_GROUP)", aliases: []string{"ipv6-add-membership", "join-group"}, validate: validateRequiredString},
			{name: "ip-multicast-if", desc: "IPv4 multicast interface (IP_MULTICAST_IF)", aliases: []string{"multicast-if"}, validate: validateRequiredString},
			{name: "ip-multicast-loop", desc: "multicast loopback (IP_MULTICAST_LOOP)", aliases: []string{"multicast-loop", "mcloop", "ipmulticastloop", "multicastloop"}, validate: validateOptionalBool},
			{name: "ip-multicast-ttl", desc: "multicast TTL (IP_MULTICAST_TTL)", aliases: []string{"multicast-ttl", "ipmulticastttl", "multicastttl"}, validate: validateOptionalByte},
			{name: "ipv6-multicast-loop", desc: "IPv6 multicast loopback (IPV6_MULTICAST_LOOP)", aliases: []string{"ipv6-mcloop", "mcloop6"}, validate: validateOptionalBool},
			{name: "ip-mtu-discover", desc: "IPv4 path MTU discovery policy (IP_MTU_DISCOVER)", aliases: []string{"mtudiscover", "ipmtudiscover"}, validate: validateIntegerRange(0, 2)},
			{name: "ipv6-mtu-discover", desc: "IPv6 path MTU discovery policy (IPV6_MTU_DISCOVER)", aliases: []string{"mtudiscover6"}, validate: validateIntegerRange(0, 2)},
			{name: "ip-add-source-membership", desc: "IPv4 source-specific multicast join (IP_ADD_SOURCE_MEMBERSHIP)", aliases: []string{"add-source-membership", "source-membership"}, validate: validateRequiredString},
			{name: "ipv6-join-source-group", desc: "IPv6 source-specific multicast join (MCAST_JOIN_SOURCE_GROUP)", aliases: []string{"ipv6-add-source-membership", "join-source-group"}, validate: validateRequiredString},
			{name: "ip-freebind", desc: "IP_FREEBIND (Linux)", aliases: []string{"freebind", "ipfreebind"}, validate: validateOptionalSignedInteger},
			{name: "ip-transparent", desc: "IP_TRANSPARENT before bind (Linux)", aliases: []string{"transparent"}, validate: validateOptionalBool},
			{name: "setsockopt", desc: "raw setsockopt after connect (dalan value)", aliases: []string{"sockopt"}, validate: validateSockoptBin},
			{name: "setsockopt-int", desc: "raw setsockopt after connect (int value)", aliases: []string{"sockopt-int"}, validate: validateSockoptInt},
			{name: "setsockopt-bin", desc: "raw setsockopt after connect (binary value)", aliases: []string{"sockopt-bin"}, validate: validateSockoptBin},
			{name: "setsockopt-string", desc: "raw setsockopt after connect (string value)", aliases: []string{"sockopt-string"}, validate: validateSockoptString},
			{name: "setsockopt-listen", desc: "raw setsockopt before bind (dalan value)", aliases: []string{"sockopt-listen"}, validate: validateSockoptBin},
			{name: "setsockopt-socket", desc: "raw setsockopt after socket (dalan value)", aliases: []string{"sockopt-sock"}, validate: validateSockoptBin},
			{name: "setsockopt-connected", desc: "raw setsockopt after connect (dalan value)", aliases: []string{"sockopt-conn"}, validate: validateSockoptBin},
			{name: "so-timestamp", desc: "SO_TIMESTAMP ancillary", aliases: []string{"timestamp"}, implementationGroups: xio.IPAncillaryImplementationGroups("so-timestamp")},
			{name: "ip-pktinfo", desc: "IP_PKTINFO", aliases: []string{"pktinfo", "ippktinfo"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-pktinfo")},
			{name: "ip-recvttl", desc: "IP_RECVTTL", aliases: []string{"recvttl", "iprecvttl"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvttl")},
			{name: "ip-recvtos", desc: "IP_RECVTOS", aliases: []string{"recvtos", "iprecvtos"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvtos")},
			{name: "ip-recvopts", desc: "IP_RECVOPTS", aliases: []string{"recvopts", "iprecvopts"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvopts")},
			{name: "ip-recvdstaddr", desc: "IP_RECVDSTADDR (Darwin)", aliases: []string{"recvdstaddr", "iprecvdstaddr"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvdstaddr")},
			{name: "ip-recvif", desc: "IP_RECVIF (Darwin)", aliases: []string{"recvif"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-recvif")},
			{name: "ip-ttl", desc: "IP_TTL", aliases: []string{"ttl", "ipttl"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-ttl"), validate: validateInteger(-1)},
			{name: "ip-tos", desc: "IP_TOS", aliases: []string{"tos", "iptos"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-tos"), validate: validateInt64(false)},
			{name: "ip-options", desc: "IP_OPTIONS", aliases: []string{"ipoptions"}, implementationGroups: xio.IPAncillaryImplementationGroups("ip-options"), validate: validateRequiredString},
			{name: "ipv6-recvpktinfo", desc: "IPV6_RECVPKTINFO", aliases: []string{"recvpktinfo"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvpktinfo")},
			{name: "ipv6-recvhoplimit", desc: "IPV6_RECVHOPLIMIT", aliases: []string{"recvhoplimit"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvhoplimit")},
			{name: "ipv6-recvtclass", desc: "IPV6_RECVTCLASS", aliases: []string{"recvtclass"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-recvtclass")},
			{name: "ipv6-unicast-hops", desc: "IPV6_UNICAST_HOPS", aliases: []string{"unicast-hops"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-unicast-hops"), validate: validateInteger(-1)},
			{name: "ipv6-tclass", desc: "IPV6_TCLASS", aliases: []string{"tclass"}, implementationGroups: xio.IPAncillaryImplementationGroups("ipv6-tclass"), validate: validateInt64(false)},
			{name: "res-nsaddr", desc: "per-address IPv4 DNS nameserver host[:port]", aliases: []string{"dns", "nameserver", "nsaddr"}, addressTypes: resolverAddressTypes(), implementationGroups: resolverImplementationGroups(), validate: validateResNSAddr},
			{name: "rcvtimeo", desc: "per-operation socket receive timeout; retry after expiration", aliases: []string{"so-rcvtimeo"}, addressTypes: socketTimeoutAddressTypes(), validate: validateDurationOption},
			{name: "sndtimeo", desc: "per-operation socket send timeout; retry after expiration", aliases: []string{"so-sndtimeo"}, addressTypes: socketTimeoutAddressTypes(), validate: validateDurationOption},
			{name: "so-linger", desc: "SO_LINGER timeout in seconds", aliases: []string{"linger"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "sndbuf", desc: "SO_SNDBUF size in bytes", aliases: []string{"so-sndbuf"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "rcvbuf", desc: "SO_RCVBUF size in bytes", aliases: []string{"so-rcvbuf"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "sndbuf-late", desc: "SO_SNDBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)", aliases: []string{"so-sndbuf-late"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "rcvbuf-late", desc: "SO_RCVBUF after connect, accept, or bind (raw socket, before TLS/PROXY/QUIC wrapping)", aliases: []string{"so-rcvbuf-late"}, addressTypes: socketTimeoutAddressTypes(), validate: validateInteger(0)},
			{name: "bindtodevice", desc: "SO_BINDTODEVICE interface name", aliases: []string{"so-bindtodevice", "if", "interface"}, addressTypes: socketTimeoutAddressTypes(), validate: validateRequiredString},
			{name: "so-protocol", desc: "socket() protocol number", aliases: []string{"so-prototype", "prototype"}, implementationGroups: []string{xio.GroupVSOCK}, validate: validateInteger(-1)},
		}},
	}
}
