package parse

func init() {
	registerOptionAliases(map[string]string{
		// ipv6-join-group is a distinct classic option (GROUP_IP6 only,
		// tag-1.8.1.3 / 12c08bf). Do not fold it onto ip-add-membership
		// (IP4+IP6); validation is spelling-specific. Same-group nicknames
		// from classic -hhh fold onto their canonical descriptor.
		"add-membership":             "ip-add-membership",
		"ip-membership":              "ip-add-membership",
		"membership":                 "ip-add-membership",
		"ipv6-add-membership":        "ipv6-join-group",
		"join-group":                 "ipv6-join-group",
		"add-source-membership":      "ip-add-source-membership",
		"source-membership":          "ip-add-source-membership",
		"ipv6-add-source-membership": "ipv6-join-source-group",
		"join-source-group":          "ipv6-join-source-group",
		"multicast-if":               "ip-multicast-if",
		"multicast-loop":             "ip-multicast-loop",
		"mcloop":                     "ip-multicast-loop",
		"ipmulticastloop":            "ip-multicast-loop",
		"multicastloop":              "ip-multicast-loop",
		"multicast-ttl":              "ip-multicast-ttl",
		"ipmulticastttl":             "ip-multicast-ttl",
		"multicastttl":               "ip-multicast-ttl",
		"mtudiscover":                "ip-mtu-discover",
		"ipmtudiscover":              "ip-mtu-discover",
		"mtudiscover6":               "ipv6-mtu-discover",
		"ipv6-mcloop":                "ipv6-multicast-loop",
		"mcloop6":                    "ipv6-multicast-loop",
		"freebind":                   "ip-freebind",
		"ipfreebind":                 "ip-freebind",
		"transparent":                "ip-transparent",
		"recverr":                    "ip-recverr",
		"iprecverr":                  "ip-recverr",
		"so-reuseaddr":               "reuseaddr",
		"so-reuseport":               "reuseport",
		"so-keepalive":               "keepalive",
		"so-bindtodevice":            "bindtodevice",
		"if":                         "bindtodevice",
		"interface":                  "bindtodevice",
		"so-broadcast":               "broadcast",
		"so-rcvbuf":                  "rcvbuf",
		"so-sndbuf":                  "sndbuf",
		"so-rcvbuf-late":             "rcvbuf-late",
		"so-sndbuf-late":             "sndbuf-late",
		"so-rcvtimeo":                "rcvtimeo",
		"so-sndtimeo":                "sndtimeo",
		"so-prototype":               "so-protocol",
		"prototype":                  "so-protocol",
		"tcp-nodelay":                "nodelay",
		"tcp-keepalive":              "keepalive",
		"so-keepidle":                "keepidle",
		"so-keepintvl":               "keepintvl",
		"so-keepcnt":                 "keepcnt",
		"tcp-keepidle":               "keepidle",
		"tcp-keepintvl":              "keepintvl",
		"tcp-keepcnt":                "keepcnt",
		"ipttl":                      "ip-ttl",
		"ttl":                        "ip-ttl",
		"iptos":                      "ip-tos",
		"tos":                        "ip-tos",
		"ipoptions":                  "ip-options",
		"pktinfo":                    "ip-pktinfo",
		"ippktinfo":                  "ip-pktinfo",
		"recvttl":                    "ip-recvttl",
		"iprecvttl":                  "ip-recvttl",
		"recvtos":                    "ip-recvtos",
		"iprecvtos":                  "ip-recvtos",
		"recvopts":                   "ip-recvopts",
		"iprecvopts":                 "ip-recvopts",
		"timestamp":                  "so-timestamp",
		"recvpktinfo":                "ipv6-recvpktinfo",
		"recvhoplimit":               "ipv6-recvhoplimit",
		"recvtclass":                 "ipv6-recvtclass",
		"unicast-hops":               "ipv6-unicast-hops",
		"tclass":                     "ipv6-tclass",
		"sp":                         "sourceport",
		"sourceport":                 "sourceport",
		"sockopt-listen":             "setsockopt-listen",
		"sockopt":                    "setsockopt",
		"sockopt-int":                "setsockopt-int",
		"sockopt-bin":                "setsockopt-bin",
		"sockopt-string":             "setsockopt-string",
		"sockopt-sock":               "setsockopt-socket",
		"sockopt-conn":               "setsockopt-connected",
	})
}
