package parse

func init() {
	registerOptionAliases(map[string]string{
		"so-reuseaddr":    "reuseaddr",
		"so-reuseport":    "reuseport",
		"ipv6-join-group": "ip-add-membership",
		"so-keepalive":    "keepalive",
		"so-bindtodevice": "bindtodevice",
		"if":              "bindtodevice",
		"interface":       "bindtodevice",
		"so-broadcast":    "broadcast",
		"so-rcvbuf":       "rcvbuf",
		"so-sndbuf":       "sndbuf",
		"so-rcvbuf-late":  "rcvbuf-late",
		"so-sndbuf-late":  "sndbuf-late",
		"so-rcvtimeo":     "rcvtimeo",
		"so-sndtimeo":     "sndtimeo",
		"so-prototype":    "so-protocol",
		"prototype":       "so-protocol",
		"tcp-nodelay":     "nodelay",
		"tcp-keepalive":   "keepalive",
		"so-keepidle":     "keepidle",
		"so-keepintvl":    "keepintvl",
		"so-keepcnt":      "keepcnt",
		"tcp-keepidle":    "keepidle",
		"tcp-keepintvl":   "keepintvl",
		"tcp-keepcnt":     "keepcnt",
		"ipttl":           "ip-ttl",
		"ttl":             "ip-ttl",
		"iptos":           "ip-tos",
		"tos":             "ip-tos",
		"ipoptions":       "ip-options",
		"pktinfo":         "ip-pktinfo",
		"ippktinfo":       "ip-pktinfo",
		"recvttl":         "ip-recvttl",
		"iprecvttl":       "ip-recvttl",
		"recvtos":         "ip-recvtos",
		"iprecvtos":       "ip-recvtos",
		"recvopts":        "ip-recvopts",
		"iprecvopts":      "ip-recvopts",
		"timestamp":       "so-timestamp",
		"recvpktinfo":     "ipv6-recvpktinfo",
		"recvhoplimit":    "ipv6-recvhoplimit",
		"recvtclass":      "ipv6-recvtclass",
		"unicast-hops":    "ipv6-unicast-hops",
		"tclass":          "ipv6-tclass",
		"sp":              "sourceport",
		"sourceport":      "sourceport",
		"sockopt-listen":  "setsockopt-listen",
		"sockopt":         "setsockopt",
		"sockopt-int":     "setsockopt-int",
		"sockopt-bin":     "setsockopt-bin",
		"sockopt-string":  "setsockopt-string",
		"sockopt-sock":    "setsockopt-socket",
		"sockopt-conn":    "setsockopt-connected",
	})
}
