package parse

func init() {
	registerOptionAliases(map[string]string{
		// ipv6-join-group is a distinct classic option (GROUP_IP6 only,
		// tag-1.8.1.3 / 12c08bf). Do not fold it onto ip-add-membership
		// (IP4+IP6); validation is spelling-specific. Same-group nicknames
		// from classic -hhh fold onto their canonical descriptor.
		"add-membership":      "ip-add-membership",
		"ip-membership":       "ip-add-membership",
		"membership":          "ip-add-membership",
		"ipv6-add-membership": "ipv6-join-group",
		"join-group":          "ipv6-join-group",
		"so-reuseaddr":        "reuseaddr",
		"so-reuseport":        "reuseport",
		"so-keepalive":        "keepalive",
		"so-bindtodevice":     "bindtodevice",
		"if":                  "bindtodevice",
		"interface":           "bindtodevice",
		"so-broadcast":        "broadcast",
		"so-rcvbuf":           "rcvbuf",
		"so-sndbuf":           "sndbuf",
		"so-rcvbuf-late":      "rcvbuf-late",
		"so-sndbuf-late":      "sndbuf-late",
		"so-rcvtimeo":         "rcvtimeo",
		"so-sndtimeo":         "sndtimeo",
		"so-prototype":        "so-protocol",
		"prototype":           "so-protocol",
		"tcp-nodelay":         "nodelay",
		"tcp-keepalive":       "keepalive",
		"so-keepidle":         "keepidle",
		"so-keepintvl":        "keepintvl",
		"so-keepcnt":          "keepcnt",
		"tcp-keepidle":        "keepidle",
		"tcp-keepintvl":       "keepintvl",
		"tcp-keepcnt":         "keepcnt",
		"ipttl":               "ip-ttl",
		"ttl":                 "ip-ttl",
		"iptos":               "ip-tos",
		"tos":                 "ip-tos",
		"ipoptions":           "ip-options",
		"pktinfo":             "ip-pktinfo",
		"ippktinfo":           "ip-pktinfo",
		"recvttl":             "ip-recvttl",
		"iprecvttl":           "ip-recvttl",
		"recvtos":             "ip-recvtos",
		"iprecvtos":           "ip-recvtos",
		"recvopts":            "ip-recvopts",
		"iprecvopts":          "ip-recvopts",
		"timestamp":           "so-timestamp",
		"recvpktinfo":         "ipv6-recvpktinfo",
		"recvhoplimit":        "ipv6-recvhoplimit",
		"recvtclass":          "ipv6-recvtclass",
		"unicast-hops":        "ipv6-unicast-hops",
		"tclass":              "ipv6-tclass",
		"sp":                  "sourceport",
		"sourceport":          "sourceport",
		"sockopt-listen":      "setsockopt-listen",
		"sockopt":             "setsockopt",
		"sockopt-int":         "setsockopt-int",
		"sockopt-bin":         "setsockopt-bin",
		"sockopt-string":      "setsockopt-string",
		"sockopt-sock":        "setsockopt-socket",
		"sockopt-conn":        "setsockopt-connected",
		"debug":               "so-debug",
		"dontroute":           "so-dontroute",
		"oobinline":           "so-oobinline",
		"cork":                "tcp-cork",
		"defer-accept":        "tcp-defer-accept",
		"linger2":             "tcp-linger2",
		"maxseg":              "tcp-maxseg",
		"mss":                 "tcp-maxseg",
		"maxseg-late":         "tcp-maxseg-late",
		"mss-late":            "tcp-maxseg-late",
		"quickack":            "tcp-quickack",
		"syncnt":              "tcp-syncnt",
		"window-clamp":        "tcp-window-clamp",
	})
}
